import {createHash,randomBytes} from 'node:crypto';

const base64url=(value:Buffer)=>value.toString('base64url');
export function createPkcePair(){const verifier=base64url(randomBytes(48)),challenge=base64url(createHash('sha256').update(verifier).digest());return{verifier,challenge}}
type TokenResponse={access_token:string;expires_in:number;refresh_token?:string};
type Dependencies={clientId:string;redirectUri:string;openExternal:(url:string)=>Promise<unknown>;request:(url:string,init?:RequestInit)=>Promise<Response>;readRefreshToken:()=>Promise<string|null>;writeRefreshToken:(token:string|null)=>Promise<void>};
export class SpotifyAuthService{
  private pending?:{state:string;verifier:string};private access?:{token:string;expiresAt:number};
  constructor(private readonly deps:Dependencies){}
  async status(){return this.access&&this.access.expiresAt>Date.now()?{state:'connected' as const}:{state:(await this.deps.readRefreshToken())?'connected' as const:'disconnected' as const}}
  async connect(){if(!this.deps.clientId)throw new Error('SPOTIFY_CLIENT_ID_MISSING');const pair=createPkcePair(),state=base64url(randomBytes(24));this.pending={state,verifier:pair.verifier};const url=new URL('https://accounts.spotify.com/authorize');url.search=new URLSearchParams({client_id:this.deps.clientId,response_type:'code',redirect_uri:this.deps.redirectUri,code_challenge_method:'S256',code_challenge:pair.challenge,state,scope:'user-read-private'}).toString();await this.deps.openExternal(url.toString());return{state:'connecting' as const}}
  async completeCallback(callback:string){const url=new URL(callback);if(!this.pending||url.searchParams.get('state')!==this.pending.state)throw new Error('SPOTIFY_STATE_MISMATCH');const code=url.searchParams.get('code');if(!code)throw new Error('SPOTIFY_CALLBACK_FAILED');const response=await this.deps.request('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:this.deps.clientId,grant_type:'authorization_code',code,redirect_uri:this.deps.redirectUri,code_verifier:this.pending.verifier})});this.pending=undefined;if(!response.ok)throw new Error(`SPOTIFY_TOKEN_FAILED_${response.status}`);const token=await response.json() as TokenResponse;this.access={token:token.access_token,expiresAt:Date.now()+token.expires_in*1000-30000};if(token.refresh_token)await this.deps.writeRefreshToken(token.refresh_token);return{state:'connected' as const}}
  async accessToken(){if(this.access&&this.access.expiresAt>Date.now())return this.access.token;const refresh=await this.deps.readRefreshToken();if(!refresh)throw new Error('SPOTIFY_NOT_CONNECTED');const response=await this.deps.request('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:this.deps.clientId,grant_type:'refresh_token',refresh_token:refresh})});if(!response.ok){if(response.status===400||response.status===401)await this.deps.writeRefreshToken(null);throw new Error(`SPOTIFY_REFRESH_FAILED_${response.status}`)}const token=await response.json() as TokenResponse;this.access={token:token.access_token,expiresAt:Date.now()+token.expires_in*1000-30000};if(token.refresh_token)await this.deps.writeRefreshToken(token.refresh_token);return this.access.token}
  async disconnect(){this.pending=undefined;this.access=undefined;await this.deps.writeRefreshToken(null)}
}
