import fs from 'node:fs/promises';import path from 'node:path';
export type TranslationPackStatus='not-downloaded'|'queued'|'downloading'|'ready'|'error'|'update-available';
export interface TranslationPackDescriptor{key:string;source:string;target:string;model:string;revision:string;status:TranslationPackStatus;size?:number;downloadedBytes?:number;error?:string;requiredFiles?:string[]}
export interface TranslationPackProgress{key:string;status:TranslationPackStatus;downloadedBytes:number;totalBytes?:number;percent:number;error?:string}
export type PackDownloader=(descriptor:TranslationPackDescriptor,target:string,signal:AbortSignal,progress:(value:TranslationPackProgress)=>void)=>Promise<void>;
export class TranslationPackService{
  private listeners=new Set<(value:TranslationPackProgress)=>void>();private controllers=new Map<string,AbortController>();
  constructor(private root:string,private downloader:PackDownloader,private catalog:TranslationPackDescriptor[]=[]){ }
  onProgress(listener:(value:TranslationPackProgress)=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener)}
  activeDownloadCount(){return this.controllers.size}
  private emit(value:TranslationPackProgress){for(const listener of this.listeners)listener(value)}
  private async ready(item:TranslationPackDescriptor){try{const directory=path.join(this.root,item.key,item.revision),manifest=JSON.parse(await fs.readFile(path.join(directory,'manifest.json'),'utf8')),required=item.requiredFiles?.length?item.requiredFiles:manifest.files;if(manifest.key!==item.key||!Array.isArray(required)||!required.length)return false;for(const file of required)if((await fs.stat(path.join(directory,file))).size<=0)return false;return true}catch{return false}}
  async list(){return Promise.all(this.catalog.map(async item=>({...item,status:await this.ready(item)?'ready':'not-downloaded'} as TranslationPackDescriptor)))}
  async download(key:string,outer?:AbortSignal){const item=this.catalog.find(value=>value.key===key);if(!item)throw Error('UNKNOWN_TRANSLATION_PACK');if(this.controllers.has(key))throw Error('TRANSLATION_PACK_DOWNLOAD_ACTIVE');const controller=new AbortController();this.controllers.set(key,controller);const abort=()=>controller.abort();outer?.addEventListener('abort',abort,{once:true});const temp=path.join(this.root,`${key}.${Date.now()}.${Math.random().toString(16).slice(2)}.tmp`),final=path.join(this.root,key,item.revision);try{await fs.mkdir(this.root,{recursive:true});for(const entry of await fs.readdir(this.root).catch(()=>[]))if(entry.startsWith(`${key}.`)&&entry.endsWith('.tmp'))await fs.rm(path.join(this.root,entry),{recursive:true,force:true});await fs.mkdir(temp,{recursive:true});this.emit({key,status:'downloading',downloadedBytes:0,percent:0});await this.downloader(item,temp,controller.signal,value=>this.emit(value));if(controller.signal.aborted)throw Error('ABORT');const required=item.requiredFiles??[];if(!required.length)throw Error('PACK_FILES_UNDECLARED');for(const file of required)if((await fs.stat(path.join(temp,file))).size<=0)throw Error('PACK_FILE_EMPTY');await fs.writeFile(path.join(temp,'manifest.json'),JSON.stringify({key,revision:item.revision,files:required}));await fs.mkdir(path.dirname(final),{recursive:true});await fs.rm(final,{recursive:true,force:true});await fs.rename(temp,final);this.emit({key,status:'ready',downloadedBytes:1,totalBytes:1,percent:100});return true}catch(error){await fs.rm(temp,{recursive:true,force:true});const aborted=controller.signal.aborted;this.emit({key,status:aborted?'not-downloaded':'error',downloadedBytes:0,percent:0,error:aborted?undefined:String(error)});throw error}finally{outer?.removeEventListener('abort',abort);this.controllers.delete(key)}}
  cancel(key:string){this.controllers.get(key)?.abort();return true}
  async remove(key:string){if(!this.catalog.some(item=>item.key===key))throw Error('UNKNOWN_TRANSLATION_PACK');await fs.rm(path.join(this.root,key),{recursive:true,force:true});return true}
}
