import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import type { StorageKind, StorageObject, StorageProvider, StorageStatus } from './StorageProvider';

const folders:Record<StorageKind,string>={image:'images',video:'videos',audio:'audio',pdf:'documents'};
const kindFromPath=(value:string):StorageKind=>/\.(mp4|mov|webm|m4v)$/i.test(value)?'video':/\.(mp3|wav|m4a|ogg|flac)$/i.test(value)?'audio':/\.pdf$/i.test(value)?'pdf':'image';
const safeName=(value:string)=>value.normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'medium';

async function gitHubCredential(){return new Promise<string|null>(resolve=>{const child=spawn('git',['credential','fill'],{windowsHide:true,stdio:['pipe','pipe','ignore']}),chunks:Buffer[]=[];child.stdout.on('data',chunk=>chunks.push(Buffer.from(chunk)));child.on('error',()=>resolve(null));child.on('close',code=>{if(code!==0){resolve(null);return}const fields=Object.fromEntries(Buffer.concat(chunks).toString('utf8').split(/\r?\n/).map(line=>line.split(/=(.*)/s).slice(0,2)).filter(pair=>pair.length===2));resolve(fields.password||null)});child.stdin.end('protocol=https\nhost=github.com\n\n')})}

export class GitHubStorageProvider implements StorageProvider{
  constructor(private readonly owner='cmoere',private readonly repository='GottesdienstRegie-Media'){}
  private api(path=''){return `https://api.github.com/repos/${this.owner}/${this.repository}${path}`}
  private headers(token?:string|null){return{'accept':'application/vnd.github+json','user-agent':'GottesdienstRegie-MediaProvider',...(token?{authorization:`Bearer ${token}`}:{})}}
  async status():Promise<StorageStatus>{try{const response=await fetch(this.api(),{headers:this.headers(),signal:AbortSignal.timeout(8000)});if(!response.ok)return{provider:'github',online:false,writable:false,message:response.status===404?'Medien-Repository nicht gefunden.':`GitHub ist nicht erreichbar (${response.status}).`};return{provider:'github',online:true,writable:!!await gitHubCredential(),message:'GitHub-Medienbibliothek verbunden.'}}catch{return{provider:'github',online:false,writable:false,message:'GitHub-Medienbibliothek ist offline.'}}}
  async list():Promise<StorageObject[]>{const response=await fetch(this.api('/git/trees/main?recursive=1'),{headers:this.headers(),signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error('MEDIA_LIBRARY_UNAVAILABLE');const json=await response.json() as {tree?:Array<{path:string;type:string;size?:number;sha:string;url:string}>};return(json.tree??[]).filter(entry=>entry.type==='blob'&&!entry.path.startsWith('metadata/')&&!entry.path.endsWith('.md')&&!entry.path.endsWith('.gitkeep')).map(entry=>({id:entry.sha,name:entry.path.split('/').at(-1)??entry.path,path:entry.path,kind:kindFromPath(entry.path),size:entry.size??0,checksum:entry.sha,downloadUrl:`https://raw.githubusercontent.com/${this.owner}/${this.repository}/main/${entry.path.split('/').map(encodeURIComponent).join('/')}`}))}
  async upload(input:{name:string;kind:StorageKind;checksum:string;data:Buffer}):Promise<StorageObject>{if(input.kind==='video'&&input.data.byteLength>80*1024*1024)throw new Error('MEDIA_TOO_LARGE_FOR_GITHUB');const token=await gitHubCredential();if(!token)throw new Error('GITHUB_LOGIN_REQUIRED');const existing=(await this.list().catch(()=>[])).find(item=>item.name.startsWith(input.checksum));if(existing)return existing;const extension=input.name.includes('.')?`.${input.name.split('.').at(-1)}`:'',path=`${folders[input.kind]}/${input.checksum}-${safeName(input.name.replace(extension,''))}${extension}`,response=await fetch(this.api(`/contents/${path.split('/').map(encodeURIComponent).join('/')}`),{method:'PUT',headers:{...this.headers(token),'content-type':'application/json'},body:JSON.stringify({message:`Medienupload: ${input.name}`,content:input.data.toString('base64'),branch:'main'}),signal:AbortSignal.timeout(120000)});if(!response.ok)throw new Error(`MEDIA_UPLOAD_${response.status}`);const json=await response.json() as {content:{sha:string;download_url:string;size:number}};return{id:json.content.sha,name:input.name,path,kind:input.kind,size:json.content.size,checksum:createHash('sha256').update(input.data).digest('hex'),downloadUrl:json.content.download_url}}
}
