import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import type { StorageKind, StorageObject, StorageProvider, StorageStatus } from './StorageProvider';

const folders:Record<StorageKind,string>={image:'images',video:'videos',audio:'audio',pdf:'documents'};
const kindFromPath=(value:string):StorageKind=>/\.(mp4|mov|webm|m4v)$/i.test(value)?'video':/\.(mp3|wav|m4a|ogg|flac)$/i.test(value)?'audio':/\.pdf$/i.test(value)?'pdf':'image';
const safeName=(value:string)=>value.normalize('NFKD').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'')||'medium';

async function gitHubCredential(owner=''){return new Promise<string|null>(resolve=>{const child=spawn('git',['credential','fill'],{windowsHide:true,stdio:['pipe','pipe','ignore']}),chunks:Buffer[]=[];child.stdout.on('data',chunk=>chunks.push(Buffer.from(chunk)));child.on('error',()=>resolve(null));child.on('close',code=>{if(code!==0){resolve(null);return}const fields=Object.fromEntries(Buffer.concat(chunks).toString('utf8').split(/\r?\n/).map(line=>line.split(/=(.*)/s).slice(0,2)).filter(pair=>pair.length===2));resolve(fields.password||fields.oauth_token||null)});child.stdin.end(`protocol=https\nhost=github.com\n${owner?`username=${owner}\n`:''}\n`)})}

export class GitHubStorageProvider implements StorageProvider{
  constructor(private readonly owner='cmoere',private readonly repository='GottesdienstRegie-Media'){}
  private api(path=''){return `https://api.github.com/repos/${this.owner}/${this.repository}${path}`}
  private headers(token?:string|null){return{'accept':'application/vnd.github+json','user-agent':'GottesdienstRegie-MediaProvider',...(token?{authorization:`Bearer ${token}`}:{})}}
  async status():Promise<StorageStatus>{try{const token=await gitHubCredential(this.owner),response=await fetch(this.api(),{headers:this.headers(token),signal:AbortSignal.timeout(8000)});if(!response.ok)return{provider:'github',online:false,writable:false,message:response.status===404?'Medien-Cloud wurde nicht gefunden.':`Medien-Cloud ist nicht erreichbar (${response.status}).`};const repository=await response.json() as {private?:boolean;permissions?:{push?:boolean}};if(repository.private!==true)return{provider:'github',online:true,writable:false,message:'MEDIA_STORAGE_NOT_PRIVATE'};return{provider:'github',online:true,writable:repository.permissions?.push===true,message:repository.permissions?.push===true?'Bereit':'UPLOAD_PERMISSION_REQUIRED'}}catch{return{provider:'github',online:false,writable:false,message:'MEDIA_STORAGE_OFFLINE'}}}
  async list():Promise<StorageObject[]>{const token=await gitHubCredential(this.owner),response=await fetch(this.api('/git/trees/main?recursive=1'),{headers:this.headers(token),signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`MEDIA_LIBRARY_HTTP_${response.status}`);const json=await response.json() as {tree?:Array<{path:string;type:string;size?:number;sha:string;url:string}>};return(json.tree??[]).filter(entry=>entry.type==='blob'&&!entry.path.startsWith('metadata/')&&!entry.path.endsWith('.md')&&!entry.path.endsWith('.gitkeep')).map(entry=>({id:entry.sha,name:entry.path.split('/').at(-1)??entry.path,path:entry.path,kind:kindFromPath(entry.path),size:entry.size??0,checksum:entry.sha,downloadUrl:`gottesdienst-cloud://media/${encodeURIComponent(entry.path)}`}))}
  private async assertPrivateWritable(){const status=await this.status();if(status.message==='MEDIA_STORAGE_NOT_PRIVATE')throw new Error('MEDIA_STORAGE_NOT_PRIVATE');if(!status.online)throw new Error('MEDIA_STORAGE_OFFLINE');if(!status.writable)throw new Error('UPLOAD_PERMISSION_REQUIRED')}
  async upload(input:{name:string;kind:StorageKind;checksum:string;data:Buffer}):Promise<StorageObject>{if(input.kind==='video'&&input.data.byteLength>80*1024*1024)throw new Error('MEDIA_TOO_LARGE_FOR_GITHUB');await this.assertPrivateWritable();const token=await gitHubCredential(this.owner);if(!token)throw new Error('GITHUB_LOGIN_REQUIRED');const existing=(await this.list().catch(()=>[])).find(item=>item.name.startsWith(input.checksum));if(existing)return existing;const extension=input.name.includes('.')?`.${input.name.split('.').at(-1)}`:'',path=`${folders[input.kind]}/${input.checksum}-${safeName(input.name.replace(extension,''))}${extension}`,url=this.api(`/contents/${path.split('/').map(encodeURIComponent).join('/')}`),body=JSON.stringify({message:`Medienupload: ${input.name}`,content:input.data.toString('base64'),branch:'main'});let response:Response|undefined;for(let attempt=0;attempt<3;attempt++){try{response=await fetch(url,{method:'PUT',headers:{...this.headers(token),'content-type':'application/json'},body,signal:AbortSignal.timeout(120000)});if(response.ok||response.status<500)break}catch{if(attempt===2)throw new Error('MEDIA_STORAGE_OFFLINE')}}if(!response)throw new Error('MEDIA_STORAGE_OFFLINE');if(!response.ok){const detail=await response.json().catch(()=>({})) as {message?:string};throw new Error(`MEDIA_UPLOAD_HTTP_${response.status}:${String(detail.message??'').slice(0,160)}`)}const json=await response.json() as {content:{sha:string;download_url:string;size:number}};return{id:json.content.sha,name:input.name,path,kind:input.kind,size:json.content.size,checksum:createHash('sha256').update(input.data).digest('hex'),downloadUrl:`gottesdienst-cloud://media/${encodeURIComponent(path)}`}}
  async download(path:string){const token=await gitHubCredential(this.owner);if(!token)throw new Error('GITHUB_LOGIN_REQUIRED');const response=await fetch(this.api(`/contents/${path.split('/').map(encodeURIComponent).join('/')}`),{headers:{...this.headers(token),accept:'application/vnd.github.raw+json'},signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`MEDIA_DOWNLOAD_${response.status}`);return Buffer.from(await response.arrayBuffer())}
  async remove(path:string,sha:string){const token=await gitHubCredential(this.owner);if(!token)throw new Error('GITHUB_LOGIN_REQUIRED');const response=await fetch(this.api(`/contents/${path.split('/').map(encodeURIComponent).join('/')}`),{method:'DELETE',headers:{...this.headers(token),'content-type':'application/json'},body:JSON.stringify({message:`Medium entfernen: ${path.split('/').at(-1)}`,sha,branch:'main'}),signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error(`MEDIA_DELETE_${response.status}`);return true}
}
