import { useEffect, useMemo, useRef, useState } from 'react';
import { DndContext, closestCenter, type DragEndEvent } from '@dnd-kit/core';
import { SortableContext, verticalListSortingStrategy, useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { usePresentation, presentationDocument, type DisplayRole, type ItemType, type ServiceItem, type Slide } from './store';
import { SlideRenderer } from './SlideRenderer';
import { liveEngine } from './LiveEngine';
import { authMessage, cancelTwoFactor, isTwoFactorChallenge, login, logout, restore, twoFactorMessage, verifyTwoFactor, type AuthSession, type TwoFactorChallenge } from './auth';
import { useI18n, type TranslationKey, type Translator } from './i18n';
import { usePreferences, type Language, type ThemeMode } from './preferences';

function Icon({name}:{name:string}){return <span className="material-symbols-outlined" aria-hidden="true">{name}</span>}
const X=()=> <Icon name="close"/>;
const LogOut=()=> <Icon name="logout"/>;
const languageOptions:{value:Language;label:TranslationKey;flag:string}[]=[
  {value:'de',label:'languageGerman',flag:'🇩🇪'},{value:'gsw',label:'languageSwissGerman',flag:'🇨🇭'},{value:'en',label:'languageEnglish',flag:'🇬🇧'},
  {value:'nl',label:'languageDutch',flag:'🇳🇱'},{value:'da',label:'languageDanish',flag:'🇩🇰'},{value:'no',label:'languageNorwegian',flag:'🇳🇴'},
  {value:'es',label:'languageSpanish',flag:'🇪🇸'},{value:'uk',label:'languageUkrainian',flag:'🇺🇦'},{value:'ru',label:'languageRussian',flag:'🇷🇺'},
  {value:'tr',label:'languageTurkish',flag:'🇹🇷'},{value:'ar',label:'languageArabic',flag:'🇸🇦'},{value:'pl',label:'languagePolish',flag:'🇵🇱'}
];

const extraLabels:Record<Language,Record<string,string>>={
  de:{versionDetails:'Versionsdetails',installedAt:'Installiert am',modifiedAt:'Dateidatum',fileSize:'Dateigröße',executable:'Programmdatei',previousVersion:'Vorherige Version',rollback:'VORHERIGE VERSION INSTALLIEREN',rollbackConfirm:'Die vorherige Version wird heruntergeladen und anschließend installiert. Fortfahren?',noPrevious:'Keine frühere installierbare Version gefunden.',audioHelp:'Wähle echte Lautsprecher- und Mikrofon-Geräte und teste den Signalweg.',speakers:'Lautsprecher',microphone:'Mikrofon',systemDefault:'Systemstandard',volume:'Ausgabelautstärke',inputGain:'Eingangsverstärkung',noiseSuppression:'Rauschunterdrückung',echoCancellation:'Echo-Unterdrückung',testSpeaker:'LAUTSPRECHER TESTEN',testMicrophone:'MIKROFON TESTEN',stopTest:'TEST STOPPEN',micLevel:'Mikrofonpegel',highContrast:'Hoher Kontrast',highContrastHelp:'Verstärkt Kontraste und Abgrenzungen.',largeText:'Größere Bedienoberfläche',largeTextHelp:'Vergrößert Texte und Bedienelemente.',strongFocus:'Deutlicher Tastaturfokus',strongFocusHelp:'Zeigt einen gut sichtbaren Fokusrahmen.',dyslexia:'Lesefreundliche Schrift',dyslexiaHelp:'Vergrößert Abstände und verbessert die Lesbarkeit.',rollbackDownloading:'Vorherige Version wird geladen'},
  gsw:{versionDetails:'Versionsdetails',installedAt:'Installiert am',modifiedAt:'Dateidatum',fileSize:'Dateigrössi',executable:'Programmdatei',previousVersion:'Vorherigi Version',rollback:'VORHERIGI VERSION INSTALLIERE',rollbackConfirm:'D vorherigi Version wird glade und denn installiert. Wiitermache?',noPrevious:'Kei früehneri installierbari Version gfunde.',audioHelp:'Wähl Lautsprecher und Mikrofon und test de Signalwäg.',speakers:'Lautsprecher',microphone:'Mikrofon',systemDefault:'Systemstandard',volume:'Usgabeluutstärchi',inputGain:'Iigangsverstärkig',noiseSuppression:'Ruschunterdrückig',echoCancellation:'Echo-Unterdrückig',testSpeaker:'LAUTSPRECHER TESTE',testMicrophone:'MIKROFON TESTE',stopTest:'TEST STOPPE',micLevel:'Mikrofonpegel',highContrast:'Hoche Kontrast',highContrastHelp:'Verstärkt Kontrast und Abgränzige.',largeText:'Grössri Bedienoberflächi',largeTextHelp:'Vergrössert Text und Bedienelement.',strongFocus:'Dütliche Tastaturfokus',strongFocusHelp:'Zeigt en guet sichtbare Fokusrahme.',dyslexia:'Läsfründlichi Schrift',dyslexiaHelp:'Vergrössert Abständ und verbessert d Läsbarkeit.',rollbackDownloading:'Vorherigi Version wird glade'},
  en:{versionDetails:'Version details',installedAt:'Installed',modifiedAt:'File date',fileSize:'File size',executable:'Application file',previousVersion:'Previous version',rollback:'INSTALL PREVIOUS VERSION',rollbackConfirm:'The previous version will be downloaded and installed. Continue?',noPrevious:'No earlier installable version was found.',audioHelp:'Select real speaker and microphone devices and test the signal path.',speakers:'Speakers',microphone:'Microphone',systemDefault:'System default',volume:'Output volume',inputGain:'Input gain',noiseSuppression:'Noise suppression',echoCancellation:'Echo cancellation',testSpeaker:'TEST SPEAKERS',testMicrophone:'TEST MICROPHONE',stopTest:'STOP TEST',micLevel:'Microphone level',highContrast:'High contrast',highContrastHelp:'Strengthens contrast and boundaries.',largeText:'Larger interface',largeTextHelp:'Enlarges text and controls.',strongFocus:'Strong keyboard focus',strongFocusHelp:'Shows a clearly visible focus ring.',dyslexia:'Reading-friendly type',dyslexiaHelp:'Increases spacing and improves readability.',rollbackDownloading:'Downloading previous version'},
  nl:{versionDetails:'Versiedetails',installedAt:'Geïnstalleerd',modifiedAt:'Bestandsdatum',fileSize:'Bestandsgrootte',executable:'Programmabestand',previousVersion:'Vorige versie',rollback:'VORIGE VERSIE INSTALLEREN',rollbackConfirm:'De vorige versie wordt gedownload en geïnstalleerd. Doorgaan?',noPrevious:'Geen eerdere installeerbare versie gevonden.',audioHelp:'Kies echte luidsprekers en microfoons en test het signaal.',speakers:'Luidsprekers',microphone:'Microfoon',systemDefault:'Systeemstandaard',volume:'Uitvoervolume',inputGain:'Ingangsversterking',noiseSuppression:'Ruisonderdrukking',echoCancellation:'Echo-onderdrukking',testSpeaker:'LUIDSPREKERS TESTEN',testMicrophone:'MICROFOON TESTEN',stopTest:'TEST STOPPEN',micLevel:'Microfoonniveau',highContrast:'Hoog contrast',highContrastHelp:'Versterkt contrasten en randen.',largeText:'Grotere interface',largeTextHelp:'Vergroot tekst en bediening.',strongFocus:'Duidelijke toetsenbordfocus',strongFocusHelp:'Toont een zichtbare focusrand.',dyslexia:'Leesvriendelijk lettertype',dyslexiaHelp:'Vergroot afstanden en leesbaarheid.',rollbackDownloading:'Vorige versie downloaden'},
  da:{versionDetails:'Versionsdetaljer',installedAt:'Installeret',modifiedAt:'Fildato',fileSize:'Filstørrelse',executable:'Programfil',previousVersion:'Forrige version',rollback:'INSTALLER FORRIGE VERSION',rollbackConfirm:'Den forrige version downloades og installeres. Fortsæt?',noPrevious:'Ingen tidligere installerbar version fundet.',audioHelp:'Vælg højttalere og mikrofon, og test signalet.',speakers:'Højttalere',microphone:'Mikrofon',systemDefault:'Systemstandard',volume:'Udgangslydstyrke',inputGain:'Indgangsforstærkning',noiseSuppression:'Støjreduktion',echoCancellation:'Ekkoreduktion',testSpeaker:'TEST HØJTTALERE',testMicrophone:'TEST MIKROFON',stopTest:'STOP TEST',micLevel:'Mikrofonniveau',highContrast:'Høj kontrast',highContrastHelp:'Forstærker kontraster og kanter.',largeText:'Større brugerflade',largeTextHelp:'Forstørrer tekst og knapper.',strongFocus:'Tydeligt tastaturfokus',strongFocusHelp:'Viser en tydelig fokusramme.',dyslexia:'Læsevenlig skrift',dyslexiaHelp:'Øger afstand og læsbarhed.',rollbackDownloading:'Downloader forrige version'},
  no:{versionDetails:'Versjonsdetaljer',installedAt:'Installert',modifiedAt:'Fildato',fileSize:'Filstørrelse',executable:'Programfil',previousVersion:'Forrige versjon',rollback:'INSTALLER FORRIGE VERSJON',rollbackConfirm:'Forrige versjon lastes ned og installeres. Fortsette?',noPrevious:'Ingen tidligere installerbar versjon funnet.',audioHelp:'Velg høyttalere og mikrofon, og test signalet.',speakers:'Høyttalere',microphone:'Mikrofon',systemDefault:'Systemstandard',volume:'Utgangsvolum',inputGain:'Inngangsforsterkning',noiseSuppression:'Støyreduksjon',echoCancellation:'Ekkoreduksjon',testSpeaker:'TEST HØYTTALERE',testMicrophone:'TEST MIKROFON',stopTest:'STOPP TEST',micLevel:'Mikrofonnivå',highContrast:'Høy kontrast',highContrastHelp:'Forsterker kontraster og kanter.',largeText:'Større grensesnitt',largeTextHelp:'Forstørrer tekst og kontroller.',strongFocus:'Tydelig tastaturfokus',strongFocusHelp:'Viser en tydelig fokusramme.',dyslexia:'Lesevennlig skrift',dyslexiaHelp:'Øker avstand og lesbarhet.',rollbackDownloading:'Laster ned forrige versjon'},
  es:{versionDetails:'Detalles de versión',installedAt:'Instalado',modifiedAt:'Fecha del archivo',fileSize:'Tamaño del archivo',executable:'Archivo de aplicación',previousVersion:'Versión anterior',rollback:'INSTALAR VERSIÓN ANTERIOR',rollbackConfirm:'Se descargará e instalará la versión anterior. ¿Continuar?',noPrevious:'No se encontró una versión anterior instalable.',audioHelp:'Selecciona altavoces y micrófono reales y prueba la señal.',speakers:'Altavoces',microphone:'Micrófono',systemDefault:'Predeterminado del sistema',volume:'Volumen de salida',inputGain:'Ganancia de entrada',noiseSuppression:'Supresión de ruido',echoCancellation:'Cancelación de eco',testSpeaker:'PROBAR ALTAVOCES',testMicrophone:'PROBAR MICRÓFONO',stopTest:'DETENER PRUEBA',micLevel:'Nivel del micrófono',highContrast:'Alto contraste',highContrastHelp:'Refuerza contrastes y límites.',largeText:'Interfaz más grande',largeTextHelp:'Amplía textos y controles.',strongFocus:'Foco de teclado visible',strongFocusHelp:'Muestra un marco de foco claro.',dyslexia:'Tipografía de fácil lectura',dyslexiaHelp:'Aumenta el espaciado y la legibilidad.',rollbackDownloading:'Descargando versión anterior'},
  uk:{versionDetails:'Відомості про версію',installedAt:'Встановлено',modifiedAt:'Дата файлу',fileSize:'Розмір файлу',executable:'Файл програми',previousVersion:'Попередня версія',rollback:'ВСТАНОВИТИ ПОПЕРЕДНЮ ВЕРСІЮ',rollbackConfirm:'Попередню версію буде завантажено й встановлено. Продовжити?',noPrevious:'Попередньої версії для встановлення не знайдено.',audioHelp:'Виберіть динаміки й мікрофон та перевірте сигнал.',speakers:'Динаміки',microphone:'Мікрофон',systemDefault:'Системний пристрій',volume:'Гучність виходу',inputGain:'Підсилення входу',noiseSuppression:'Шумозаглушення',echoCancellation:'Приглушення відлуння',testSpeaker:'ПЕРЕВІРИТИ ДИНАМІКИ',testMicrophone:'ПЕРЕВІРИТИ МІКРОФОН',stopTest:'ЗУПИНИТИ ТЕСТ',micLevel:'Рівень мікрофона',highContrast:'Високий контраст',highContrastHelp:'Посилює контрасти й межі.',largeText:'Збільшений інтерфейс',largeTextHelp:'Збільшує текст і елементи.',strongFocus:'Помітний фокус клавіатури',strongFocusHelp:'Показує чітку рамку фокусу.',dyslexia:'Шрифт для легкого читання',dyslexiaHelp:'Збільшує інтервали й читабельність.',rollbackDownloading:'Завантаження попередньої версії'},
  ru:{versionDetails:'Сведения о версии',installedAt:'Установлено',modifiedAt:'Дата файла',fileSize:'Размер файла',executable:'Файл программы',previousVersion:'Предыдущая версия',rollback:'УСТАНОВИТЬ ПРЕДЫДУЩУЮ ВЕРСИЮ',rollbackConfirm:'Предыдущая версия будет загружена и установлена. Продолжить?',noPrevious:'Предыдущая устанавливаемая версия не найдена.',audioHelp:'Выберите динамики и микрофон и проверьте сигнал.',speakers:'Динамики',microphone:'Микрофон',systemDefault:'Системное устройство',volume:'Громкость выхода',inputGain:'Усиление входа',noiseSuppression:'Шумоподавление',echoCancellation:'Подавление эха',testSpeaker:'ПРОВЕРИТЬ ДИНАМИКИ',testMicrophone:'ПРОВЕРИТЬ МИКРОФОН',stopTest:'ОСТАНОВИТЬ ТЕСТ',micLevel:'Уровень микрофона',highContrast:'Высокий контраст',highContrastHelp:'Усиливает контрасты и границы.',largeText:'Увеличенный интерфейс',largeTextHelp:'Увеличивает текст и элементы.',strongFocus:'Заметный фокус клавиатуры',strongFocusHelp:'Показывает чёткую рамку фокуса.',dyslexia:'Удобный для чтения шрифт',dyslexiaHelp:'Увеличивает интервалы и читаемость.',rollbackDownloading:'Загрузка предыдущей версии'},
  tr:{versionDetails:'Sürüm ayrıntıları',installedAt:'Kurulum tarihi',modifiedAt:'Dosya tarihi',fileSize:'Dosya boyutu',executable:'Uygulama dosyası',previousVersion:'Önceki sürüm',rollback:'ÖNCEKİ SÜRÜMÜ KUR',rollbackConfirm:'Önceki sürüm indirilecek ve kurulacak. Devam edilsin mi?',noPrevious:'Kurulabilir önceki sürüm bulunamadı.',audioHelp:'Gerçek hoparlör ve mikrofonları seçip sinyali test edin.',speakers:'Hoparlörler',microphone:'Mikrofon',systemDefault:'Sistem varsayılanı',volume:'Çıkış sesi',inputGain:'Giriş kazancı',noiseSuppression:'Gürültü azaltma',echoCancellation:'Yankı giderme',testSpeaker:'HOPARLÖRÜ TEST ET',testMicrophone:'MİKROFONU TEST ET',stopTest:'TESTİ DURDUR',micLevel:'Mikrofon seviyesi',highContrast:'Yüksek kontrast',highContrastHelp:'Kontrastları ve sınırları güçlendirir.',largeText:'Daha büyük arayüz',largeTextHelp:'Metinleri ve kontrolleri büyütür.',strongFocus:'Belirgin klavye odağı',strongFocusHelp:'Belirgin bir odak çerçevesi gösterir.',dyslexia:'Okuma dostu yazı',dyslexiaHelp:'Aralığı ve okunabilirliği artırır.',rollbackDownloading:'Önceki sürüm indiriliyor'},
  ar:{versionDetails:'تفاصيل الإصدار',installedAt:'تاريخ التثبيت',modifiedAt:'تاريخ الملف',fileSize:'حجم الملف',executable:'ملف التطبيق',previousVersion:'الإصدار السابق',rollback:'تثبيت الإصدار السابق',rollbackConfirm:'سيتم تنزيل الإصدار السابق وتثبيته. هل تريد المتابعة؟',noPrevious:'لم يتم العثور على إصدار سابق قابل للتثبيت.',audioHelp:'اختر مكبرات الصوت والميكروفون الفعلية واختبر الإشارة.',speakers:'مكبرات الصوت',microphone:'الميكروفون',systemDefault:'افتراضي النظام',volume:'مستوى صوت الخرج',inputGain:'كسب الإدخال',noiseSuppression:'تقليل الضوضاء',echoCancellation:'إلغاء الصدى',testSpeaker:'اختبار مكبرات الصوت',testMicrophone:'اختبار الميكروفون',stopTest:'إيقاف الاختبار',micLevel:'مستوى الميكروفون',highContrast:'تباين عالٍ',highContrastHelp:'يقوي التباين والحدود.',largeText:'واجهة أكبر',largeTextHelp:'يكبر النص وعناصر التحكم.',strongFocus:'تركيز لوحة مفاتيح واضح',strongFocusHelp:'يعرض إطار تركيز واضحًا.',dyslexia:'خط سهل القراءة',dyslexiaHelp:'يزيد التباعد ويحسن القراءة.',rollbackDownloading:'جارٍ تنزيل الإصدار السابق'},
  pl:{versionDetails:'Szczegóły wersji',installedAt:'Zainstalowano',modifiedAt:'Data pliku',fileSize:'Rozmiar pliku',executable:'Plik aplikacji',previousVersion:'Poprzednia wersja',rollback:'ZAINSTALUJ POPRZEDNIĄ WERSJĘ',rollbackConfirm:'Poprzednia wersja zostanie pobrana i zainstalowana. Kontynuować?',noPrevious:'Nie znaleziono wcześniejszej wersji do instalacji.',audioHelp:'Wybierz głośniki i mikrofon oraz przetestuj sygnał.',speakers:'Głośniki',microphone:'Mikrofon',systemDefault:'Domyślne systemowe',volume:'Głośność wyjścia',inputGain:'Wzmocnienie wejścia',noiseSuppression:'Redukcja szumów',echoCancellation:'Redukcja echa',testSpeaker:'TESTUJ GŁOŚNIKI',testMicrophone:'TESTUJ MIKROFON',stopTest:'ZATRZYMAJ TEST',micLevel:'Poziom mikrofonu',highContrast:'Wysoki kontrast',highContrastHelp:'Wzmacnia kontrasty i granice.',largeText:'Większy interfejs',largeTextHelp:'Powiększa tekst i elementy.',strongFocus:'Wyraźny fokus klawiatury',strongFocusHelp:'Pokazuje widoczną ramkę fokusu.',dyslexia:'Krój ułatwiający czytanie',dyslexiaHelp:'Zwiększa odstępy i czytelność.',rollbackDownloading:'Pobieranie poprzedniej wersji'}
};

const loginImageModules=import.meta.glob<string>('./assets/login-backgrounds/*.png',{eager:true,query:'?url',import:'default'});
const allLoginImages=Object.values(loginImageModules);
function randomLoginImage(theme:ThemeMode){
  const dark=theme==='dark'||(theme==='system'&&typeof matchMedia!=='undefined'&&matchMedia('(prefers-color-scheme: dark)').matches);
  const themed=allLoginImages.filter((_image,index)=>dark?index%2===0:index%2===1);
  const images=themed.length?themed:allLoginImages;
  return images[Math.floor(Math.random()*images.length)];
}

function Login({authenticated}:{authenticated:(session:AuthSession)=>void}){
  const {t}=useI18n();
  const language=usePreferences(state=>state.language),setLanguage=usePreferences(state=>state.setLanguage);
  const theme=usePreferences(state=>state.theme),showLoginBackgrounds=usePreferences(state=>state.showLoginBackgrounds);
  const [email,setEmail]=useState('');
  const [password,setPassword]=useState('');
  const [showPassword,setShowPassword]=useState(false);
  const [remember,setRemember]=useState(true);
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const [connected,setConnected]=useState<boolean|null>(null);
  const [twoFactor,setTwoFactor]=useState<TwoFactorChallenge|null>(null);
  const [twoFactorCode,setTwoFactorCode]=useState('');
  const [recoveryMode,setRecoveryMode]=useState(false);
  const [twoFactorError,setTwoFactorError]=useState('');
  const [verifyBusy,setVerifyBusy]=useState(false);
  const [languageOpen,setLanguageOpen]=useState(false);
  const [backgroundImage]=useState(()=>randomLoginImage(theme));

  useEffect(()=>{
    let active=true;
    const check=()=>void window.desktop?.auth.connection().then(value=>active&&setConnected(value)).catch(()=>active&&setConnected(false));
    check();
    const timer=setInterval(check,15000);
    return()=>{active=false;clearInterval(timer)};
  },[]);

  async function submit(e:React.FormEvent){
    e.preventDefault();setBusy(true);setError('');
    try{
      const result=await login(email,password,remember);setPassword('');
      if(isTwoFactorChallenge(result)){setTwoFactor(result);setTwoFactorCode('');setRecoveryMode(false);setTwoFactorError('');return}
      authenticated(result);
    }catch(error){setPassword('');setError(authMessage(error instanceof Error?error.message:'SERVER',t))}
    finally{setBusy(false)}
  }

  async function confirmTwoFactor(e?:React.FormEvent){
    e?.preventDefault();if(!twoFactor||verifyBusy)return;
    const normalized=recoveryMode?twoFactorCode.toUpperCase().replace(/[^A-Z2-9]/g,''):twoFactorCode.replace(/\D/g,'');
    if((recoveryMode&&normalized.length!==12)||(!recoveryMode&&normalized.length!==6)){setTwoFactorError(t(recoveryMode?'recoveryIncomplete':'codeIncomplete'));return}
    setVerifyBusy(true);setTwoFactorError('');
    try{authenticated(await verifyTwoFactor(twoFactor.challengeId,twoFactorCode,recoveryMode));setTwoFactor(null)}
    catch(error){setTwoFactorError(twoFactorMessage(error instanceof Error?error.message:'SERVER',t));if(!recoveryMode)setTwoFactorCode('')}
    finally{setVerifyBusy(false)}
  }

  async function cancelChallenge(){
    if(twoFactor)await cancelTwoFactor(twoFactor.challengeId);
    setTwoFactor(null);setTwoFactorCode('');setRecoveryMode(false);setTwoFactorError('');
  }

  const twoFactorText=twoFactor?.method==='totp'?t('twoFactorTotp'):t('twoFactorSent',{destination:twoFactor?.destination||t('securityChannel')});
  useEffect(()=>{if(!twoFactor||recoveryMode||twoFactorCode.length!==6||verifyBusy)return;const timer=setTimeout(()=>void confirmTwoFactor(),220);return()=>clearTimeout(timer)},[twoFactorCode,recoveryMode,twoFactor,verifyBusy]);
  const selectedLanguage=languageOptions.find(option=>option.value===language)??languageOptions[0];
  return <>
    <main className={`login ${showLoginBackgrounds?'with-background':''}`} style={showLoginBackgrounds?{'--login-image':`url("${backgroundImage}")`} as React.CSSProperties:undefined}>
      <div className="login-language-menu"><button type="button" className="language-flag" onClick={()=>setLanguageOpen(value=>!value)} title={t('language')} aria-expanded={languageOpen}>{selectedLanguage.flag}</button>{languageOpen&&<div className="language-menu" role="menu">{languageOptions.map(option=><button type="button" role="menuitem" className={option.value===language?'active':''} key={option.value} onClick={()=>{setLanguage(option.value);setLanguageOpen(false)}}><span>{option.flag}</span>{t(option.label)}</button>)}</div>}</div>
      <form onSubmit={submit} className="login-panel">
        <div className="brand-mark">GR</div><h1>GottesdienstRegie</h1><p>{t('loginSubtitle')}</p>
        <label>{t('email')}<input autoFocus type="email" autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)} required/></label>
        <label>{t('password')}<div className="password-field"><input type={showPassword?'text':'password'} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShowPassword(value=>!value)} title={t(showPassword?'hidePassword':'showPassword')}><Icon name={showPassword?'visibility_off':'visibility'}/></button></div></label>
        <label className="remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> {t('remember')}</label>
        {error&&<div className="error">{error}</div>}
        <button className="primary" disabled={busy}>{t(busy?'signingIn':'signIn')}</button>
        <button type="button" className="forgot" disabled title={t('notAvailable')}>{t('forgotPassword')}</button>
      </form>
      <div className={`firebase-status ${connected===true?'connected':connected===false?'disconnected':''}`}><span/>{t(connected===null?'firebaseChecking':connected?'firebaseConnected':'firebaseDisconnected')}</div>
      {showLoginBackgrounds&&<span className="image-credit">{t('backgroundImageCredit')}</span>}
    </main>
    {twoFactor&&<div className="two-factor-backdrop"><form className="two-factor-dialog" onSubmit={confirmTwoFactor} role="dialog" aria-modal="true" aria-labelledby="two-factor-title">
      <header><div className="two-factor-icon"><Icon name="verified_user"/></div><div><h2 id="two-factor-title">{t('twoFactorTitle')}</h2><span>{t('twoFactorSubtitle')}</span></div></header>
      <p>{recoveryMode?t('recoveryIntro'):twoFactorText}</p>
      <label>{t(recoveryMode?'recoveryCode':'verificationCode')}<input autoFocus inputMode={recoveryMode?'text':'numeric'} autoComplete="one-time-code" maxLength={recoveryMode?14:6} placeholder={recoveryMode?'XXXX-XXXX-XXXX':'000000'} value={twoFactorCode} onChange={e=>{const value=recoveryMode?e.target.value.toUpperCase().replace(/[^A-Z2-9-]/g,'').slice(0,14):e.target.value.replace(/\D/g,'').slice(0,6);setTwoFactorCode(value);setTwoFactorError('')}}/></label>
      {twoFactorError&&<div className="error">{twoFactorError}</div>}
      <button className="recovery-toggle" type="button" onClick={()=>{setRecoveryMode(value=>!value);setTwoFactorCode('');setTwoFactorError('')}}>{t(recoveryMode?'useNormalCode':'useRecoveryCode')}</button>
      <div className="two-factor-actions"><button type="button" onClick={()=>void cancelChallenge()}>{t('cancel')}</button><button className="primary" disabled={verifyBusy}>{t(verifyBusy?'verifying':'confirm')}</button></div>
    </form></div>}
  </>;
}

function SortableItem({item,active,live,onSelect,canEdit}:{item:ServiceItem;active:boolean;live:boolean;onSelect:()=>void;canEdit:boolean}){
  const {t}=useI18n();
  const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:item.id,disabled:!canEdit});
  const icon:Record<ItemType,string>={song:'music_note',bible:'menu_book',content:'title',image:'image',video:'movie',audio:'audio_file',web:'language',pdf:'picture_as_pdf',timer:'timer',countdown:'hourglass_bottom'};
  return <button ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`service-item ${active?'active':''} ${live?'live-item':''} ${isDragging?'dragging':''}`} onClick={onSelect}><span className="drag" {...attributes} {...listeners}><Icon name="drag_indicator"/></span><span className="kind"><Icon name={icon[item.type]}/></span><span><b>{item.title}</b><small>{item.slides.length} {t(item.slides.length===1?'slidesOne':'slidesMany')}</small></span>{live&&<i className="live-dot"/>}</button>;
}

function AddPopover({close}:{close:()=>void}){
  const {t}=useI18n();
  const add=usePresentation(state=>state.addItem);
  const options:{type:ItemType;label:TranslationKey;title:TranslationKey;icon:string}[]=[{type:'content',label:'content',title:'newContent',icon:'title'}];
  return <div className="popover"><header><b>{t('addItem')}</b><button onClick={close}><Icon name="close"/></button></header>{options.map(option=><button key={option.type} onClick={()=>{add(option.type,{title:t(option.title),section:t('serviceSection'),body:t('editContent')});close()}}><Icon name={option.icon}/><span>{t(option.label)}</span></button>)}</div>;
}

function OrderOfService({canEdit}:{canEdit:boolean}){
  const {t}=useI18n();
  const items=usePresentation(state=>state.items),selected=usePresentation(state=>state.selectedItemId),live=usePresentation(state=>state.liveItemId),select=usePresentation(state=>state.select),reorder=usePresentation(state=>state.reorder);
  const [adding,setAdding]=useState(false);let last='';
  function end(e:DragEndEvent){if(canEdit&&e.over&&e.active.id!==e.over.id)reorder(String(e.active.id),String(e.over.id))}
  return <aside className="service"><header><b>{t('orderOfService')}</b><button className="icon-button" disabled={!canEdit} onClick={()=>setAdding(value=>!value)} title={t(canEdit?'addItem':'noEditPermission')}><Icon name="add"/></button>{adding&&canEdit&&<AddPopover close={()=>setAdding(false)}/>}</header><div className="service-list"><DndContext collisionDetection={closestCenter} onDragEnd={end}><SortableContext items={items.map(item=>item.id)} strategy={verticalListSortingStrategy}>{items.map(item=>{const show=item.section!==last;last=item.section;return <div key={item.id}>{show&&<div className="section-label">{item.section}</div>}<SortableItem item={item} active={selected===item.id} live={live===item.id} canEdit={canEdit} onSelect={()=>select(item.id)}/></div>})}</SortableContext></DndContext></div></aside>;
}

function LazyThumbnail({slide}:{slide:Slide}){
  const ref=useRef<HTMLDivElement>(null),[visible,setVisible]=useState(false);
  useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){setVisible(true);observer.disconnect()}},{rootMargin:'360px'});observer.observe(node);return()=>observer.disconnect()},[]);
  return <div ref={ref} className="lazy-thumbnail">{visible&&<SlideRenderer slide={slide} mode="thumbnail"/>}</div>;
}

function Workspace({canEdit}:{canEdit:boolean}){
  const {t}=useI18n();const state=usePresentation();const itemId=state.mode==='preview'?state.previewItemId:state.selectedItemId,slideId=state.mode==='preview'?state.previewSlideId:state.selectedSlideId;const item=state.items.find(entry=>entry.id===itemId)??state.items[0];const slide=item?.slides.find(entry=>entry.id===slideId)??item?.slides[0];
  if(!slide)return <section className="workspace empty">{t('noSlides')}</section>;
  if(state.mode==='preview')return <section className={`workspace preview-workspace ${state.previewLayout==='grid'?'preview-grid':''}`} style={{'--grid-size':`${state.gridSize}px`} as React.CSSProperties}>
    <div className="preview-toolbar"><div><button className={state.previewLayout==='single'?'active':''} onClick={()=>state.setPreviewLayout('single')}>{t('singleView')}</button><button className={state.previewLayout==='grid'?'active':''} onClick={()=>state.setPreviewLayout('grid')}>{t('slideOverview')}</button></div><label>MAIN <select aria-label="MAIN"><option>MAIN</option></select></label><label className="thumbnail-size"><span>{t('previewSize')}</span><Icon name="zoom_out"/><input type="range" min="120" max="320" value={state.gridSize} onChange={event=>state.setGridSize(Number(event.target.value))}/><Icon name="zoom_in"/></label></div>
    {state.previewLayout==='single'?<div className="preview-single"><div className="canvas-wrap"><SlideRenderer slide={slide} mode="preview"/></div></div>:<div className="preview-scroll">{state.sections.map(section=>{const entries=state.items.filter(entry=>entry.sectionId===section.id);return entries.length?<div className="preview-section" key={section.id}><h2>{section.title}</h2>{entries.map(entry=><div className="grid-item" key={entry.id}><h3>{entry.title}</h3><div className="grid-slides">{entry.slides.map((current,index)=>{const preview=current.id===state.previewSlideId&&entry.id===state.previewItemId,live=current.id===state.liveSlideId&&entry.id===state.liveItemId,canTakeLive=entry.enabled&&!entry.disabled&&current.enabled;return <div key={current.id} className={`grid-slide ${preview?'selected':''} ${live?'live-slide':''} ${!canTakeLive?'disabled-slide':''}`}><button className="thumbnail-hit" onClick={()=>state.onAir?(canTakeLive&&state.goLive(entry.id,current.id)):state.selectPreview(entry.id,current.id)} aria-label={`${entry.title}, ${t('slide')} ${index+1}`}><LazyThumbnail slide={current}/></button><span className="thumbnail-number">{index+1}</span>{live&&<i className="live-dot"/>}<div className="thumbnail-actions"><button onClick={()=>state.selectPreview(entry.id,current.id)}>{t('preview')}</button><button disabled={!canEdit} onClick={()=>{state.select(entry.id,current.id);state.setMode('edit')}}>{t('edit')}</button></div></div>})}</div></div>)}</div>:null})}</div>}
  </section>;
  return <section className="workspace"><div className="canvas-wrap"><SlideRenderer slide={slide} mode="editor"/></div></section>;
}

function Inspector({canEdit}:{canEdit:boolean}){
  const {t}=useI18n();const state=usePresentation();const item=state.items.find(entry=>entry.id===state.selectedItemId),slide=item?.slides.find(entry=>entry.id===state.selectedSlideId);
  return <aside className="inspector"><header><b>{t('properties')}</b><span>{t('layers')}</span></header>{slide?<div className="fields"><label>{t('title')}<input disabled={!canEdit} value={slide.title} onChange={e=>state.updateSlide({title:e.target.value})}/></label><label>{t('text')}<textarea disabled={!canEdit} rows={7} value={slide.body} onChange={e=>state.updateSlide({body:e.target.value})}/></label><label>{t('background')}<input disabled={!canEdit} type="color" value={slide.background} onChange={e=>state.updateSlide({background:e.target.value})}/></label></div>:null}</aside>;
}

function SortableSlide({slide,index,itemId}:{slide:Slide;index:number;itemId:string}){const state=usePresentation(),{attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:slide.id});return <button ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} className={`${slide.id===state.selectedSlideId?'active':''} ${slide.id===state.liveSlideId?'live-slide':''} ${!slide.enabled?'disabled-slide':''} ${isDragging?'dragging':''}`} onClick={()=>state.select(itemId,slide.id)} {...attributes} {...listeners}><SlideRenderer slide={slide} mode="thumbnail"/><span>{index+1}</span>{slide.id===state.liveSlideId&&<i className="live-dot"/>}</button>}
function Filmstrip(){const {t}=useI18n(),state=usePresentation(),item=state.items.find(entry=>entry.id===state.selectedItemId);function end(event:DragEndEvent){if(event.over&&event.active.id!==event.over.id)state.reorderSlides(String(event.active.id),String(event.over.id))}return <div className="filmstrip"><header><b>{t('slides')}</b><div className="slide-actions"><button onClick={state.addSlide} title="Neue Folie"><Icon name="add"/></button><button onClick={state.duplicateSlide} title="Duplizieren"><Icon name="content_copy"/></button><button onClick={state.copySlide} title="Kopieren"><Icon name="file_copy"/></button><button onClick={state.pasteSlide} disabled={!state.clipboard} title="Einfügen"><Icon name="content_paste"/></button><button onClick={()=>state.moveSlide(-1)} title="Nach links"><Icon name="arrow_back"/></button><button onClick={()=>state.moveSlide(1)} title="Nach rechts"><Icon name="arrow_forward"/></button><button onClick={state.toggleSlide} title="Aktivieren/Deaktivieren"><Icon name="visibility"/></button><button className="danger-icon" onClick={state.removeSlide} title="Löschen"><Icon name="delete"/></button></div></header><DndContext collisionDetection={closestCenter} onDragEnd={end}><SortableContext items={item?.slides.map(slide=>slide.id)??[]}><div>{item?.slides.map((slide,index)=><SortableSlide key={slide.id} slide={slide} index={index} itemId={item.id}/>)}</div></SortableContext></DndContext></div>}

function ExpandableItem({title,body}:{title:string;body:string}){const [open,setOpen]=useState(false);return <div className="expandable-item"><button type="button" onClick={()=>setOpen(value=>!value)} aria-expanded={open}><b>{open?'−':'+'}</b><span>{title}</span></button>{open&&<p>{body}</p>}</div>}

function plainReleaseNotes(value:string){if(!/<[a-z][\s\S]*>/i.test(value))return value;const document=new DOMParser().parseFromString(value,'text/html');document.querySelectorAll('br').forEach(node=>node.replaceWith('\n'));document.querySelectorAll('li').forEach(node=>node.prepend('• '));document.querySelectorAll('h1,h2,h3,h4,p,li').forEach(node=>node.append('\n'));return (document.body.textContent??value).replace(/\n\s*\n\s*\n/g,'\n\n').trim()}

type SettingsTab='general'|'accessibility'|'updates'|'display'|'audio'|'videoInput'|'presentation'|'quickScreens'|'fonts'|'defaultMedia'|'defaultStage'|'remote'|'lightingMidi';
const settingTabs:SettingsTab[]=['general','accessibility','updates','display','audio','videoInput','presentation','quickScreens','fonts','defaultMedia','defaultStage','remote','lightingMidi'];

function SettingsModal({close,canConfigure}:{close:()=>void;canConfigure:boolean}){
  const {t,locale}=useI18n();
  const [tab,setTab]=useState<SettingsTab>('general');
  const [displays,setDisplays]=useState<DesktopDisplay[]>([]);
  const [currentVersion,setCurrentVersion]=useState('…');
  const [versionMetadata,setVersionMetadata]=useState<DesktopVersionMetadata|null>(null);
  const [previousVersion,setPreviousVersion]=useState<DesktopPreviousVersion|null|undefined>(undefined);
  const [updateStatus,setUpdateStatus]=useState<DesktopUpdateStatus>({state:'idle'});
  const [audioDevices,setAudioDevices]=useState<MediaDeviceInfo[]>([]);
  const [micLevel,setMicLevel]=useState(0);
  const [micTesting,setMicTesting]=useState(false);
  const microphoneStream=useRef<MediaStream|null>(null);
  const displayRoles=usePresentation(state=>state.displayRoles),setDisplayRole=usePresentation(state=>state.setDisplayRole);
  const prefs=usePreferences();
  const {language,theme,blackWhite,reduceMotion,compactMode,showLoginBackgrounds,highContrast,largeText,strongFocus,dyslexiaFriendly,audioOutputDevice,audioInputDevice,outputVolume,inputGain,noiseSuppression,echoCancellation}=prefs;
  const {setLanguage,setTheme,setBlackWhite,setReduceMotion,setCompactMode,setShowLoginBackgrounds}=prefs;
  const L=extraLabels[language];
  useEffect(()=>{
    void window.desktop?.displays().then(setDisplays);
    void window.desktop?.updates.currentVersion().then(setCurrentVersion);
    void window.desktop?.updates.metadata().then(setVersionMetadata);
    void window.desktop?.updates.previous().then(setPreviousVersion).catch(()=>setPreviousVersion(null));
    void navigator.mediaDevices?.enumerateDevices().then(setAudioDevices).catch(()=>setAudioDevices([]));
    const displayDispose=window.desktop?.onDisplaysChanged(setDisplays);
    const dispose=window.desktop?.updates.onStatus(setUpdateStatus);
    return()=>{dispose?.();displayDispose?.();microphoneStream.current?.getTracks().forEach(track=>track.stop())};
  },[]);
  async function testSpeakers(){const context=new AudioContext(),oscillator=context.createOscillator(),gain=context.createGain(),destination=context.createMediaStreamDestination(),audio=new Audio(),sinkAudio=audio as HTMLAudioElement&{setSinkId?:(id:string)=>Promise<void>};gain.gain.value=Math.max(0,Math.min(1,outputVolume/100));oscillator.frequency.value=523.25;oscillator.connect(gain).connect(destination);audio.srcObject=destination.stream;if(audioOutputDevice!=='default'&&sinkAudio.setSinkId)await sinkAudio.setSinkId(audioOutputDevice);await audio.play();oscillator.start();oscillator.stop(context.currentTime+0.65);setTimeout(()=>{audio.pause();void context.close()},900)}
  async function toggleMicrophone(){if(microphoneStream.current){microphoneStream.current.getTracks().forEach(track=>track.stop());microphoneStream.current=null;setMicTesting(false);setMicLevel(0);return}const stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:audioInputDevice==='default'?undefined:{exact:audioInputDevice},noiseSuppression,echoCancellation,autoGainControl:false}});microphoneStream.current=stream;setAudioDevices(await navigator.mediaDevices.enumerateDevices());setMicTesting(true);const context=new AudioContext(),source=context.createMediaStreamSource(stream),analyser=context.createAnalyser(),values=new Uint8Array(analyser.frequencyBinCount);source.connect(analyser);const tick=()=>{if(microphoneStream.current!==stream){void context.close();return}analyser.getByteTimeDomainData(values);let sum=0;for(const value of values){const normalized=(value-128)/128;sum+=normalized*normalized}setMicLevel(Math.min(100,Math.round(Math.sqrt(sum/values.length)*inputGain)));requestAnimationFrame(tick)};tick()}
  const themeOptions:{value:ThemeMode;label:TranslationKey}[]=[{value:'system',label:'themeSystem'},{value:'light',label:'themeLight'},{value:'dark',label:'themeDark'}];
  const updateText=updateStatus.state==='checking'?t('updateChecking')
    :updateStatus.state==='available'?t('updateAvailable',{version:updateStatus.version??''})
    :updateStatus.state==='not-available'?t('updateCurrent')
    :updateStatus.state==='downloading'?t('updateDownloading',{percent:updateStatus.percent??0})
    :updateStatus.state==='rollback-downloading'?`${L.rollbackDownloading}: ${updateStatus.percent??0} %`
    :updateStatus.state==='downloaded'?t('updateDownloaded',{version:updateStatus.version??''})
    :updateStatus.state==='error'?t('updateError',{detail:updateStatus.message??t('authUnknown')})
    :updateStatus.state==='development'?t('updateDevelopment'):'';
  const notes:[[TranslationKey,TranslationKey],[TranslationKey,TranslationKey],[TranslationKey,TranslationKey],[TranslationKey,TranslationKey],[TranslationKey,TranslationKey]]=[['releaseNoteLanguagesTitle','releaseNoteLanguagesBody'],['releaseNoteLoginTitle','releaseNoteLoginBody'],['releaseNoteSecurityTitle','releaseNoteSecurityBody'],['releaseNoteHelpTitle','releaseNoteHelpBody'],['releaseNoteUpdatesTitle','releaseNoteUpdatesBody']];
  return <div className="modal-backdrop"><div className="modal"><header><h2>{t('settings')}</h2><button onClick={close} title={t('cancel')}><X/></button></header><div className="modal-body"><nav>{settingTabs.map(key=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{t(key)}</button>)}</nav>
    {tab==='general'?<section><h3>{t('general')}</h3><p>{t('generalHelp')}</p><div className="settings-group"><h4>{t('language')}</h4><label>{t('language')}<select value={language} onChange={e=>setLanguage(e.target.value as Language)}>{languageOptions.map(option=><option value={option.value} key={option.value}>{option.flag} {t(option.label)}</option>)}</select></label></div><div className="settings-group"><h4>{t('appearance')}</h4><label>{t('theme')}<select value={theme} onChange={e=>setTheme(e.target.value as ThemeMode)}>{themeOptions.map(option=><option value={option.value} key={option.value}>{t(option.label)}</option>)}</select></label><label className="setting-check"><input type="checkbox" checked={blackWhite} onChange={e=>setBlackWhite(e.target.checked)}/><span><b>{t('blackWhite')}</b><small>{t('blackWhiteHelp')}</small></span></label></div></section>
    :tab==='accessibility'?<section><h3>{t('accessibility')}</h3><p>{t('accessibilityHelp')}</p><label className="setting-check"><input type="checkbox" checked={reduceMotion} onChange={e=>setReduceMotion(e.target.checked)}/><span><b>{t('reduceMotion')}</b><small>{t('reduceMotionHelp')}</small></span></label><label className="setting-check"><input type="checkbox" checked={compactMode} onChange={e=>setCompactMode(e.target.checked)}/><span><b>{t('compactMode')}</b><small>{t('compactModeHelp')}</small></span></label><label className="setting-check"><input type="checkbox" checked={highContrast} onChange={e=>prefs.setHighContrast(e.target.checked)}/><span><b>{L.highContrast}</b><small>{L.highContrastHelp}</small></span></label><label className="setting-check"><input type="checkbox" checked={largeText} onChange={e=>prefs.setLargeText(e.target.checked)}/><span><b>{L.largeText}</b><small>{L.largeTextHelp}</small></span></label><label className="setting-check"><input type="checkbox" checked={strongFocus} onChange={e=>prefs.setStrongFocus(e.target.checked)}/><span><b>{L.strongFocus}</b><small>{L.strongFocusHelp}</small></span></label><label className="setting-check"><input type="checkbox" checked={dyslexiaFriendly} onChange={e=>prefs.setDyslexiaFriendly(e.target.checked)}/><span><b>{L.dyslexia}</b><small>{L.dyslexiaHelp}</small></span></label><label className="setting-check"><input type="checkbox" checked={showLoginBackgrounds} onChange={e=>setShowLoginBackgrounds(e.target.checked)}/><span><b>{t('showLoginBackgrounds')}</b><small>{t('showLoginBackgroundsHelp')}</small></span></label></section>
    :tab==='updates'?<section><h3>{t('updatesTitle')}</h3><p>{t('currentVersion')}: <b>{currentVersion}</b></p>{versionMetadata&&<div className="version-details"><h4>{L.versionDetails}</h4><dl><dt>{L.installedAt}</dt><dd>{new Date(versionMetadata.installedAt).toLocaleString(locale)}</dd><dt>{L.modifiedAt}</dt><dd>{new Date(versionMetadata.modifiedAt).toLocaleString(locale)}</dd><dt>{L.fileSize}</dt><dd>{new Intl.NumberFormat(locale,{style:'unit',unit:'megabyte',maximumFractionDigits:1}).format(versionMetadata.fileSize/1024/1024)}</dd><dt>{L.executable}</dt><dd>{versionMetadata.executable}</dd></dl></div>}{updateText&&<div className={`update-state ${updateStatus.state}`}>{updateText}</div>}{(updateStatus.state==='downloading'||updateStatus.state==='rollback-downloading')&&<div className="update-progress" role="progressbar" aria-valuenow={updateStatus.percent??0} aria-valuemin={0} aria-valuemax={100}><i style={{width:`${updateStatus.percent??0}%`}}/></div>}<div className="update-actions"><button className="primary" disabled={updateStatus.state==='checking'||updateStatus.state==='downloading'||updateStatus.state==='rollback-downloading'} onClick={()=>void window.desktop?.updates.check().then(setUpdateStatus)}>{t('checkUpdates')}</button>{updateStatus.state==='available'&&<button className="primary" onClick={()=>void window.desktop?.updates.download()}>{t('updateDownload')}</button>}{updateStatus.state==='downloaded'&&<button className="primary" onClick={()=>void window.desktop?.updates.install()}>{t('updateInstall')}</button>}</div><div className="rollback-box"><h4>{L.previousVersion}</h4>{previousVersion?<><p><b>{previousVersion.version}</b> · {new Date(previousVersion.publishedAt).toLocaleDateString(locale)} · {new Intl.NumberFormat(locale,{style:'unit',unit:'megabyte',maximumFractionDigits:1}).format(previousVersion.size/1024/1024)}</p><button disabled={updateStatus.state==='rollback-downloading'} onClick={()=>{if(confirm(L.rollbackConfirm))void window.desktop?.updates.rollback()}}>{L.rollback}</button></>:previousVersion===null?<p>{L.noPrevious}</p>:<p>…</p>}</div><h4>{t('releaseNotes')} {currentVersion}</h4><div className="release-accordion">{notes.map(([title,body])=><ExpandableItem key={title} title={t(title)} body={t(body)}/>)}<ExpandableItem title={t('audio')} body={L.audioHelp}/><ExpandableItem title={t('accessibility')} body={`${L.highContrastHelp} ${L.largeTextHelp} ${L.strongFocusHelp} ${L.dyslexiaHelp}`}/><ExpandableItem title="ON AIR" body={t('helpGettingStartedBody')}/><ExpandableItem title={t('slides')} body={t('helpShortcutsBody')}/></div>{updateStatus.releaseNotes&&<div className="remote-release-notes"><h4>{t('onlineReleaseNotes')}</h4><p>{plainReleaseNotes(updateStatus.releaseNotes)}</p></div>}</section>
    :tab==='audio'?<section><h3>{t('audio')}</h3><p>{L.audioHelp}</p><div className="audio-settings"><label>{L.speakers}<select value={audioOutputDevice} onChange={e=>prefs.setAudioOutputDevice(e.target.value)}><option value="default">{L.systemDefault}</option>{audioDevices.filter(device=>device.kind==='audiooutput'&&device.deviceId!=='default').map((device,index)=><option key={device.deviceId} value={device.deviceId}>{device.label||`${L.speakers} ${index+1}`}</option>)}</select></label><label>{L.microphone}<select value={audioInputDevice} onChange={e=>prefs.setAudioInputDevice(e.target.value)}><option value="default">{L.systemDefault}</option>{audioDevices.filter(device=>device.kind==='audioinput'&&device.deviceId!=='default').map((device,index)=><option key={device.deviceId} value={device.deviceId}>{device.label||`${L.microphone} ${index+1}`}</option>)}</select></label><label>{L.volume}<input type="range" min="0" max="100" value={outputVolume} onChange={e=>prefs.setOutputVolume(Number(e.target.value))}/><output>{outputVolume}%</output></label><label>{L.inputGain}<input type="range" min="0" max="200" value={inputGain} onChange={e=>prefs.setInputGain(Number(e.target.value))}/><output>{inputGain}%</output></label><label className="setting-check"><input type="checkbox" checked={noiseSuppression} onChange={e=>prefs.setNoiseSuppression(e.target.checked)}/><span><b>{L.noiseSuppression}</b></span></label><label className="setting-check"><input type="checkbox" checked={echoCancellation} onChange={e=>prefs.setEchoCancellation(e.target.checked)}/><span><b>{L.echoCancellation}</b></span></label><div className="audio-test"><button onClick={()=>void testSpeakers()}>{L.testSpeaker}</button><button className={micTesting?'danger-button':''} onClick={()=>void toggleMicrophone()}>{micTesting?L.stopTest:L.testMicrophone}</button></div><label>{L.micLevel}<div className="mic-meter"><i style={{width:`${micLevel}%`}}/></div></label></div></section>
    :tab==='display'?<section><h3>{t('displayTitle')}</h3><p>{t('displayHelp')}</p><div className="display-heading"><h4>{t('displayTitle')}</h4><button title={t('displayTitle')} disabled={!window.desktop} onClick={()=>void window.desktop?.identifyDisplays(displayRoles)}><Icon name="monitor"/> {t('displayNumber',{number:'1·2·3'})}</button></div><div className="display-list">{displays.map((display,index)=>{const current=(display.primary?'operator':displayRoles[String(display.id)]??'unused') as DisplayRole;return <article className="display-card" key={display.id}><b>{index+1}</b><div><strong>{display.label||t('displayNumber',{number:index+1})}</strong><span>{display.bounds.width} × {display.bounds.height} · {display.scaleFactor}× · X {display.bounds.x} / Y {display.bounds.y} · {display.rotation}°</span>{display.primary&&<small>{t('controlSurface')}</small>}</div><label>{t('display')}<select disabled={!canConfigure||display.primary} value={current} onChange={event=>setDisplayRole(display.id,event.target.value as DisplayRole)}><option value="unused">{t('unassigned')}</option><option value="operator">{t('controlSurface')}</option><option value="main">MAIN</option><option value="stage">STAGE</option><option value="notes">NOTES</option><option value="livestream">LIVESTREAM</option><option value="lobby">LOBBY</option></select></label></article>})}</div>{!canConfigure&&<div className="notice">{t('noPermission')}</div>}{!window.desktop&&<div className="notice">{t('displayDesktopOnly')}</div>}</section>
    :<section><h3>{t(tab)}</h3><p>{t('sectionUnavailable')}</p></section>}
  </div></div></div>;
}

function roleLabel(t:Translator,role:string){const labels:Record<string,TranslationKey>={viewer:'roleViewer',presenter:'rolePresenter',editor:'roleEditor',admin:'roleAdmin'};return labels[role]?t(labels[role]):role.toUpperCase()}

function HelpModal({close}:{close:()=>void}){
  const {t,language}=useI18n();
  const [version,setVersion]=useState('…');
  useEffect(()=>{void window.desktop?.updates.currentVersion().then(setVersion)},[]);
  const topics:[[TranslationKey,TranslationKey],[TranslationKey,TranslationKey],[TranslationKey,TranslationKey],[TranslationKey,TranslationKey],[TranslationKey,TranslationKey]]=[['helpGettingStarted','helpGettingStartedBody'],['helpShortcuts','helpShortcutsBody'],['helpUpdates','helpUpdatesBody'],['helpSecurity','helpSecurityBody'],['helpImages','helpImagesBody']];
  const L=extraLabels[language];
  return <div className="modal-backdrop"><div className="help-dialog"><header><div><h2>{t('helpTitle')}</h2><p>{t('helpIntro')}</p></div><button onClick={close} title={t('close')}><X/></button></header><div className="help-topics">{topics.map(([title,body])=><ExpandableItem key={title} title={t(title)} body={t(body)}/>)}<ExpandableItem title={t('audio')} body={L.audioHelp}/><ExpandableItem title={t('accessibility')} body={`${L.highContrastHelp} ${L.largeTextHelp} ${L.strongFocusHelp}`}/><ExpandableItem title={L.previousVersion} body={L.rollbackConfirm}/><ExpandableItem title="ON AIR" body={t('helpGettingStartedBody')}/></div><footer><span>GottesdienstRegie {version}</span><button className="primary" onClick={close}>{t('close')}</button></footer></div></div>;
}

function LogoutDialog({cancel,confirm}:{cancel:()=>void;confirm:()=>void}){const {t}=useI18n();return <div className="modal-backdrop"><div className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="logout-title"><div className="confirm-icon"><Icon name="logout"/></div><h2 id="logout-title">{t('logoutConfirmTitle')}</h2><p>{t('logoutConfirmText')}</p><div><button onClick={cancel}>{t('staySignedIn')}</button><button className="danger-button" onClick={confirm}>{t('logoutNow')}</button></div></div></div>}

function AppShell({session,onLogout}:{session:AuthSession;onLogout:()=>void}){
  const {t,locale}=useI18n();
  const state=usePresentation();const [settingsOpen,setSettingsOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false),[logoutConfirm,setLogoutConfirm]=useState(false),[displays,setDisplays]=useState<DesktopDisplay[]>([]),[outputState,setOutputState]=useState<Record<string,string>>({});
  const user=session.user,access=user.appAccess.gottesdienstRegie,can=(permission:string)=>session.permissions.includes(permission),canEdit=can('presentationEdit'),canConfigure=can('outputSettings')||can('appSettings');
  const selected=state.items.find(item=>item.id===state.selectedItemId),slideCount=selected?.slides.length??0,slideIndex=Math.max(0,selected?.slides.findIndex(slide=>slide.id===state.selectedSlideId)??0)+1;
  useEffect(()=>{if(state.saveState!=='dirty'||!window.desktop)return;const timer=setTimeout(()=>{state.markSaving();void window.desktop!.presentation.save(presentationDocument(usePresentation.getState())).then(()=>usePresentation.getState().markSaved()).catch(()=>usePresentation.getState().markSaveError())},700);return()=>clearTimeout(timer)},[state.updatedAt,state.saveState]);
  useEffect(()=>{void window.desktop?.displays().then(setDisplays);const disposeDisplays=window.desktop?.onDisplaysChanged(setDisplays),disposeOutputs=window.desktop?.onOutputStatus(status=>setOutputState(current=>({...current,[status.role]:status.state})));return()=>{disposeDisplays?.();disposeOutputs?.()}},[]);
  useEffect(()=>{if(!state.onAir||!state.liveSlideId)return;const liveSlide=state.items.flatMap(item=>item.slides).find(slide=>slide.id===state.liveSlideId);if(liveSlide)void liveEngine.show(liveSlide)},[state.liveSlideId,state.onAir]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null,isInput=target?.matches('input,textarea,select,[contenteditable="true"]');if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?state.redo():state.undo();return}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();state.markSaving();void window.desktop?.presentation.save(presentationDocument(usePresentation.getState())).then(()=>usePresentation.getState().markSaved());return}if(isInput||!state.onAir)return;if(event.key==='ArrowRight'||event.key==='PageDown'){event.preventDefault();state.nextLive()}if(event.key==='ArrowLeft'||event.key==='PageUp'){event.preventDefault();state.previousLive()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[state.onAir]);
  async function air(){if(!can('presentationLive')||!window.desktop)return;if(state.onAir){await liveEngine.stop();state.setOnAir(false);setOutputState({});return}const itemId=state.previewItemId||state.selectedItemId,slideId=state.previewSlideId||state.selectedSlideId,slide=state.items.find(item=>item.id===itemId)?.slides.find(entry=>entry.id===slideId);if(!slide)return;const enabledSlides=state.items.filter(item=>item.enabled&&!item.disabled).flatMap(item=>item.slides.filter(entry=>entry.enabled));const preflight=await liveEngine.preflight(state.displayRoles,{hasPresentation:state.items.length>0,activeSlideCount:enabledSlides.length,media:enabledSlides.flatMap(entry=>entry.elements.filter(element=>element.visible&&(element.type==='image'||element.type==='video')).map(element=>String(element.properties.src??element.properties.url??''))).filter(Boolean)});if(!preflight.ok){alert(preflight.errors.join('\n'));return}await liveEngine.start(state.displayRoles,slide);state.goLive(itemId,slideId);state.setOnAir(true)}
  async function leave(){if(state.onAir){await window.desktop?.goOffAir();state.setOnAir(false)}await logout();onLogout()}
  const menus:{key:TranslationKey;action?:()=>void}[]=[{key:'file'},{key:'media'},{key:'presentation'},{key:'view'},{key:'tools'},{key:'settings',action:()=>setSettingsOpen(true)},{key:'help',action:()=>setHelpOpen(true)}];
  return <div className="app"><div className="menubar">{menus.map(menu=><button key={menu.key} disabled={!menu.action} title={menu.action?t(menu.key):t('notAvailableTitle')} onClick={menu.action}>{t(menu.key)}</button>)}<span/><button title={`GottesdienstRegie: ${roleLabel(t,access.role)} · ${t('logout')}`} onClick={()=>setLogoutConfirm(true)}><LogOut/> {user.firstname??user.email}</button></div>
    <div className="toolbar"><div><b>{state.title}</b><span> · {new Date().toLocaleDateString(locale)}</span></div><div className="mode"><button className={state.mode==='edit'?'active':''} onClick={()=>state.setMode('edit')}>{t('edit')}</button><button className={state.mode==='preview'?'active':''} onClick={()=>state.setMode('preview')}>{t('preview')}</button></div><button className={`onair ${state.onAir?'live':''}`} disabled={!can('presentationLive')||!state.mainDisplayId||!window.desktop} title={!can('presentationLive')?t('noLivePermission'):!state.mainDisplayId?t('assignMain'):''} onClick={()=>void air()}><span/> {state.onAir?'OFF AIR':'ON AIR'}</button></div>
    <div className="main"><OrderOfService canEdit={canEdit}/><Workspace canEdit={canEdit}/><Inspector canEdit={canEdit}/></div>{state.mode==='edit'&&<Filmstrip/>}
    <div className="status"><span>{state.saveState==='error'?t('authUnknown'):t('ready')}</span><span>{t('local')} {state.saveState==='saving'?'…':state.saveState==='error'?'!':'✓'}</span><span>{t('syncOffline')}</span><span>{t('main')} {state.mainDisplayId&&!displays.some(display=>display.id===state.mainDisplayId)?'FEHLT':state.onAir?(outputState.main==='missing'?'FEHLT':'ON AIR'):state.mainDisplayId?t('ready'):'—'}</span><span>STAGE {Object.entries(state.displayRoles).some(([,role])=>role==='stage')?(outputState.stage==='missing'?'FEHLT':t('ready')):'—'}</span><i/><span>{roleLabel(t,access.role)}</span><span>{t('item')} {Math.max(1,state.items.findIndex(item=>item.id===state.selectedItemId)+1)}/{state.items.length}</span><span>{t('slide')} {slideIndex}/{slideCount}</span><Clock locale={locale}/></div>
    {settingsOpen&&<SettingsModal canConfigure={canConfigure} close={()=>setSettingsOpen(false)}/>} {helpOpen&&<HelpModal close={()=>setHelpOpen(false)}/>} {logoutConfirm&&<LogoutDialog cancel={()=>setLogoutConfirm(false)} confirm={()=>void leave()}/>}</div>;
}

function Clock({locale}:{locale:string}){const [now,setNow]=useState(new Date());useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(timer)},[]);return <span>{now.toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'})}</span>}
function Output(){const [slide,setSlide]=useState<Slide|null>(null);useEffect(()=>window.desktop?.onLiveSlide(payload=>setSlide(payload as Slide)),[]);return <div className="output">{slide&&<SlideRenderer slide={slide} mode="live"/>}</div>}

export function App(){
  const [session,setSession]=useState<AuthSession|null|undefined>(undefined);
  const language=usePreferences(state=>state.language),theme=usePreferences(state=>state.theme),blackWhite=usePreferences(state=>state.blackWhite),reduceMotion=usePreferences(state=>state.reduceMotion),compactMode=usePreferences(state=>state.compactMode),highContrast=usePreferences(state=>state.highContrast),largeText=usePreferences(state=>state.largeText),strongFocus=usePreferences(state=>state.strongFocus),dyslexiaFriendly=usePreferences(state=>state.dyslexiaFriendly);
  const {t}=useI18n();
  useEffect(()=>{document.documentElement.lang=language==='gsw'?'de-CH':language;document.documentElement.dir=language==='ar'?'rtl':'ltr';document.documentElement.dataset.theme=theme;document.documentElement.dataset.bw=String(blackWhite);document.documentElement.dataset.reduceMotion=String(reduceMotion);document.documentElement.dataset.compact=String(compactMode);document.documentElement.dataset.contrast=String(highContrast);document.documentElement.dataset.largeText=String(largeText);document.documentElement.dataset.strongFocus=String(strongFocus);document.documentElement.dataset.dyslexia=String(dyslexiaFriendly)},[language,theme,blackWhite,reduceMotion,compactMode,highContrast,largeText,strongFocus,dyslexiaFriendly]);
  useEffect(()=>{void restore().then(setSession)},[]);
  const signedIn=!!session;
  useEffect(()=>{if(!signedIn)return;let active=true;const check=async()=>{const refreshed=await restore();if(!active)return;if(!refreshed){setSession(null);return}setSession(current=>{if(!current)return refreshed;const currentAccess=current.user.appAccess.gottesdienstRegie,nextAccess=refreshed.user.appAccess.gottesdienstRegie;const changed=current.expiresAt!==refreshed.expiresAt||current.user.uid!==refreshed.user.uid||currentAccess.enabled!==nextAccess.enabled||currentAccess.role!==nextAccess.role||JSON.stringify(current.permissions)!==JSON.stringify(refreshed.permissions);return changed?refreshed:current})};const timer=setInterval(()=>void check(),120_000);return()=>{active=false;clearInterval(timer)}},[signedIn]);
  const output=useMemo(()=>location.hash==='#output',[]);
  if(output)return <Output/>;
  if(session===undefined)return <div className="boot">{t('accountLoading')}</div>;
  return session?<AppShell session={session} onLogout={()=>setSession(null)}/>:<Login authenticated={setSession}/>;
}
