import {useState} from 'react';
import type {AudioContinueUntil,BackgroundAudioConfig,BackgroundAudioTrack} from './store';

const Icon=({name}:{name:string})=><span className="material-symbols-outlined" aria-hidden="true">{name}</span>;
export const defaultBackgroundAudio=(tracks:BackgroundAudioTrack[]=[]):BackgroundAudioConfig=>({tracks,shuffle:false,repeat:true,continueUntil:'sectionEnd',volume:70,fadeInSeconds:1.5,fadeOutSeconds:2.5,crossfadeSeconds:2,muted:false,resumeSectionAfterItem:true,ducking:{enabled:true,level:25,attackMs:350,releaseMs:900},restartMode:'resume'});

export function BackgroundAudioPanel({title,targetType,targetId,value,onChange,onClose}:{title:string;targetType:'section'|'serviceItem';targetId:string;value?:BackgroundAudioConfig;onChange:(value?:BackgroundAudioConfig)=>void;onClose:()=>void}){
 const config=value??defaultBackgroundAudio(),[dragIndex,setDragIndex]=useState(-1);
 const update=(patch:Partial<BackgroundAudioConfig>)=>onChange({...config,...patch});
 const reorder=(to:number)=>{if(dragIndex<0||dragIndex===to)return;const tracks=[...config.tracks],[moved]=tracks.splice(dragIndex,1);tracks.splice(to,0,moved);update({tracks});setDragIndex(-1)};
 return <div className="background-audio-panel" role="dialog" aria-label="Background Audio" onClick={event=>event.stopPropagation()}>
  <header><div><Icon name="library_music"/><span><b>BACKGROUND AUDIO</b><small>{title}</small></span></div><button title="Schließen" onClick={onClose}><Icon name="close"/></button></header>
  <div className="background-audio-actions"><button className="primary" onClick={()=>void (window.desktop as any)?.mediaWindow?.open('select','audio',targetType,targetId)}><Icon name="add"/> AUDIO HINZUFÜGEN</button><button onClick={()=>void (window.desktop as any)?.mediaWindow?.open('manage','audio')}><Icon name="folder_open"/> AUDIO BROWSER</button></div>
  {config.tracks.length?<div className="background-audio-tracks">{config.tracks.map((track,index)=><div key={`${track.assetId}-${index}`} draggable onDragStart={()=>setDragIndex(index)} onDragOver={event=>event.preventDefault()} onDrop={()=>reorder(index)}><Icon name="drag_indicator"/><Icon name={track.status==='missing'?'warning':'music_note'}/><span><b>{track.name}</b><small>{track.artist||track.format||'Cloud-Audio'}</small></span><button title="Entfernen" onClick={()=>update({tracks:config.tracks.filter((_,current)=>current!==index)})}><Icon name="close"/></button></div>)}</div>:<div className="background-audio-empty"><Icon name="music_off"/><span>Noch keine Musik ausgewählt.</span></div>}
  <div className="background-audio-options"><label><input type="checkbox" checked={config.shuffle} onChange={event=>update({shuffle:event.target.checked})}/> Zufällige Reihenfolge</label><label><input type="checkbox" checked={config.repeat} onChange={event=>update({repeat:event.target.checked})}/> Playlist wiederholen</label><label><input type="checkbox" checked={config.muted} onChange={event=>update({muted:event.target.checked})}/> Stumm</label><label>Weiter bis<select value={config.continueUntil} onChange={event=>update({continueUntil:event.target.value as AudioContinueUntil})}><option value="itemEnd">Elementende</option><option value="sectionEnd">Abschnittsende</option><option value="playlistEnd">Playlistende</option><option value="stopCue">Stop-Cue</option><option value="nextSection">Nächster Abschnitt</option><option value="offAir">OFF AIR</option></select></label><label>Lautstärke <output>{config.volume}%</output><input type="range" min="0" max="100" value={config.volume} onChange={event=>update({volume:Number(event.target.value)})}/></label><div className="audio-number-row"><label>Einblenden<input type="number" min="0" max="30" step="0.5" value={config.fadeInSeconds} onChange={event=>update({fadeInSeconds:Number(event.target.value)})}/><small>Sek.</small></label><label>Ausblenden<input type="number" min="0" max="30" step="0.5" value={config.fadeOutSeconds} onChange={event=>update({fadeOutSeconds:Number(event.target.value)})}/><small>Sek.</small></label><label>Crossfade<input type="number" min="0" max="30" step="0.5" value={config.crossfadeSeconds} onChange={event=>update({crossfadeSeconds:Number(event.target.value)})}/><small>Sek.</small></label></div><label><input type="checkbox" checked={config.ducking.enabled} onChange={event=>update({ducking:{...config.ducking,enabled:event.target.checked}})}/> Bei Video-Audio automatisch absenken</label>{config.ducking.enabled&&<label>Absenkung <output>{config.ducking.level}%</output><input type="range" min="0" max="100" value={config.ducking.level} onChange={event=>update({ducking:{...config.ducking,level:Number(event.target.value)}})}/></label>}</div>
  <footer><button className="danger" disabled={!value} onClick={()=>onChange(undefined)}>ALLES ENTFERNEN</button><button className="primary" onClick={onClose}>FERTIG</button></footer>
 </div>
}
