import type { BackgroundAudioConfig, BackgroundAudioTrack, ServiceItem, ServiceSection } from './store';
import {defaultAudioRouting,routeDeviceId,type AudioRouting} from './audioRouting';
import {usePreferences} from './preferences';

export interface BackgroundAudioState{active:boolean;paused:boolean;muted:boolean;track?:BackgroundAudioTrack;currentTime:number;duration:number;volume:number;sourceKey:string;error?:string}

const emptyState:BackgroundAudioState={active:false,paused:false,muted:false,currentTime:0,duration:0,volume:70,sourceKey:''};

class BackgroundAudioEngine{
  getState(){return {...this.state}}
  private audio=new Audio();private config?:BackgroundAudioConfig;private index=-1;private sourceKey='';private sourceSectionId='';private state={...emptyState};private outputDevice='default';private routeVolume=.8;private routeMuted=false;private ducked=false;
  constructor(){this.audio.preload='auto';this.applyRouting(usePreferences.getState().audioRouting);usePreferences.subscribe(state=>this.applyRouting(state.audioRouting));this.audio.addEventListener('ended',()=>void this.advance());this.audio.addEventListener('play',()=>this.publish());this.audio.addEventListener('pause',()=>this.publish());this.audio.addEventListener('error',()=>{this.state.error='Der aktuelle Background-Audio-Titel konnte nicht wiedergegeben werden.';this.publish()});window.setInterval(()=>this.publish(),500)}
  snapshot(){return this.state}
  private publish(){this.state={...this.state,active:Boolean(this.audio.src)&&!this.audio.ended,paused:this.audio.paused,muted:this.audio.muted,track:this.config?.tracks[this.index],currentTime:Number.isFinite(this.audio.currentTime)?this.audio.currentTime:0,duration:Number.isFinite(this.audio.duration)?this.audio.duration:(this.config?.tracks[this.index]?.durationSeconds??0),volume:Math.round((this.config?.volume??70)*(this.ducked?(this.config?.ducking.level??25)/100:1)),sourceKey:this.sourceKey};window.dispatchEvent(new CustomEvent('gottesdienstregie:background-audio',{detail:this.state}))}
  private applyRouting(value?:AudioRouting){const routing={...defaultAudioRouting,...value,background:{...defaultAudioRouting.background,...value?.background}};this.outputDevice=routeDeviceId(routing,'background')||'default';this.routeVolume=routing.background.volume/100;this.routeMuted=routing.background.muted;this.audio.muted=Boolean(this.config?.muted)||this.routeMuted;this.audio.volume=this.targetVolume();const target=this.audio as HTMLAudioElement&{setSinkId?:(id:string)=>Promise<void>};if(target.setSinkId)void target.setSinkId(this.outputDevice==='default'?'':this.outputDevice).catch(()=>target.setSinkId?.('').catch(()=>{}))}
  async setOutputDevice(deviceId:string){this.outputDevice=deviceId;const target=this.audio as HTMLAudioElement&{setSinkId?:(id:string)=>Promise<void>};if(target.setSinkId)await target.setSinkId(deviceId==='default'?'':deviceId).catch(()=>target.setSinkId?.('').catch(()=>{}))}
  private targetVolume(){return Math.max(0,Math.min(1,(this.config?.volume??70)/100*this.routeVolume*(this.ducked?(this.config?.ducking.level??25)/100:1)))}
  private fade(to:number,seconds:number){const from=this.audio.volume,start=performance.now(),duration=Math.max(0,seconds)*1000;if(!duration){this.audio.volume=to;return Promise.resolve()}return new Promise<void>(resolve=>{const step=(now:number)=>{const progress=Math.min(1,(now-start)/duration);this.audio.volume=from+(to-from)*progress;if(progress<1)requestAnimationFrame(step);else resolve()};requestAnimationFrame(step)})}
  private async playIndex(index:number,crossfade=false){if(!this.config?.tracks.length)return;this.index=index;const track=this.config.tracks[index];if(!track?.url){this.state.error=`„${track?.name??'Audio'}“ ist nicht vorbereitet.`;this.publish();return}const fadeSeconds=crossfade?this.config.crossfadeSeconds:this.config.fadeInSeconds;if(crossfade&&this.audio.src)await this.fade(0,Math.min(this.config.crossfadeSeconds/2,1));this.audio.src=track.url;this.audio.muted=this.config.muted||this.routeMuted;this.audio.volume=fadeSeconds?0:this.targetVolume();const sink=this.audio as HTMLAudioElement&{setSinkId?:(id:string)=>Promise<void>};if(sink.setSinkId)await sink.setSinkId(this.outputDevice==='default'?'':this.outputDevice).catch(()=>sink.setSinkId?.('').catch(()=>{}));try{await this.audio.play();if(fadeSeconds)await this.fade(this.targetVolume(),fadeSeconds)}catch{this.state.error=`„${track.name}“ konnte nicht gestartet werden.`}this.publish()}
  async start(sourceKey:string,config:BackgroundAudioConfig,sectionId=''){if(!config.tracks.length)return;if(this.sourceKey===sourceKey&&this.audio.src)return;await this.stop(0);this.sourceKey=sourceKey;this.sourceSectionId=sectionId;this.config=config;this.index=config.shuffle&&config.tracks.length>1?Math.floor(Math.random()*config.tracks.length):0;await this.playIndex(this.index)}
  async sync(item:ServiceItem|undefined,section:ServiceSection|undefined){if(!item||!section){await this.stop();return}if(item.audioStopCue){await this.stop(item.audioStopCue.fadeOutSeconds);return}if(item.backgroundAudio?.tracks.length){if(item.backgroundAudio.autoPlay===false){if(this.sourceKey!==`item:${item.id}`)await this.stop();return}await this.start(`item:${item.id}`,item.backgroundAudio,section.id);return}if(this.sourceKey.startsWith('item:')){const previous=this.config,until=previous?.continueUntil,sectionEnded=Boolean(this.sourceSectionId&&this.sourceSectionId!==section.id);if(until==='itemEnd'||(until==='sectionEnd'&&sectionEnded))await this.stop(previous?.fadeOutSeconds);if(!this.sourceKey&&previous?.resumeSectionAfterItem&&section.backgroundAudio&&section.backgroundAudio.autoPlay!==false)await this.start(`section:${section.id}`,section.backgroundAudio,section.id);return}if(section.backgroundAudio?.tracks.length){if(section.backgroundAudio.autoPlay===false){if(this.sourceKey!==`section:${section.id}`)await this.stop();return}if(!section.backgroundAudio.startItemId||section.backgroundAudio.startItemId===item.id)await this.start(`section:${section.id}`,section.backgroundAudio,section.id);return}if(this.sourceKey.startsWith('section:')&&this.sourceKey!==`section:${section.id}`&&!['offAir','stopCue','nextSection'].includes(this.config?.continueUntil??''))await this.stop(this.config?.fadeOutSeconds)}
  private async advance(){if(!this.config?.tracks.length)return;let next=this.index+1;if(this.config.shuffle&&this.config.tracks.length>1){do next=Math.floor(Math.random()*this.config.tracks.length);while(next===this.index)}else if(next>=this.config.tracks.length){if(!this.config.repeat||this.config.continueUntil==='playlistEnd'){await this.stop(this.config.fadeOutSeconds);return}next=0}await this.playIndex(next,true)}
  async next(){if(this.config?.tracks.length)await this.advance()}
  pause(){this.audio.pause();this.publish()}
  async resume(){await this.audio.play().catch(()=>{});this.publish()}
  async stop(fadeSeconds=this.config?.fadeOutSeconds??0){if(this.audio.src&&fadeSeconds)await this.fade(0,fadeSeconds);this.audio.pause();this.audio.removeAttribute('src');this.audio.load();this.config=undefined;this.index=-1;this.sourceKey='';this.sourceSectionId='';this.ducked=false;this.state={...emptyState};this.publish()}
  setVolume(value:number){if(!this.config)return;this.config={...this.config,volume:Math.max(0,Math.min(100,value))};this.audio.volume=this.targetVolume();this.publish()}
  setMuted(value:boolean){if(!this.config)return;this.config={...this.config,muted:value};this.audio.muted=value||this.routeMuted;this.publish()}
  async setDucked(value:boolean){if(!this.config?.ducking.enabled||this.ducked===value)return;this.ducked=value;const seconds=(value?this.config.ducking.attackMs:this.config.ducking.releaseMs)/1000;await this.fade(this.targetVolume(),seconds);this.publish()}
}

export const backgroundAudioEngine=new BackgroundAudioEngine();
