import {useEffect,useMemo,useState} from 'react';
import {BIBLE_BOOKS,BIBLE_TRANSLATIONS,loadBiblePassage,type BiblePassage} from './bible/provider';

export function BibleTextDialog({close,onShow}:{close:()=>void;onShow:(value:{reference:string;text:string;translation:string})=>void}){
  const[translation,setTranslation]=useState('luther1545'),[book,setBook]=useState('John'),[bookQuery,setBookQuery]=useState(''),[chapter,setChapter]=useState(3),[fromVerse,setFromVerse]=useState(16),[toVerse,setToVerse]=useState(16),[passage,setPassage]=useState<BiblePassage|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const selectedBook=BIBLE_BOOKS.find(entry=>entry.id===book)??BIBLE_BOOKS[42],filtered=useMemo(()=>BIBLE_BOOKS.filter(entry=>`${entry.name} ${entry.id}`.toLowerCase().includes(bookQuery.trim().toLowerCase())),[bookQuery]);
  useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();close()}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[close]);
  useEffect(()=>{setPassage(null);setError('')},[translation,book,chapter,fromVerse,toVerse]);
  const preview=async()=>{setLoading(true);setError('');try{setPassage(await loadBiblePassage({translation,book,bookLabel:selectedBook.name,chapter:Math.max(1,chapter),fromVerse:Math.max(1,fromVerse),toVerse:Math.max(fromVerse,toVerse)}))}catch(reason){setPassage(null);setError(reason instanceof Error&&reason.message.startsWith('BIBLE_PROVIDER_')?'Der Bibeltextdienst ist momentan nicht erreichbar. Prüfe die Internetverbindung und versuche es erneut.':'Für diese Bibelstelle wurde kein Text gefunden. Prüfe Buch, Kapitel und Verse.')}finally{setLoading(false)}};
  return <div className="modal-backdrop bible-dialog-backdrop" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="bible-text-dialog bible-text-dialog-v54" role="dialog" aria-modal="true" aria-labelledby="bible-dialog-title"><header><div><small>MAIN-SCHNELLANZEIGE</small><h2 id="bible-dialog-title">Bibeltext einblenden</h2></div><button onClick={close} aria-label="Schließen">×</button></header><div className="bible-dialog-body"><section className="bible-reference-fields"><label>Übersetzung<select value={translation} onChange={event=>setTranslation(event.target.value)}>{BIBLE_TRANSLATIONS.map(entry=><option key={entry.id} value={entry.id}>{entry.name} · {entry.language}</option>)}</select></label><label>Buch suchen<input autoFocus spellCheck value={bookQuery} onChange={event=>setBookQuery(event.target.value)} placeholder="z. B. Johannes"/></label><label>Buch<select size={6} value={book} onChange={event=>{setBook(event.target.value);setBookQuery('')}}>{filtered.map(entry=><option key={entry.id} value={entry.id}>{entry.name}</option>)}</select></label><div className="bible-number-fields"><label>Kapitel<input type="number" min="1" max="150" value={chapter} onChange={event=>setChapter(Number(event.target.value))}/></label><label>Vers von<input type="number" min="1" max="176" value={fromVerse} onChange={event=>setFromVerse(Number(event.target.value))}/></label><label>Vers bis<input type="number" min={fromVerse} max="176" value={toVerse} onChange={event=>setToVerse(Number(event.target.value))}/></label></div><button className="primary bible-preview-button" disabled={loading} onClick={()=>void preview()}>{loading?'TEXT WIRD GELADEN …':'BIBELTEXT LADEN'}</button></section><section className="bible-passage-preview" aria-live="polite"><header><b>Vorschau</b>{passage&&<small>{passage.translation}</small>}</header>{loading?<div className="bible-loading"><i/><span>Bibelstelle wird geladen …</span></div>:error?<div className="bible-error"><span className="material-symbols-outlined">error</span><p>{error}</p><button onClick={()=>void preview()}>ERNEUT VERSUCHEN</button></div>:passage?<><h3>{passage.reference}</h3><div>{passage.verses.map(verse=><p key={verse.number}><sup>{verse.number}</sup>{verse.text}</p>)}</div></>:<div className="bible-empty"><span className="material-symbols-outlined">menu_book</span><p>Wähle eine Bibelstelle und lade den Text für die Vorschau.</p></div>}</section></div><footer><small>Der Text wird als temporäre Schnellanzeige über MAIN gelegt. Die laufende Folie bleibt erhalten.</small><div><button onClick={close}>ABBRECHEN</button><button className="primary" disabled={!passage||loading} onClick={()=>passage&&onShow({reference:passage.reference,text:passage.verses.map(verse=>`${verse.number} ${verse.text}`).join('\n'),translation:passage.translation})}>AUF MAIN ANZEIGEN</button></div></footer></section></div>
}
