import { usePreferences, type Language } from './preferences';

const de={
  loginSubtitle:'Mit deinem Konto anmelden',email:'E-Mail-Adresse',password:'Passwort',showPassword:'Passwort anzeigen',hidePassword:'Passwort ausblenden',remember:'Angemeldet bleiben',signIn:'ANMELDEN',signingIn:'Anmeldung läuft …',forgotPassword:'Passwort vergessen?',notAvailable:'Noch nicht verfügbar',firebaseChecking:'Firebase wird geprüft …',firebaseConnected:'Mit Firebase verbunden',firebaseDisconnected:'Keine Firebase-Verbindung',
  twoFactorTitle:'Zwei-Faktor-Anmeldung',twoFactorSubtitle:'Zusätzliche Sicherheitsprüfung',twoFactorTotp:'Öffne deine Authenticator- oder Passwort-App und gib den aktuellen 6-stelligen Code ein.',twoFactorSent:'Ein 6-stelliger Code wurde an {destination} gesendet.',securityChannel:'deinen Sicherheitskanal',recoveryIntro:'Gib einen deiner einmalig verwendbaren Wiederherstellungscodes ein.',recoveryCode:'Wiederherstellungscode',verificationCode:'Bestätigungscode',recoveryIncomplete:'Bitte einen vollständigen Wiederherstellungscode eingeben.',codeIncomplete:'Bitte den 6-stelligen Code eingeben.',useNormalCode:'Normalen 2FA-Code verwenden',useRecoveryCode:'Wiederherstellungscode verwenden',cancel:'ABBRECHEN',verifying:'PRÜFUNG LÄUFT …',confirm:'BESTÄTIGEN',codeSafety:'Der Code ist fünf Minuten gültig. Teile ihn niemals mit anderen Personen.',
  file:'Datei',media:'Medien',presentation:'Präsentation',view:'Ansicht',tools:'Werkzeuge',settings:'Einstellungen',help:'Hilfe',logout:'Abmelden',noPermission:'Keine Berechtigung',noEditPermission:'Keine Berechtigung zum Bearbeiten',notAvailableTitle:'Noch nicht verfügbar',
  orderOfService:'ABLAUF',addItem:'Element hinzufügen',song:'Song',bible:'Bibel',content:'Inhalt',newSong:'Neuer Song',newBible:'Bibelstelle',newContent:'Neuer Inhalt',newMedia:'Neues Medium',serviceSection:'GOTTESDIENST',editContent:'Inhalt bearbeiten',slidesOne:'Folie',slidesMany:'Folien',noSlides:'Noch keine Folien',properties:'EIGENSCHAFTEN',layers:'EBENEN',title:'Titel',text:'Text',background:'Hintergrund',slides:'FOLIEN',edit:'BEARBEITEN',preview:'VORSCHAU',singleView:'Einzelansicht',slideOverview:'Folienübersicht',previewSize:'Vorschaugröße',
  onAir:'AUF SENDUNG',offAir:'AUS SENDUNG',noLivePermission:'Keine Berechtigung für Auf Sendung',assignMain:'MAIN-Anzeige in Einstellungen zuweisen',ready:'BEREIT',local:'LOKAL',syncOffline:'SYNC OFFLINE',main:'MAIN',live:'LIVE',item:'ELEMENT',slide:'FOLIE',accountLoading:'Konto wird geladen …',roleViewer:'BETRACHTER',rolePresenter:'PRÄSENTATOR',roleEditor:'BEARBEITER',roleAdmin:'ADMIN',displayNumber:'Anzeige {number}',
  general:'Allgemein',display:'Anzeige',audio:'Audio',videoInput:'Videoeingang',quickScreens:'Schnellanzeigen',fonts:'Schriftarten',defaultMedia:'Standardmedien',defaultStage:'Standard-Bühne',remote:'Fernsteuerung',lightingMidi:'Licht/MIDI',language:'Sprache',appearance:'Darstellung',theme:'Farbschema',themeSystem:'Systemeinstellung',themeLight:'Hell',themeDark:'Dunkel',blackWhite:'Schwarz-Weiß-Modus',blackWhiteHelp:'Entfernt alle Farben aus der Bedienoberfläche und den Ausgabefenstern.',generalHelp:'Sprache und Darstellung werden sofort angewendet und auf diesem Gerät gespeichert.',displayTitle:'Anzeige',displayHelp:'MAIN-Ausgabe einem physischen Bildschirm zuweisen.',unassigned:'Nicht zugewiesen',controlSurface:'Bedienoberfläche',displayDesktopOnly:'Display-Erkennung ist nur in der Desktop-App verfügbar.',sectionUnavailable:'Dieser Einstellungsbereich ist noch nicht verfügbar.',
  updatesTitle:'Updates und Version',currentVersion:'Installierte Version',checkUpdates:'NACH UPDATES SUCHEN',updateChecking:'Suche nach Updates …',updateAvailable:'Version {version} ist verfügbar.',updateCurrent:'GottesdienstRegie ist aktuell.',updateDownloading:'Update wird heruntergeladen: {percent} %',updateDownloaded:'Version {version} ist bereit zur Installation.',updateDownload:'UPDATE HERUNTERLADEN',updateInstall:'INSTALLIEREN UND NEU STARTEN',updateError:'Updatefehler: {detail}',updateDevelopment:'Updateprüfung ist nur in der installierten App verfügbar.',releaseNotes:'Versionshinweise',releaseCurrentBody:'Neu in 0.2.0: automatische Updateprüfung über GitHub, sichere manuelle Installation, vollständig mehrsprachige Updateanzeige und integrierte Versionshinweise.',
  languageGerman:'Deutsch',languageEnglish:'Englisch',languageDutch:'Niederländisch',languageDanish:'Dänisch',languageNorwegian:'Norwegisch',
  authDesktop:'Die Anmeldung ist nur in der installierten Desktop-App möglich.',authStorage:'Windows konnte die Sitzung nicht sicher verschlüsseln.',authGasNetwork:'Der bestehende PGB-Login-Service ist nicht erreichbar.',authGasResponse:'Der PGB-Login-Service hat eine ungültige Antwort geliefert.',authEmailUnverified:'Bitte bestätige zuerst deine E-Mail-Adresse.',authLocked:'Das Konto ist vorübergehend gesperrt.',authInitialPassword:'Dieses Einmalpasswort muss zuerst auf der Gemeinde-Webseite geändert werden.',authTwoFactorCooldown:'Es wurde bereits ein Bestätigungscode versendet. Bitte warte kurz und starte die Anmeldung erneut.',authTwoFactorExpired:'Die Zwei-Faktor-Anmeldung ist abgelaufen. Bitte melde dich erneut an.',authTwoFactorInvalid:'Der Bestätigungscode ist nicht korrekt.',authTwoFactorError:'Die Zwei-Faktor-Prüfung konnte nicht gestartet werden.',authSessionFailed:'Der PGB-Login war korrekt, aber die Sitzung konnte nicht erstellt werden.',authAlgorithm:'Der Passwortalgorithmus dieses Kontos wird noch nicht unterstützt.',authFirebase:'Firebase ist nicht erreichbar oder die Datenbankabfrage wurde abgelehnt.',authAccessUnavailable:'Deine GottesdienstRegie-Freigabe konnte gerade nicht aus Firebase geladen werden. Bitte prüfe die Verbindung und versuche es erneut.',authDisabled:'Dieses Benutzerkonto ist deaktiviert oder wurde zentral abgemeldet.',authNoAccess:'Das Konto ist gültig, besitzt aber keinen freigeschalteten GottesdienstRegie-Zugang.',authInvalid:'E-Mail-Adresse oder Passwort ist nicht korrekt.',authTechnical:'Technischer Anmeldefehler: {detail}',authUnknown:'Unbekannter Fehler',serverCodeExpired:'Die Anmeldung ist abgelaufen. Bitte melde dich erneut an.',serverTooMany:'Zu viele Fehlversuche. Bitte starte die Anmeldung erneut.',serverRecoveryInvalid:'Der Wiederherstellungscode ist ungültig oder wurde bereits verwendet.',serverTotpInvalid:'Der Code der Authenticator-App ist nicht korrekt.'
} as const;

export type TranslationKey=keyof typeof de;
type Dictionary=Record<TranslationKey,string>;

const en:Dictionary={
  loginSubtitle:'Sign in with your account',email:'Email address',password:'Password',showPassword:'Show password',hidePassword:'Hide password',remember:'Stay signed in',signIn:'SIGN IN',signingIn:'SIGNING IN …',forgotPassword:'Forgot password?',notAvailable:'Not available yet',firebaseChecking:'Checking Firebase …',firebaseConnected:'Connected to Firebase',firebaseDisconnected:'No Firebase connection',
  twoFactorTitle:'Two-factor sign-in',twoFactorSubtitle:'Additional security check',twoFactorTotp:'Open your authenticator or password app and enter the current 6-digit code.',twoFactorSent:'A 6-digit code was sent to {destination}.',securityChannel:'your security channel',recoveryIntro:'Enter one of your single-use recovery codes.',recoveryCode:'Recovery code',verificationCode:'Verification code',recoveryIncomplete:'Enter a complete recovery code.',codeIncomplete:'Enter the 6-digit code.',useNormalCode:'Use a normal 2FA code',useRecoveryCode:'Use a recovery code',cancel:'CANCEL',verifying:'VERIFYING …',confirm:'CONFIRM',codeSafety:'The code is valid for five minutes. Never share it with anyone.',
  file:'File',media:'Media',presentation:'Presentation',view:'View',tools:'Tools',settings:'Settings',help:'Help',logout:'Sign out',noPermission:'No permission',noEditPermission:'No permission to edit',notAvailableTitle:'Not available yet',
  orderOfService:'ORDER OF SERVICE',addItem:'Add item',song:'Song',bible:'Bible',content:'Content',newSong:'New song',newBible:'Bible passage',newContent:'New content',newMedia:'New media',serviceSection:'SERVICE',editContent:'Edit content',slidesOne:'Slide',slidesMany:'Slides',noSlides:'No slides yet',properties:'PROPERTIES',layers:'LAYERS',title:'Title',text:'Text',background:'Background',slides:'SLIDES',edit:'EDIT',preview:'PREVIEW',singleView:'Single view',slideOverview:'Slide overview',previewSize:'Preview size',
  onAir:'ON AIR',offAir:'OFF AIR',noLivePermission:'No permission to go on air',assignMain:'Assign a MAIN display in Settings',ready:'READY',local:'LOCAL',syncOffline:'SYNC OFFLINE',main:'MAIN',live:'LIVE',item:'ITEM',slide:'SLIDE',accountLoading:'Loading account …',roleViewer:'VIEWER',rolePresenter:'PRESENTER',roleEditor:'EDITOR',roleAdmin:'ADMIN',displayNumber:'Display {number}',
  general:'General',display:'Display',audio:'Audio',videoInput:'Video input',quickScreens:'Quick Screens',fonts:'Fonts',defaultMedia:'Default media',defaultStage:'Default stage',remote:'Remote',lightingMidi:'Lighting/MIDI',language:'Language',appearance:'Appearance',theme:'Color scheme',themeSystem:'System setting',themeLight:'Light',themeDark:'Dark',blackWhite:'Black-and-white mode',blackWhiteHelp:'Removes all colors from the control interface and output windows.',generalHelp:'Language and appearance are applied immediately and saved on this device.',displayTitle:'Display',displayHelp:'Assign the MAIN output to a physical display.',unassigned:'Not assigned',controlSurface:'Control interface',displayDesktopOnly:'Display detection is only available in the desktop app.',sectionUnavailable:'This settings section is not available yet.',
  updatesTitle:'Updates and version',currentVersion:'Installed version',checkUpdates:'CHECK FOR UPDATES',updateChecking:'Checking for updates …',updateAvailable:'Version {version} is available.',updateCurrent:'GottesdienstRegie is up to date.',updateDownloading:'Downloading update: {percent}%',updateDownloaded:'Version {version} is ready to install.',updateDownload:'DOWNLOAD UPDATE',updateInstall:'INSTALL AND RESTART',updateError:'Update error: {detail}',updateDevelopment:'Update checking is only available in the installed app.',releaseNotes:'Release notes',releaseCurrentBody:'New in 0.2.0: automatic update checks through GitHub, secure manual installation, a fully multilingual update interface and integrated release notes.',
  languageGerman:'German',languageEnglish:'English',languageDutch:'Dutch',languageDanish:'Danish',languageNorwegian:'Norwegian',
  authDesktop:'Sign-in is only available in the installed desktop app.',authStorage:'Windows could not encrypt the session securely.',authGasNetwork:'The PGB sign-in service cannot be reached.',authGasResponse:'The PGB sign-in service returned an invalid response.',authEmailUnverified:'Please verify your email address first.',authLocked:'The account is temporarily locked.',authInitialPassword:'This one-time password must first be changed on the church website.',authTwoFactorCooldown:'A verification code has already been sent. Wait briefly and start sign-in again.',authTwoFactorExpired:'Two-factor sign-in has expired. Please sign in again.',authTwoFactorInvalid:'The verification code is incorrect.',authTwoFactorError:'The two-factor check could not be started.',authSessionFailed:'The PGB credentials were correct, but the session could not be created.',authAlgorithm:'This account’s password algorithm is not supported yet.',authFirebase:'Firebase cannot be reached or the database request was denied.',authAccessUnavailable:'Your GottesdienstRegie access could not be loaded from Firebase. Check the connection and try again.',authDisabled:'This user account is disabled or was signed out centrally.',authNoAccess:'The account is valid but has no enabled GottesdienstRegie access.',authInvalid:'The email address or password is incorrect.',authTechnical:'Technical sign-in error: {detail}',authUnknown:'Unknown error',serverCodeExpired:'Sign-in has expired. Please sign in again.',serverTooMany:'Too many failed attempts. Start sign-in again.',serverRecoveryInvalid:'The recovery code is invalid or has already been used.',serverTotpInvalid:'The authenticator app code is incorrect.'
};

const nl:Dictionary={
  loginSubtitle:'Meld je aan met je account',email:'E-mailadres',password:'Wachtwoord',showPassword:'Wachtwoord tonen',hidePassword:'Wachtwoord verbergen',remember:'Aangemeld blijven',signIn:'AANMELDEN',signingIn:'AANMELDEN …',forgotPassword:'Wachtwoord vergeten?',notAvailable:'Nog niet beschikbaar',firebaseChecking:'Firebase wordt gecontroleerd …',firebaseConnected:'Verbonden met Firebase',firebaseDisconnected:'Geen Firebase-verbinding',
  twoFactorTitle:'Tweestapsverificatie',twoFactorSubtitle:'Extra beveiligingscontrole',twoFactorTotp:'Open je authenticator- of wachtwoordapp en voer de huidige 6-cijferige code in.',twoFactorSent:'Er is een 6-cijferige code verzonden naar {destination}.',securityChannel:'je beveiligingskanaal',recoveryIntro:'Voer een van je eenmalige herstelcodes in.',recoveryCode:'Herstelcode',verificationCode:'Verificatiecode',recoveryIncomplete:'Voer een volledige herstelcode in.',codeIncomplete:'Voer de 6-cijferige code in.',useNormalCode:'Normale 2FA-code gebruiken',useRecoveryCode:'Herstelcode gebruiken',cancel:'ANNULEREN',verifying:'CONTROLEREN …',confirm:'BEVESTIGEN',codeSafety:'De code is vijf minuten geldig. Deel hem nooit met anderen.',
  file:'Bestand',media:'Media',presentation:'Presentatie',view:'Beeld',tools:'Gereedschappen',settings:'Instellingen',help:'Help',logout:'Afmelden',noPermission:'Geen toestemming',noEditPermission:'Geen toestemming om te bewerken',notAvailableTitle:'Nog niet beschikbaar',
  orderOfService:'DIENSTVOLGORDE',addItem:'Item toevoegen',song:'Lied',bible:'Bijbel',content:'Inhoud',newSong:'Nieuw lied',newBible:'Bijbelgedeelte',newContent:'Nieuwe inhoud',newMedia:'Nieuwe media',serviceSection:'DIENST',editContent:'Inhoud bewerken',slidesOne:'Dia',slidesMany:'Dia’s',noSlides:'Nog geen dia’s',properties:'EIGENSCHAPPEN',layers:'LAGEN',title:'Titel',text:'Tekst',background:'Achtergrond',slides:'DIA’S',edit:'BEWERKEN',preview:'VOORBEELD',singleView:'Enkele weergave',slideOverview:'Dia-overzicht',previewSize:'Voorbeeldgrootte',
  onAir:'IN UITZENDING',offAir:'UIT UITZENDING',noLivePermission:'Geen toestemming om uit te zenden',assignMain:'Wijs een MAIN-scherm toe in Instellingen',ready:'GEREED',local:'LOKAAL',syncOffline:'SYNC OFFLINE',main:'MAIN',live:'LIVE',item:'ITEM',slide:'DIA',accountLoading:'Account wordt geladen …',roleViewer:'KIJKER',rolePresenter:'PRESENTATOR',roleEditor:'BEWERKER',roleAdmin:'ADMIN',displayNumber:'Beeldscherm {number}',
  general:'Algemeen',display:'Beeldscherm',audio:'Audio',videoInput:'Video-ingang',quickScreens:'Snelle schermen',fonts:'Lettertypen',defaultMedia:'Standaardmedia',defaultStage:'Standaardpodium',remote:'Afstandsbediening',lightingMidi:'Licht/MIDI',language:'Taal',appearance:'Weergave',theme:'Kleurenschema',themeSystem:'Systeeminstelling',themeLight:'Licht',themeDark:'Donker',blackWhite:'Zwart-witmodus',blackWhiteHelp:'Verwijdert alle kleuren uit de bedieningsinterface en uitvoervensters.',generalHelp:'Taal en weergave worden direct toegepast en op dit apparaat opgeslagen.',displayTitle:'Beeldscherm',displayHelp:'Wijs de MAIN-uitvoer toe aan een fysiek beeldscherm.',unassigned:'Niet toegewezen',controlSurface:'Bedieningsinterface',displayDesktopOnly:'Schermdetectie is alleen beschikbaar in de desktop-app.',sectionUnavailable:'Dit instellingengedeelte is nog niet beschikbaar.',
  updatesTitle:'Updates en versie',currentVersion:'Geïnstalleerde versie',checkUpdates:'CONTROLEREN OP UPDATES',updateChecking:'Controleren op updates …',updateAvailable:'Versie {version} is beschikbaar.',updateCurrent:'GottesdienstRegie is bijgewerkt.',updateDownloading:'Update downloaden: {percent}%',updateDownloaded:'Versie {version} is klaar voor installatie.',updateDownload:'UPDATE DOWNLOADEN',updateInstall:'INSTALLEREN EN HERSTARTEN',updateError:'Updatefout: {detail}',updateDevelopment:'Controleren op updates is alleen beschikbaar in de geïnstalleerde app.',releaseNotes:'Versieopmerkingen',releaseCurrentBody:'Nieuw in 0.2.0: automatische updatecontrole via GitHub, veilige handmatige installatie, een volledig meertalige updateweergave en geïntegreerde versieopmerkingen.',
  languageGerman:'Duits',languageEnglish:'Engels',languageDutch:'Nederlands',languageDanish:'Deens',languageNorwegian:'Noors',
  authDesktop:'Aanmelden kan alleen in de geïnstalleerde desktop-app.',authStorage:'Windows kon de sessie niet veilig versleutelen.',authGasNetwork:'De PGB-aanmeldservice is niet bereikbaar.',authGasResponse:'De PGB-aanmeldservice gaf een ongeldig antwoord.',authEmailUnverified:'Bevestig eerst je e-mailadres.',authLocked:'Het account is tijdelijk geblokkeerd.',authInitialPassword:'Dit eenmalige wachtwoord moet eerst op de gemeentewebsite worden gewijzigd.',authTwoFactorCooldown:'Er is al een verificatiecode verzonden. Wacht even en start de aanmelding opnieuw.',authTwoFactorExpired:'De tweestapsverificatie is verlopen. Meld je opnieuw aan.',authTwoFactorInvalid:'De verificatiecode is onjuist.',authTwoFactorError:'De tweestapscontrole kon niet worden gestart.',authSessionFailed:'De PGB-aanmelding was correct, maar de sessie kon niet worden aangemaakt.',authAlgorithm:'Het wachtwoordalgoritme van dit account wordt nog niet ondersteund.',authFirebase:'Firebase is niet bereikbaar of het databaseverzoek is geweigerd.',authAccessUnavailable:'Je GottesdienstRegie-toegang kon niet uit Firebase worden geladen. Controleer de verbinding en probeer opnieuw.',authDisabled:'Dit gebruikersaccount is uitgeschakeld of centraal afgemeld.',authNoAccess:'Het account is geldig, maar heeft geen geactiveerde toegang tot GottesdienstRegie.',authInvalid:'Het e-mailadres of wachtwoord is onjuist.',authTechnical:'Technische aanmeldfout: {detail}',authUnknown:'Onbekende fout',serverCodeExpired:'De aanmelding is verlopen. Meld je opnieuw aan.',serverTooMany:'Te veel mislukte pogingen. Start de aanmelding opnieuw.',serverRecoveryInvalid:'De herstelcode is ongeldig of al gebruikt.',serverTotpInvalid:'De code van de authenticator-app is onjuist.'
};

const da:Dictionary={
  loginSubtitle:'Log ind med din konto',email:'E-mailadresse',password:'Adgangskode',showPassword:'Vis adgangskode',hidePassword:'Skjul adgangskode',remember:'Forbliv logget ind',signIn:'LOG IND',signingIn:'LOGGER IND …',forgotPassword:'Glemt adgangskode?',notAvailable:'Ikke tilgængelig endnu',firebaseChecking:'Kontrollerer Firebase …',firebaseConnected:'Forbundet til Firebase',firebaseDisconnected:'Ingen Firebase-forbindelse',
  twoFactorTitle:'Tofaktorgodkendelse',twoFactorSubtitle:'Ekstra sikkerhedskontrol',twoFactorTotp:'Åbn din godkendelses- eller adgangskodeapp, og indtast den aktuelle 6-cifrede kode.',twoFactorSent:'En 6-cifret kode blev sendt til {destination}.',securityChannel:'din sikkerhedskanal',recoveryIntro:'Indtast en af dine genoprettelseskoder til engangsbrug.',recoveryCode:'Genoprettelseskode',verificationCode:'Bekræftelseskode',recoveryIncomplete:'Indtast en fuldstændig genoprettelseskode.',codeIncomplete:'Indtast den 6-cifrede kode.',useNormalCode:'Brug en normal 2FA-kode',useRecoveryCode:'Brug en genoprettelseskode',cancel:'ANNULLER',verifying:'KONTROLLERER …',confirm:'BEKRÆFT',codeSafety:'Koden er gyldig i fem minutter. Del den aldrig med andre.',
  file:'Fil',media:'Medier',presentation:'Præsentation',view:'Vis',tools:'Værktøjer',settings:'Indstillinger',help:'Hjælp',logout:'Log ud',noPermission:'Ingen tilladelse',noEditPermission:'Ingen tilladelse til at redigere',notAvailableTitle:'Ikke tilgængelig endnu',
  orderOfService:'GUDSTJENESTEFORLØB',addItem:'Tilføj element',song:'Sang',bible:'Bibel',content:'Indhold',newSong:'Ny sang',newBible:'Bibeltekst',newContent:'Nyt indhold',newMedia:'Nyt medie',serviceSection:'GUDSTJENESTE',editContent:'Rediger indhold',slidesOne:'Slide',slidesMany:'Slides',noSlides:'Ingen slides endnu',properties:'EGENSKABER',layers:'LAG',title:'Titel',text:'Tekst',background:'Baggrund',slides:'SLIDES',edit:'REDIGER',preview:'FORHÅNDSVISNING',singleView:'Enkeltvisning',slideOverview:'Slideoversigt',previewSize:'Forhåndsvisningsstørrelse',
  onAir:'I LUFTEN',offAir:'FRA LUFTEN',noLivePermission:'Ingen tilladelse til at gå i luften',assignMain:'Tildel en MAIN-skærm i Indstillinger',ready:'KLAR',local:'LOKAL',syncOffline:'SYNC OFFLINE',main:'MAIN',live:'LIVE',item:'ELEMENT',slide:'SLIDE',accountLoading:'Indlæser konto …',roleViewer:'SEER',rolePresenter:'PRÆSENTATØR',roleEditor:'REDAKTØR',roleAdmin:'ADMIN',displayNumber:'Skærm {number}',
  general:'Generelt',display:'Skærm',audio:'Lyd',videoInput:'Videoindgang',quickScreens:'Hurtigskærme',fonts:'Skrifttyper',defaultMedia:'Standardmedier',defaultStage:'Standardscene',remote:'Fjernbetjening',lightingMidi:'Lys/MIDI',language:'Sprog',appearance:'Udseende',theme:'Farvetema',themeSystem:'Systemindstilling',themeLight:'Lys',themeDark:'Mørk',blackWhite:'Sort-hvid-tilstand',blackWhiteHelp:'Fjerner alle farver fra betjeningsfladen og outputvinduerne.',generalHelp:'Sprog og udseende anvendes med det samme og gemmes på denne enhed.',displayTitle:'Skærm',displayHelp:'Tildel MAIN-outputtet til en fysisk skærm.',unassigned:'Ikke tildelt',controlSurface:'Betjeningsflade',displayDesktopOnly:'Skærmregistrering er kun tilgængelig i desktopappen.',sectionUnavailable:'Dette indstillingsområde er ikke tilgængeligt endnu.',
  updatesTitle:'Opdateringer og version',currentVersion:'Installeret version',checkUpdates:'SØG EFTER OPDATERINGER',updateChecking:'Søger efter opdateringer …',updateAvailable:'Version {version} er tilgængelig.',updateCurrent:'GottesdienstRegie er opdateret.',updateDownloading:'Downloader opdatering: {percent} %',updateDownloaded:'Version {version} er klar til installation.',updateDownload:'DOWNLOAD OPDATERING',updateInstall:'INSTALLER OG GENSTART',updateError:'Opdateringsfejl: {detail}',updateDevelopment:'Opdateringssøgning er kun tilgængelig i den installerede app.',releaseNotes:'Versionsbemærkninger',releaseCurrentBody:'Nyt i 0.2.0: automatisk opdateringssøgning via GitHub, sikker manuel installation, en fuldt flersproget opdateringsvisning og integrerede versionsbemærkninger.',
  languageGerman:'Tysk',languageEnglish:'Engelsk',languageDutch:'Nederlandsk',languageDanish:'Dansk',languageNorwegian:'Norsk',
  authDesktop:'Login er kun muligt i den installerede desktopapp.',authStorage:'Windows kunne ikke kryptere sessionen sikkert.',authGasNetwork:'PGB-logintjenesten kan ikke nås.',authGasResponse:'PGB-logintjenesten returnerede et ugyldigt svar.',authEmailUnverified:'Bekræft først din e-mailadresse.',authLocked:'Kontoen er midlertidigt låst.',authInitialPassword:'Denne engangsadgangskode skal først ændres på kirkens hjemmeside.',authTwoFactorCooldown:'Der er allerede sendt en bekræftelseskode. Vent kort, og start login igen.',authTwoFactorExpired:'Tofaktorgodkendelsen er udløbet. Log ind igen.',authTwoFactorInvalid:'Bekræftelseskoden er forkert.',authTwoFactorError:'Tofaktorkontrollen kunne ikke startes.',authSessionFailed:'PGB-login var korrekt, men sessionen kunne ikke oprettes.',authAlgorithm:'Denne kontos adgangskodealgoritme understøttes ikke endnu.',authFirebase:'Firebase kan ikke nås, eller databaseanmodningen blev afvist.',authAccessUnavailable:'Din GottesdienstRegie-adgang kunne ikke indlæses fra Firebase. Kontroller forbindelsen, og prøv igen.',authDisabled:'Denne brugerkonto er deaktiveret eller logget ud centralt.',authNoAccess:'Kontoen er gyldig, men har ikke aktiveret adgang til GottesdienstRegie.',authInvalid:'E-mailadressen eller adgangskoden er forkert.',authTechnical:'Teknisk loginfejl: {detail}',authUnknown:'Ukendt fejl',serverCodeExpired:'Login er udløbet. Log ind igen.',serverTooMany:'For mange mislykkede forsøg. Start login igen.',serverRecoveryInvalid:'Genoprettelseskoden er ugyldig eller allerede brugt.',serverTotpInvalid:'Koden fra godkendelsesappen er forkert.'
};

const no:Dictionary={
  loginSubtitle:'Logg inn med kontoen din',email:'E-postadresse',password:'Passord',showPassword:'Vis passord',hidePassword:'Skjul passord',remember:'Forbli innlogget',signIn:'LOGG INN',signingIn:'LOGGER INN …',forgotPassword:'Glemt passord?',notAvailable:'Ikke tilgjengelig ennå',firebaseChecking:'Kontrollerer Firebase …',firebaseConnected:'Koblet til Firebase',firebaseDisconnected:'Ingen Firebase-tilkobling',
  twoFactorTitle:'Tofaktorinnlogging',twoFactorSubtitle:'Ekstra sikkerhetskontroll',twoFactorTotp:'Åpne autentiserings- eller passordappen og skriv inn den gjeldende 6-sifrede koden.',twoFactorSent:'En 6-sifret kode ble sendt til {destination}.',securityChannel:'sikkerhetskanalen din',recoveryIntro:'Skriv inn en av gjenopprettingskodene for engangsbruk.',recoveryCode:'Gjenopprettingskode',verificationCode:'Bekreftelseskode',recoveryIncomplete:'Skriv inn en fullstendig gjenopprettingskode.',codeIncomplete:'Skriv inn den 6-sifrede koden.',useNormalCode:'Bruk en vanlig 2FA-kode',useRecoveryCode:'Bruk en gjenopprettingskode',cancel:'AVBRYT',verifying:'KONTROLLERER …',confirm:'BEKREFT',codeSafety:'Koden er gyldig i fem minutter. Del den aldri med andre.',
  file:'Fil',media:'Medier',presentation:'Presentasjon',view:'Visning',tools:'Verktøy',settings:'Innstillinger',help:'Hjelp',logout:'Logg ut',noPermission:'Ingen tillatelse',noEditPermission:'Ingen tillatelse til å redigere',notAvailableTitle:'Ikke tilgjengelig ennå',
  orderOfService:'GUDSTJENESTEFORLØP',addItem:'Legg til element',song:'Sang',bible:'Bibel',content:'Innhold',newSong:'Ny sang',newBible:'Bibeltekst',newContent:'Nytt innhold',newMedia:'Nytt medium',serviceSection:'GUDSTJENESTE',editContent:'Rediger innhold',slidesOne:'Lysbilde',slidesMany:'Lysbilder',noSlides:'Ingen lysbilder ennå',properties:'EGENSKAPER',layers:'LAG',title:'Tittel',text:'Tekst',background:'Bakgrunn',slides:'LYSBILDER',edit:'REDIGER',preview:'FORHÅNDSVISNING',singleView:'Enkeltvisning',slideOverview:'Lysbildeoversikt',previewSize:'Forhåndsvisningsstørrelse',
  onAir:'PÅ LUFTEN',offAir:'AV LUFTEN',noLivePermission:'Ingen tillatelse til å gå på luften',assignMain:'Tilordne en MAIN-skjerm i Innstillinger',ready:'KLAR',local:'LOKAL',syncOffline:'SYNC FRAKOBLET',main:'MAIN',live:'DIREKTE',item:'ELEMENT',slide:'LYSBILDE',accountLoading:'Laster konto …',roleViewer:'SEER',rolePresenter:'PRESENTATØR',roleEditor:'REDAKTØR',roleAdmin:'ADMIN',displayNumber:'Skjerm {number}',
  general:'Generelt',display:'Skjerm',audio:'Lyd',videoInput:'Videoinngang',quickScreens:'Hurtigskjermer',fonts:'Skrifter',defaultMedia:'Standardmedier',defaultStage:'Standardscene',remote:'Fjernkontroll',lightingMidi:'Lys/MIDI',language:'Språk',appearance:'Utseende',theme:'Fargetema',themeSystem:'Systeminnstilling',themeLight:'Lys',themeDark:'Mørk',blackWhite:'Svart-hvitt-modus',blackWhiteHelp:'Fjerner alle farger fra kontrollgrensesnittet og utgangsvinduene.',generalHelp:'Språk og utseende brukes umiddelbart og lagres på denne enheten.',displayTitle:'Skjerm',displayHelp:'Tilordne MAIN-utgangen til en fysisk skjerm.',unassigned:'Ikke tilordnet',controlSurface:'Kontrollgrensesnitt',displayDesktopOnly:'Skjermgjenkjenning er bare tilgjengelig i skrivebordsappen.',sectionUnavailable:'Denne innstillingsdelen er ikke tilgjengelig ennå.',
  updatesTitle:'Oppdateringer og versjon',currentVersion:'Installert versjon',checkUpdates:'SE ETTER OPPDATERINGER',updateChecking:'Ser etter oppdateringer …',updateAvailable:'Versjon {version} er tilgjengelig.',updateCurrent:'GottesdienstRegie er oppdatert.',updateDownloading:'Laster ned oppdatering: {percent} %',updateDownloaded:'Versjon {version} er klar til installasjon.',updateDownload:'LAST NED OPPDATERING',updateInstall:'INSTALLER OG START PÅ NYTT',updateError:'Oppdateringsfeil: {detail}',updateDevelopment:'Oppdateringssøk er bare tilgjengelig i den installerte appen.',releaseNotes:'Versjonsmerknader',releaseCurrentBody:'Nytt i 0.2.0: automatisk oppdateringssøk via GitHub, sikker manuell installasjon, en fullstendig flerspråklig oppdateringsvisning og integrerte versjonsmerknader.',
  languageGerman:'Tysk',languageEnglish:'Engelsk',languageDutch:'Nederlandsk',languageDanish:'Dansk',languageNorwegian:'Norsk',
  authDesktop:'Innlogging er bare tilgjengelig i den installerte skrivebordsappen.',authStorage:'Windows kunne ikke kryptere økten sikkert.',authGasNetwork:'PGB-innloggingstjenesten kan ikke nås.',authGasResponse:'PGB-innloggingstjenesten returnerte et ugyldig svar.',authEmailUnverified:'Bekreft e-postadressen din først.',authLocked:'Kontoen er midlertidig låst.',authInitialPassword:'Dette engangspassordet må først endres på menighetens nettside.',authTwoFactorCooldown:'En bekreftelseskode er allerede sendt. Vent litt og start innloggingen på nytt.',authTwoFactorExpired:'Tofaktorinnloggingen er utløpt. Logg inn på nytt.',authTwoFactorInvalid:'Bekreftelseskoden er feil.',authTwoFactorError:'Tofaktorkontrollen kunne ikke startes.',authSessionFailed:'PGB-innloggingen var riktig, men økten kunne ikke opprettes.',authAlgorithm:'Passordalgoritmen for denne kontoen støttes ikke ennå.',authFirebase:'Firebase kan ikke nås, eller databaseforespørselen ble avvist.',authAccessUnavailable:'GottesdienstRegie-tilgangen din kunne ikke lastes fra Firebase. Kontroller tilkoblingen og prøv igjen.',authDisabled:'Denne brukerkontoen er deaktivert eller logget ut sentralt.',authNoAccess:'Kontoen er gyldig, men har ikke aktivert tilgang til GottesdienstRegie.',authInvalid:'E-postadressen eller passordet er feil.',authTechnical:'Teknisk innloggingsfeil: {detail}',authUnknown:'Ukjent feil',serverCodeExpired:'Innloggingen er utløpt. Logg inn på nytt.',serverTooMany:'For mange mislykkede forsøk. Start innloggingen på nytt.',serverRecoveryInvalid:'Gjenopprettingskoden er ugyldig eller allerede brukt.',serverTotpInvalid:'Koden fra autentiseringsappen er feil.'
};

const dictionaries:Record<Language,Dictionary>={de,en,nl,da,no};
export const locales:Record<Language,string>={de:'de-DE',en:'en-GB',nl:'nl-NL',da:'da-DK',no:'nb-NO'};
export type Translator=(key:TranslationKey,values?:Record<string,string|number>)=>string;

export function translate(language:Language,key:TranslationKey,values:Record<string,string|number>={}){
  return Object.entries(values).reduce((text,[name,value])=>text.replaceAll(`{${name}}`,String(value)),dictionaries[language][key]);
}

export function useI18n(){
  const language=usePreferences(state=>state.language);
  const t:Translator=(key,values)=>translate(language,key,values);
  return {language,locale:locales[language],t};
}
