export interface TranslationLanguage{code:string;name:string;nativeName:string;standard:boolean}
export const standardLanguageCodes=['de','en','fr','es','it','nl','pl','pt','uk','ru','tr','ar','da','sv','no'] as const;
const data:Array<[string,string,string]>=[
['de','Deutsch','Deutsch'],['en','Englisch','English'],['fr','Französisch','Français'],['es','Spanisch','Español'],['it','Italienisch','Italiano'],['nl','Niederländisch','Nederlands'],['pl','Polnisch','Polski'],['pt','Portugiesisch','Português'],['uk','Ukrainisch','Українська'],['ru','Russisch','Русский'],['tr','Türkisch','Türkçe'],['ar','Arabisch','العربية'],['da','Dänisch','Dansk'],['sv','Schwedisch','Svenska'],['no','Norwegisch','Norsk'],
['af','Afrikaans','Afrikaans'],['sq','Albanisch','Shqip'],['am','Amharisch','አማርኛ'],['hy','Armenisch','Հայերեն'],['az','Aserbaidschanisch','Azərbaycanca'],['eu','Baskisch','Euskara'],['bn','Bengalisch','বাংলা'],['bs','Bosnisch','Bosanski'],['bg','Bulgarisch','Български'],['ca','Katalanisch','Català'],['zh','Chinesisch','中文'],['hr','Kroatisch','Hrvatski'],['cs','Tschechisch','Čeština'],['et','Estnisch','Eesti'],['fi','Finnisch','Suomi'],['ka','Georgisch','ქართული'],['el','Griechisch','Ελληνικά'],['he','Hebräisch','עברית'],['hi','Hindi','हिन्दी'],['hu','Ungarisch','Magyar'],['id','Indonesisch','Bahasa Indonesia'],['ga','Irisch','Gaeilge'],['ja','Japanisch','日本語'],['ko','Koreanisch','한국어'],['lv','Lettisch','Latviešu'],['lt','Litauisch','Lietuvių'],['ms','Malaiisch','Bahasa Melayu'],['fa','Persisch','فارسی'],['ro','Rumänisch','Română'],['sr','Serbisch','Српски'],['sk','Slowakisch','Slovenčina'],['sl','Slowenisch','Slovenščina'],['sw','Suaheli','Kiswahili'],['th','Thailändisch','ไทย'],['vi','Vietnamesisch','Tiếng Việt'],['cy','Walisisch','Cymraeg'],['yi','Jiddisch','ייִדיש']];
const standard=new Set<string>(standardLanguageCodes);
export const translationLanguages:TranslationLanguage[]=data.map(([code,name,nativeName])=>({code,name,nativeName,standard:standard.has(code)}));
export function searchLanguages(query:string){const needle=query.trim().toLocaleLowerCase('de');return translationLanguages.filter(language=>!needle||`${language.code} ${language.name} ${language.nativeName}`.toLocaleLowerCase('de').includes(needle))}
export function languageByCode(code:string){return translationLanguages.find(language=>language.code===code)??translationLanguages[0]}
export function translationModelKey(source:string,target:string){return `${source.toLowerCase()}-${target.toLowerCase()}`}
