import {useEffect,useMemo,useRef,useState} from 'react';
import {usePreferences} from './preferences';
import {applyAudioRoute,defaultAudioRouting} from './audioRouting';
const Icon=({name}:{name:string})=><span className="material-symbols-outlined" aria-hidden="true">{name}</span>;
type Context='manage'|'select';type Purpose='item'|'background'|'audio';type TargetType='section'|'serviceItem';
const bytes=(value:number)=>value<1048576?`${Math.max(1,Math.round(value/1024))} KB`:`${(value/1048576).toLocaleString('de-DE',{maximumFractionDigits:1})} MB`;
const typeName=(kind:CloudMediaAsset['kind'])=>({image:'Bild',video:'Video',audio:'Audio',pdf:'PDF'})[kind];
export function MediaBrowser(){
 const prefs=usePreferences();
 const initial=useMemo(()=>{const q=new URLSearchParams(location.hash.split('?')[1]??''),purpose=(q.get('purpose')==='audio'?'audio':q.get('purpose')==='background'?'background':'item') as Purpose;return{context:(q.get('context')==='select'?'select':'manage') as Context,purpose,targetType:(q.get('targetType')==='serviceItem'?'serviceItem':'section') as TargetType,targetId:q.get('targetId')??''}},[]);
 const [context,setContext]=useState(initial.context),[purpose,setPurpose]=useState(initial.purpose),[targetType,setTargetType]=useState<TargetType>(initial.targetType),[targetId,setTargetId]=useState(initial.targetId),[items,setItems]=useState<CloudMediaAsset[]>([]),[selected,setSelected]=useState<CloudMediaAsset|null>(null),[audioSelection,setAudioSelection]=useState<CloudMediaAsset[]>([]),[query,setQuery]=useState(''),[kind,setKind]=useState(initial.purpose==='audio'?'audio':'all'),[sort,setSort]=useState('newest'),[tab,setTab]=useState<'cloud'|'community'|'unsplash'>('cloud'),[loading,setLoading]=useState(true),[offline,setOffline]=useState(false),[cloudStatus,setCloudStatus]=useState<MediaStorageStatus|null>(null),[busy,setBusy]=useState(''),[staged,setStaged]=useState<MediaAsset[]>([]),[uploadName,setUploadName]=useState(''),[uploadTags,setUploadTags]=useState('');
 const searchRef=useRef<HTMLInputElement>(null),api=(window.desktop as any)?.media,mediaWindow=(window.desktop as any)?.mediaWindow,isAudio=purpose==='audio';
 const audioRouting=usePreferences(state=>state.audioRouting);
 async function refresh(){setLoading(true);try{const status=await api?.onlineStatus?.().catch(()=>null);if(!status?.online)throw new Error(status?.message||'MEDIA_STORAGE_OFFLINE');const cloud=await (api?.cloudList()??Promise.resolve([])).catch(()=>[] as CloudMediaAsset[]);setItems(cloud);setCloudStatus(status);setOffline(false);setSelected(current=>current?cloud.find((entry:CloudMediaAsset)=>entry.id===current.id)??null:null)}catch{setCloudStatus(null);setOffline(true);setItems([])}finally{setLoading(false)}}
 async function searchUnsplash(){if(!prefs.unsplashAccessKey){const key=prompt('Bitte gib den Unsplash Access Key ein. Er wird nur auf diesem Gerät gespeichert.');if(!key)return;prefs.setUnsplashAccessKey(key.trim())}setLoading(true);setOffline(false);try{const key=usePreferences.getState().unsplashAccessKey,results=await api?.unsplashSearch(query,key)??[];setItems(results);setSelected(null)}catch(error){setOffline(true);alert(`Unsplash konnte nicht geladen werden. Bitte prüfe den Access Key und die Internetverbindung.\n\n${String(error).replace(/^Error invoking remote method '[^']+':\s*/,'')}`)}finally{setLoading(false)}}
 useEffect(()=>{void refresh();const dispose=mediaWindow?.onContext((next:{context:Context;purpose:Purpose;targetType?:TargetType;targetId?:string})=>{setContext(next.context);setPurpose(next.purpose);setKind(next.purpose==='audio'?'audio':'all');setTargetType(next.targetType??'section');setTargetId(next.targetId??'');setAudioSelection([])});return()=>dispose?.()},[]);
 useEffect(()=>{if(selected?.kind!=='audio')return;const frame=requestAnimationFrame(()=>{const audio=document.querySelector<HTMLAudioElement>('.detail-preview audio');if(!audio)return;const routing={...defaultAudioRouting,...audioRouting,preview:{...defaultAudioRouting.preview,...audioRouting?.preview}};void applyAudioRoute(audio,routing,'preview')});return()=>cancelAnimationFrame(frame)},[selected?.id,audioRouting]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='f'){event.preventDefault();searchRef.current?.focus()}if(event.key==='Escape'&&context==='select')void mediaWindow?.close()};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[context]);
 const shown=useMemo(()=>items.filter(item=>(kind==='all'||item.kind===kind)&&(purpose!=='background'||item.kind==='image')&&(!isAudio||item.kind==='audio')&&`${item.name} ${(item.tags??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='size'?b.size-a.size:String(b.updatedAt??'').localeCompare(String(a.updatedAt??''))),[items,kind,purpose,isAudio,query,sort]);
 async function beginUpload(){const picked:MediaAsset[]=await api?.import(isAudio?'audio':undefined)??[];if(!picked.length)return;setStaged(picked);setUploadName(picked[0].name);setUploadTags('')}
 const uploadError=(error:unknown)=>{const value=String(error);if(value.includes('MEDIA_STORAGE_NOT_PRIVATE'))return'Die Medien-Cloud ist noch nicht als privater Team-Speicher eingerichtet.';if(value.includes('GITHUB_LOGIN_REQUIRED')||value.includes('HTTP_401')||value.includes('HTTP_403'))return'Die Anmeldung für die Medien-Cloud fehlt oder besitzt keine Upload-Berechtigung.';if(value.includes('TOO_LARGE'))return'Diese Datei ist für den Cloudspeicher zu groß.';if(value.includes('OFFLINE')||value.includes('fetch')||value.includes('timeout'))return'Die Medien-Cloud ist momentan nicht erreichbar. Die Quelldatei bleibt erhalten.';return`Der Upload konnte nicht abgeschlossen werden: ${value.replace(/^Error invoking remote method '[^']+':\s*/,'').slice(0,220)}`};
 async function upload(){setBusy('upload');try{for(const [index,asset] of staged.entries()){await api.update(asset.id,{name:index===0?uploadName.trim()||asset.name:asset.name,tags:uploadTags.split(',').map((tag:string)=>tag.trim()).filter(Boolean)});await api.sync(asset.id)}setStaged([]);await refresh()}catch(error){alert(uploadError(error))}finally{setBusy('')}}
 async function remove(){if(!selected||!confirm(`„${selected.name}“ aus der Medienbibliothek entfernen?`))return;setBusy(selected.id);try{await api.cloudRemove(selected.id);setSelected(null);setAudioSelection(list=>list.filter(entry=>entry.id!==selected.id));await refresh()}catch{alert('Das Medium konnte nicht gelöscht werden. Es wird möglicherweise noch verwendet.')}finally{setBusy('')}}
 function choose(item:CloudMediaAsset){setSelected(item);if(isAudio&&context==='select')setAudioSelection(list=>list.some(entry=>entry.id===item.id)?list.filter(entry=>entry.id!==item.id):[...list,item])}
 function reorder(from:number,to:number){setAudioSelection(list=>{const next=[...list],[moved]=next.splice(from,1);next.splice(to,0,moved);return next})}
 function useSelected(){if(isAudio)return void mediaWindow?.selectAudio(audioSelection,targetType,targetId);if(selected)void mediaWindow?.select(selected,purpose)}
 return <main className={`cloud-media-browser ${isAudio?'audio-browser':''}`}>
  <header className="media-window-header"><div><h1>{isAudio?'Audiobrowser':'Medienbibliothek'}</h1><p>{isAudio?'Musik aus dem Team-Cloudspeicher auswählen und als Playlist hinzufügen.':'Medien zentral suchen, verwalten und für Präsentationen verwenden.'}</p></div><div className={`media-cloud-status ${cloudStatus?.online?'online':'offline'}`} title={cloudStatus?.message??'Cloudstatus wird geprüft'}><Icon name={cloudStatus?.online?'cloud_done':'cloud_off'}/><span>{cloudStatus?.online?'Cloud verbunden':'Cloud wird geprüft'}</span></div></header>
  {!isAudio&&<nav className="media-tabs"><button className={tab==='cloud'?'active':''} onClick={()=>{setTab('cloud');void refresh()}}>CLOUD-MEDIEN</button><button className={tab==='community'?'active':''} onClick={()=>setTab('community')}>COMMUNITY</button><button className={tab==='unsplash'?'active':''} onClick={()=>{setTab('unsplash');void searchUnsplash()}}>UNSPLASH</button></nav>}
  <div className="media-commandbar"><label className="media-search"><Icon name="search"/><input ref={searchRef} placeholder={tab==='unsplash'?'Unsplash durchsuchen':isAudio?'Audio durchsuchen':'Medien durchsuchen'} value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&tab==='unsplash')void searchUnsplash()}}/></label>{tab==='unsplash'&&<button onClick={()=>void searchUnsplash()}><Icon name="search"/> SUCHEN</button>}{!isAudio&&<select value={kind} onChange={event=>setKind(event.target.value)}><option value="all">Alle Medien</option><option value="image">Bilder</option><option value="video">Videos</option><option value="audio">Audio</option><option value="pdf">PDF</option></select>}<select value={sort} onChange={event=>setSort(event.target.value)}><option value="newest">Neueste zuerst</option><option value="name">Name</option><option value="size">Dateigröße</option></select><button className="primary" onClick={()=>void beginUpload()}><Icon name="cloud_upload"/> {isAudio?'AUDIO HOCHLADEN':'MEDIEN HOCHLADEN'}</button></div>
  <div className="media-browser-body"><aside className="media-navigation"><b>BIBLIOTHEK</b><button className="active"><Icon name={isAudio?'library_music':'perm_media'}/> {isAudio?'Alle Audiodateien':'Alle Medien'}</button><button><Icon name="schedule"/> Zuletzt verwendet</button><button><Icon name="star"/> Favoriten</button>{isAudio&&<><b>PLAYLIST</b><p>{audioSelection.length} Titel ausgewählt</p></>}</aside>
   <section className="media-content">{loading?<div className="media-state"><span className="media-loading"/><h2>Medien werden geladen …</h2></div>:offline?<div className="media-state"><Icon name="cloud_off"/><h2>Cloud nicht erreichbar</h2><button onClick={()=>void refresh()}>ERNEUT VERSUCHEN</button></div>:shown.length?(isAudio?<div className="audio-media-list">{shown.map(item=>{const checked=audioSelection.some(entry=>entry.id===item.id);return <button key={item.id} className={`${selected?.id===item.id?'selected':''} ${checked?'checked':''}`} onClick={()=>choose(item)}><Icon name={checked?'check_box':'check_box_outline_blank'}/><Icon name="audio_file"/><span><b>{item.name}</b><small>{item.tags?.join(' · ')||'Team-Audio'}</small></span><small>{(item.extension||item.path.split('.').at(-1)||'Audio').toUpperCase()}</small><small>{bytes(item.size)}</small></button>})}</div>:<div className="cloud-media-grid">{shown.map(item=><button key={item.id} className={selected?.id===item.id?'selected':''} onClick={()=>choose(item)} onDoubleClick={()=>context==='select'&&void mediaWindow?.select(item,purpose)}>{item.kind==='image'?<img loading="lazy" src={item.downloadUrl} alt=""/>:<span className="media-kind"><Icon name={item.kind==='video'?'movie':item.kind==='audio'?'audio_file':'picture_as_pdf'}/></span>}<strong>{item.name}</strong><small>{typeName(item.kind)} · {bytes(item.size)}</small></button>)}</div>):<div className="media-state"><Icon name="cloud_upload"/><h2>{isAudio?'Noch keine Audiodateien':'Noch keine Medien'}</h2><p>Lade Dateien hoch. Erst nach erfolgreichem Cloud-Upload können sie verwendet werden.</p><button className="primary" onClick={()=>void beginUpload()}>HOCHLADEN</button></div>}</section>
   <aside className="media-details">{selected?<><div className="detail-preview">{selected.kind==='image'?<img src={selected.downloadUrl} alt=""/>:selected.kind==='audio'?<><Icon name="graphic_eq"/><audio controls preload="metadata" src={selected.downloadUrl}/></>:<Icon name={selected.kind==='video'?'movie':'picture_as_pdf'}/>}</div><h2>{selected.name}</h2><dl><dt>Typ</dt><dd>{typeName(selected.kind)}</dd><dt>Dateigröße</dt><dd>{bytes(selected.size)}</dd><dt>Format</dt><dd>{selected.extension||selected.path.split('.').at(-1)?.toUpperCase()}</dd><dt>Quelle</dt><dd>{tab==='unsplash'?'Unsplash':'Team-Cloud'}</dd></dl><div className="detail-actions">{context==='select'&&!isAudio&&<button className="primary" onClick={useSelected}>VERWENDEN</button>}{tab!=='unsplash'&&<button className="danger" disabled={busy===selected.id} onClick={()=>void remove()}><Icon name="delete"/> LÖSCHEN</button>}</div></>:<div className="detail-empty"><Icon name="info"/><span>Wähle bitte ein Medium aus.</span></div>}</aside>
  </div>
  {isAudio&&context==='select'&&<footer className="audio-selection-tray"><div><b>{audioSelection.length} Titel ausgewählt</b><span>Reihenfolge durch Ziehen ändern</span></div><div className="audio-selection-chips">{audioSelection.map((item,index)=><span key={item.id} draggable onDragStart={event=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={event=>event.preventDefault()} onDrop={event=>reorder(Number(event.dataTransfer.getData('text/plain')),index)}><Icon name="drag_indicator"/>{item.name}<button onClick={()=>setAudioSelection(list=>list.filter(entry=>entry.id!==item.id))}><Icon name="close"/></button></span>)}</div><button onClick={()=>setAudioSelection([])}>LEEREN</button><button onClick={()=>void mediaWindow?.close()}>ABBRECHEN</button><button className="primary" disabled={!audioSelection.length||!targetId} onClick={useSelected}>HINZUFÜGEN</button></footer>}
  {staged.length>0&&<div className="media-upload-backdrop"><section className="media-upload-dialog"><header><div><h2>{isAudio?'AUDIO HOCHLADEN':'MEDIEN HOCHLADEN'}</h2><p>Nach erfolgreichem Upload steht die Datei im Team-Cloudspeicher bereit.</p></div><button onClick={()=>setStaged([])}><Icon name="close"/></button></header><div className="upload-preview"><Icon name={isAudio?'audio_file':'cloud_upload'}/><span>{staged.map(item=>item.fileName).join(', ')}</span></div><label>Name<input value={uploadName} onChange={event=>setUploadName(event.target.value)}/></label><label>Interpret / Schlagwörter<input placeholder="z. B. Instrumental, Worship" value={uploadTags} onChange={event=>setUploadTags(event.target.value)}/></label><footer><button onClick={()=>setStaged([])}>ABBRECHEN</button><button className="primary" disabled={busy==='upload'} onClick={()=>void upload()}>{busy==='upload'?'WIRD HOCHGELADEN …':'JETZT HOCHLADEN'}</button></footer></section></div>}
 </main>
}
