import {useEffect,useMemo,useRef,useState} from 'react';
import {usePreferences} from './preferences';
import {applyAudioRoute,defaultAudioRouting} from './audioRouting';
const Icon=({name}:{name:string})=><span className="material-symbols-outlined" aria-hidden="true">{name}</span>;
type Context='manage'|'select';type Purpose='item'|'background'|'audio';type TargetType='section'|'serviceItem';
const bytes=(value:number)=>value<1048576?`${Math.max(1,Math.round(value/1024))} KB`:`${(value/1048576).toLocaleString('de-DE',{maximumFractionDigits:1})} MB`;
const typeName=(kind:CloudMediaAsset['kind'])=>({image:'Bild',video:'Video',audio:'Audio',pdf:'PDF'})[kind];
export function MediaBrowser(){
 const prefs=usePreferences();
 const initial=useMemo(()=>{const q=new URLSearchParams(location.hash.split('?')[1]??''),purpose=(q.get('purpose')==='audio'?'audio':q.get('purpose')==='background'?'background':'item') as Purpose;return{context:(q.get('context')==='select'?'select':'manage') as Context,purpose,targetType:(q.get('targetType')==='serviceItem'?'serviceItem':'section') as TargetType,targetId:q.get('targetId')??''}},[]);
 const [context,setContext]=useState(initial.context),[purpose,setPurpose]=useState(initial.purpose),[targetType,setTargetType]=useState<TargetType>(initial.targetType),[targetId,setTargetId]=useState(initial.targetId),[items,setItems]=useState<CloudMediaAsset[]>([]),[cloudItems,setCloudItems]=useState<CloudMediaAsset[]>([]),[selected,setSelected]=useState<CloudMediaAsset|null>(null),[audioSelection,setAudioSelection]=useState<CloudMediaAsset[]>([]),[query,setQuery]=useState(''),[kind,setKind]=useState(initial.purpose==='audio'?'audio':'all'),[sort,setSort]=useState('newest'),[tab,setTab]=useState<'cloud'|'community'|'unsplash'>('cloud'),[libraryFilter,setLibraryFilter]=useState<'all'|'recent'|'favorites'>('all'),[visibleCount,setVisibleCount]=useState(30),[loading,setLoading]=useState(true),[offline,setOffline]=useState(false),[cloudStatus,setCloudStatus]=useState<MediaStorageStatus|null>(null),[busy,setBusy]=useState(''),[staged,setStaged]=useState<MediaAsset[]>([]),[uploadName,setUploadName]=useState(''),[uploadTags,setUploadTags]=useState('');
 const [deleteTarget,setDeleteTarget]=useState<CloudMediaAsset|null>(null),[gridSize,setGridSize]=useState(()=>Number(localStorage.getItem('gottesdienstregie.media-grid-size')||190)),[generatorOpen,setGeneratorOpen]=useState(false),[generatorPrompt,setGeneratorPrompt]=useState('Ruhiger abstrakter Gottesdienst-Hintergrund'),[generatorStyle,setGeneratorStyle]=useState('soft');
 const searchRef=useRef<HTMLInputElement>(null),api=(window.desktop as any)?.media,mediaWindow=(window.desktop as any)?.mediaWindow,isAudio=purpose==='audio';
 const audioRouting=usePreferences(state=>state.audioRouting);
 async function refresh(target=tab){setLoading(true);try{const status=await api?.onlineStatus?.().catch(()=>null);if(!status?.online)throw new Error(status?.message||'MEDIA_STORAGE_OFFLINE');const cloud=await (api?.cloudList()??Promise.resolve([])).catch(()=>[] as CloudMediaAsset[]);setCloudItems(cloud);setItems(target==='community'?cloud.filter((entry:CloudMediaAsset)=>entry.visibility==='community'):cloud);setCloudStatus(status);setOffline(false);setSelected(current=>current?cloud.find((entry:CloudMediaAsset)=>entry.id===current.id)??null:null)}catch{setCloudStatus(null);setOffline(true);setItems([])}finally{setLoading(false)}}
 async function searchUnsplash(search=query){setLoading(true);setOffline(false);try{const key=usePreferences.getState().unsplashAccessKey,results=await api?.unsplashSearch(search,key)??[];setItems(results);setSelected(null)}catch(error){setOffline(true);alert(`Unsplash konnte nicht geladen werden. Bitte prüfe die Internetverbindung und versuche es erneut.\n\n${String(error).replace(/^Error invoking remote method '[^']+':\s*/,'')}`)}finally{setLoading(false)}}
 useEffect(()=>{void refresh();const dispose=mediaWindow?.onContext((next:{context:Context;purpose:Purpose;targetType?:TargetType;targetId?:string})=>{setContext(next.context);setPurpose(next.purpose);setKind(next.purpose==='audio'?'audio':'all');setTargetType(next.targetType??'section');setTargetId(next.targetId??'');setAudioSelection([])});return()=>dispose?.()},[]);
 useEffect(()=>{if(selected?.kind!=='audio')return;const frame=requestAnimationFrame(()=>{const audio=document.querySelector<HTMLAudioElement>('.detail-preview audio');if(!audio)return;const routing={...defaultAudioRouting,...audioRouting,preview:{...defaultAudioRouting.preview,...audioRouting?.preview}};void applyAudioRoute(audio,routing,'preview')});return()=>cancelAnimationFrame(frame)},[selected?.id,audioRouting]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='f'){event.preventDefault();searchRef.current?.focus()}if(event.key==='Delete'&&selected&&tab!=='unsplash'&&context==='manage'){event.preventDefault();setDeleteTarget(selected)}if(event.key==='Escape'){if(deleteTarget)setDeleteTarget(null);else if(context==='select')void mediaWindow?.close()}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[context,selected,tab,deleteTarget]);
 const shown=useMemo(()=>items.filter(item=>(kind==='all'||item.kind===kind)&&(purpose!=='background'||item.kind==='image')&&(!isAudio||item.kind==='audio')&&(libraryFilter!=='favorites'||item.favorite)&&(libraryFilter!=='recent'||Boolean(item.updatedAt))&&`${item.name} ${(item.tags??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='size'?b.size-a.size:String(b.updatedAt??'').localeCompare(String(a.updatedAt??''))).slice(0,libraryFilter==='recent'?Math.min(20,visibleCount):visibleCount),[items,kind,purpose,isAudio,query,sort,libraryFilter,visibleCount]);
 const totalMatches=useMemo(()=>items.filter(item=>(kind==='all'||item.kind===kind)&&(purpose!=='background'||item.kind==='image')&&(!isAudio||item.kind==='audio')&&(libraryFilter!=='favorites'||item.favorite)&&(libraryFilter!=='recent'||Boolean(item.updatedAt))&&`${item.name} ${(item.tags??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())).length,[items,kind,purpose,isAudio,query,libraryFilter]);
 function switchTab(next:'cloud'|'community'|'unsplash'){setTab(next);setSelected(null);setQuery('');setKind(isAudio?'audio':'all');setLibraryFilter('all');setVisibleCount(30);setOffline(false);if(next==='cloud'){setItems(cloudItems);void refresh('cloud')}else if(next==='community'){setLoading(false);setItems(cloudItems.filter(entry=>entry.visibility==='community'))}else{setItems([]);void searchUnsplash('')}}
 function resetFilters(){setQuery('');setKind(isAudio?'audio':'all');setLibraryFilter('all');setVisibleCount(30)}
 async function beginUpload(){const picked:MediaAsset[]=await api?.import(isAudio?'audio':undefined)??[];if(!picked.length)return;setStaged(picked);setUploadName(picked[0].name);setUploadTags('')}
 const uploadError=(error:unknown)=>{const value=String(error);if(value.includes('MEDIA_STORAGE_NOT_PRIVATE'))return'Die Medien-Cloud ist noch nicht als privater Team-Speicher eingerichtet.';if(value.includes('GITHUB_LOGIN_REQUIRED')||value.includes('HTTP_401')||value.includes('HTTP_403'))return'Die Anmeldung für die Medien-Cloud fehlt oder besitzt keine Upload-Berechtigung.';if(value.includes('TOO_LARGE'))return'Diese Datei ist für den Cloudspeicher zu groß.';if(value.includes('OFFLINE')||value.includes('fetch')||value.includes('timeout'))return'Die Medien-Cloud ist momentan nicht erreichbar. Die Quelldatei bleibt erhalten.';return`Der Upload konnte nicht abgeschlossen werden: ${value.replace(/^Error invoking remote method '[^']+':\s*/,'').slice(0,220)}`};
 async function upload(){setBusy('upload');try{for(const [index,asset] of staged.entries()){await api.update(asset.id,{name:index===0?uploadName.trim()||asset.name:asset.name,tags:uploadTags.split(',').map((tag:string)=>tag.trim()).filter(Boolean)});await api.sync(asset.id)}setStaged([]);await refresh()}catch(error){alert(uploadError(error))}finally{setBusy('')}}
 async function remove(){if(!deleteTarget){if(selected)setDeleteTarget(selected);return}const target=deleteTarget;setBusy(target.id);try{await api.cloudRemove(target.id);setSelected(null);setDeleteTarget(null);setAudioSelection(list=>list.filter(entry=>entry.id!==target.id));await refresh()}catch(error){const detail=String(error);setDeleteTarget(null);alert(detail.includes('MEDIA_IN_PRESENTATIONS')?'Dieses Medium wird noch in einer Präsentation verwendet und kann deshalb nicht gelöscht werden.':detail.includes('MEDIA_IN_LIVE_USE')?'Während ON AIR können Medien nicht gelöscht werden.':'Das Medium konnte nicht gelöscht werden. Bitte prüfe Cloud-Verbindung und Berechtigung.')}finally{setBusy('')}}
 async function toggleFavorite(){if(!selected||tab==='unsplash')return;setBusy(selected.id);try{await api.update(selected.id,{favorite:!selected.favorite});setSelected({...selected,favorite:!selected.favorite});await refresh(tab)}finally{setBusy('')}}
 function choose(item:CloudMediaAsset){setSelected(item);if(isAudio&&context==='select')setAudioSelection(list=>list.some(entry=>entry.id===item.id)?list.filter(entry=>entry.id!==item.id):[...list,item])}
 function reorder(from:number,to:number){setAudioSelection(list=>{const next=[...list],[moved]=next.splice(from,1);next.splice(to,0,moved);return next})}
 function useSelected(){if(isAudio)return void mediaWindow?.selectAudio(audioSelection,targetType,targetId);if(selected)void mediaWindow?.select(selected,purpose)}
 function generateLocal(){const seed=[...generatorPrompt].reduce((sum,char)=>sum+char.charCodeAt(0),0),hue=seed%360,hue2=(hue+generatorStyle==='bold'?95:55)%360,id=`generated-${Date.now()}`,safe=generatorPrompt.replace(/[<>&"']/g,'').slice(0,120),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1920" height="1080" viewBox="0 0 1920 1080"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${hue} 55% ${generatorStyle==='dark'?12:30}%)"/><stop offset="1" stop-color="hsl(${hue2} 65% ${generatorStyle==='dark'?20:55}%)"/></linearGradient><filter id="b"><feGaussianBlur stdDeviation="75"/></filter></defs><rect width="1920" height="1080" fill="url(#g)"/><g opacity=".5" filter="url(#b)"><circle cx="${300+seed%500}" cy="260" r="360" fill="hsl(${(hue+130)%360} 70% 62%)"/><circle cx="1450" cy="${550+seed%250}" r="430" fill="hsl(${(hue2+90)%360} 70% 55%)"/></g><path d="M0 850 Q480 ${520+seed%180} 960 820 T1920 700 V1080 H0Z" fill="#000" opacity=".18"/><metadata>${safe}</metadata></svg>`,url=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`,asset={id,name:`KI-Motiv · ${generatorPrompt.slice(0,42)}`,path:'lokal-generiert',kind:'image' as const,size:new Blob([svg]).size,checksum:id,downloadUrl:url,updatedAt:new Date().toISOString(),tags:['KI-generiert','Lokal','Ohne API-Schlüssel'],extension:'SVG',visibility:'private' as const};setItems(current=>[asset,...current]);setSelected(asset);setGeneratorOpen(false)}
 return <main className={`cloud-media-browser ${isAudio?'audio-browser':''}`} style={{'--media-card-size':`${gridSize}px`} as any}>
  <header className="media-window-header"><div><h1>{isAudio?'Audiobrowser':'Medienbibliothek'}</h1><p>{isAudio?'Musik aus dem Team-Cloudspeicher auswählen und als Playlist hinzufügen.':'Medien zentral suchen, verwalten und für Präsentationen verwenden.'}</p></div><div className={`media-cloud-status ${cloudStatus?.online?'online':'offline'}`} title={cloudStatus?.message??'Cloudstatus wird geprüft'}><Icon name={cloudStatus?.online?'cloud_done':'cloud_off'}/></div></header>
  {!isAudio&&<nav className="media-tabs"><button className={tab==='cloud'?'active':''} onClick={()=>switchTab('cloud')}>CLOUD-MEDIEN</button><button className={tab==='community'?'active':''} onClick={()=>switchTab('community')}>COMMUNITY</button><button className={tab==='unsplash'?'active':''} onClick={()=>switchTab('unsplash')}><span className="unsplash-mini-mark" aria-hidden="true"><i/><i/></span> UNSPLASH</button>{prefs.aiEnabled&&<button onClick={()=>setGeneratorOpen(true)}><Icon name="auto_awesome"/> KI-MOTIVE</button>}</nav>}
  <div className="media-commandbar"><label className="media-search"><Icon name="search"/><input ref={searchRef} placeholder={tab==='unsplash'?'Unsplash durchsuchen':isAudio?'Audio durchsuchen':'Medien durchsuchen'} value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&tab==='unsplash')void searchUnsplash()}}/></label>{tab==='unsplash'&&<button onClick={()=>void searchUnsplash()}><Icon name="search"/> SUCHEN</button>}{!isAudio&&<select value={kind} onChange={event=>setKind(event.target.value)}><option value="all">Alle Medien</option><option value="image">Bilder</option><option value="video">Videos</option><option value="audio">Audio</option><option value="pdf">PDF</option></select>}<select value={sort} onChange={event=>setSort(event.target.value)}><option value="newest">Neueste zuerst</option><option value="name">Name</option><option value="size">Dateigröße</option></select><button className="primary" onClick={()=>void beginUpload()}><Icon name="cloud_upload"/> {isAudio?'AUDIO HOCHLADEN':'MEDIEN HOCHLADEN'}</button></div>
  <div className="media-viewbar"><span><b>{totalMatches}</b> {totalMatches===1?'Medium':'Medien'} gefunden</span><label title="Größe der Medienkacheln"><Icon name="photo_size_select_small"/><input type="range" min="140" max="280" step="20" value={gridSize} onChange={event=>{const value=Number(event.target.value);setGridSize(value);localStorage.setItem('gottesdienstregie.media-grid-size',String(value))}}/><Icon name="photo_size_select_large"/></label>{selected&&tab!=='unsplash'&&<><button onClick={()=>void toggleFavorite()} disabled={busy===selected.id}><Icon name={selected.favorite?'star':'star_outline'}/> {selected.favorite?'FAVORIT ENTFERNEN':'ALS FAVORIT'}</button><button className="danger" onClick={()=>setDeleteTarget(selected)} disabled={busy===selected.id}><Icon name="delete"/> MEDIUM LÖSCHEN</button></>}</div>
  <div className="media-browser-body"><aside className="media-navigation"><b>BIBLIOTHEK</b><button className={libraryFilter==='all'?'active':''} onClick={()=>{setLibraryFilter('all');setVisibleCount(30)}}><Icon name={isAudio?'library_music':'perm_media'}/> {isAudio?'Alle Audiodateien':'Alle Medien'}</button><button className={libraryFilter==='recent'?'active':''} onClick={()=>{setLibraryFilter('recent');setVisibleCount(30)}}><Icon name="schedule"/> Zuletzt verwendet</button><button className={libraryFilter==='favorites'?'active':''} onClick={()=>{setLibraryFilter('favorites');setVisibleCount(30)}}><Icon name="star"/> Favoriten</button>{isAudio&&<><b>PLAYLIST</b><p>{audioSelection.length} Titel ausgewählt</p></>}</aside>
   <section className="media-content">{tab==='unsplash'&&!loading&&<div className="unsplash-category-brand"><span className="unsplash-mini-mark" aria-hidden="true"><i/><i/></span><b>Unsplash</b><small>Kostenlose Fotos durchsuchen</small></div>}{loading?<div className="media-state"><span className="media-loading"/><h2>Medien werden geladen …</h2></div>:offline?<div className="media-state"><Icon name="cloud_off"/><h2>{tab==='unsplash'?'Unsplash nicht erreichbar':'Cloud nicht erreichbar'}</h2><button onClick={()=>tab==='unsplash'?void searchUnsplash():void refresh()}>ERNEUT VERSUCHEN</button></div>:shown.length?<>{isAudio?<div className="audio-media-list">{shown.map(item=>{const checked=audioSelection.some(entry=>entry.id===item.id);return <button key={item.id} className={`${selected?.id===item.id?'selected':''} ${checked?'checked':''}`} onClick={()=>choose(item)}><Icon name={checked?'check_box':'check_box_outline_blank'}/><Icon name="audio_file"/><span><b>{item.name}</b><small>{item.tags?.join(' · ')||'Team-Audio'}</small></span><small>{(item.extension||item.path.split('.').at(-1)||'Audio').toUpperCase()}</small><small>{bytes(item.size)}</small></button>})}</div>:<div className="cloud-media-grid">{shown.map(item=><button key={item.id} className={selected?.id===item.id?'selected':''} onClick={()=>choose(item)} onDoubleClick={()=>context==='select'&&void mediaWindow?.select(item,purpose)}>{item.kind==='image'?<img loading="lazy" src={item.downloadUrl} alt=""/>:<span className="media-kind"><Icon name={item.kind==='video'?'movie':item.kind==='audio'?'audio_file':'picture_as_pdf'}/></span>}<strong>{item.name}</strong><small>{typeName(item.kind)} · {bytes(item.size)}</small></button>)}</div>}<div className="media-load-controls">{totalMatches>visibleCount&&<button onClick={()=>setVisibleCount(value=>value+30)}>MEHR LADEN</button>}{visibleCount>30&&<button onClick={()=>setVisibleCount(30)}>WENIGER ANZEIGEN</button>}</div></>:items.length>0||query||kind!=='all'||libraryFilter!=='all'?<div className="media-state"><Icon name="filter_alt_off"/><h2>Keine passenden Medien gefunden</h2><p>Bitte ändere den Suchbegriff oder setze die Filter zurück.</p><button onClick={resetFilters}>FILTER ZURÜCKSETZEN</button></div>:<div className="media-state"><Icon name={tab==='community'?'groups':'cloud_upload'}/><h2>{tab==='community'?'Noch keine Community-Medien':isAudio?'Noch keine Audiodateien':'Noch keine Medien'}</h2><p>{tab==='community'?'Freigegebene Medien werden hier getrennt von Unsplash und der Team-Cloud angezeigt.':'Lade bitte Dateien hoch. Erst nach erfolgreichem Cloud-Upload können sie verwendet werden.'}</p>{tab==='cloud'&&<button className="primary" onClick={()=>void beginUpload()}>HOCHLADEN</button>}</div>}</section>
   <aside className="media-details">{selected?<><div className="detail-preview">{selected.kind==='image'?<img src={selected.downloadUrl} alt=""/>:selected.kind==='audio'?<><Icon name="graphic_eq"/><audio controls preload="metadata" src={selected.downloadUrl}/></>:<Icon name={selected.kind==='video'?'movie':'picture_as_pdf'}/>}</div><h2>{selected.name}</h2><dl><dt>Typ</dt><dd>{typeName(selected.kind)}</dd><dt>Dateigröße</dt><dd>{bytes(selected.size)}</dd><dt>Format</dt><dd>{selected.extension||selected.path.split('.').at(-1)?.toUpperCase()}</dd><dt>Quelle</dt><dd>{tab==='unsplash'?'Unsplash':'Team-Cloud'}</dd></dl><div className="detail-actions">{context==='select'&&!isAudio&&<button className="primary" onClick={useSelected}>VERWENDEN</button>}{tab!=='unsplash'&&<button className="danger" disabled={busy===selected.id} onClick={()=>void remove()}><Icon name="delete"/> LÖSCHEN</button>}</div></>:<div className="detail-empty"><Icon name="info"/><span>Wähle bitte ein Medium aus.</span></div>}</aside>
  </div>
  {isAudio&&context==='select'&&<footer className="audio-selection-tray"><div><b>{audioSelection.length} Titel ausgewählt</b><span>Reihenfolge durch Ziehen ändern</span></div><div className="audio-selection-chips">{audioSelection.map((item,index)=><span key={item.id} draggable onDragStart={event=>event.dataTransfer.setData('text/plain',String(index))} onDragOver={event=>event.preventDefault()} onDrop={event=>reorder(Number(event.dataTransfer.getData('text/plain')),index)}><Icon name="drag_indicator"/>{item.name}<button onClick={()=>setAudioSelection(list=>list.filter(entry=>entry.id!==item.id))}><Icon name="close"/></button></span>)}</div><button onClick={()=>setAudioSelection([])}>LEEREN</button><button onClick={()=>void mediaWindow?.close()}>ABBRECHEN</button><button className="primary" disabled={!audioSelection.length||!targetId} onClick={useSelected}>HINZUFÜGEN</button></footer>}
  {staged.length>0&&<div className="media-upload-backdrop"><section className="media-upload-dialog"><header><div><h2>{isAudio?'AUDIO HOCHLADEN':'MEDIEN HOCHLADEN'}</h2><p>Nach erfolgreichem Upload steht die Datei im Team-Cloudspeicher bereit.</p></div><button onClick={()=>setStaged([])}><Icon name="close"/></button></header><div className="upload-preview"><Icon name={isAudio?'audio_file':'cloud_upload'}/><span>{staged.map(item=>item.fileName).join(', ')}</span></div><label>Name<input value={uploadName} onChange={event=>setUploadName(event.target.value)}/></label><label>Interpret / Schlagwörter<input placeholder="z. B. Instrumental, Worship" value={uploadTags} onChange={event=>setUploadTags(event.target.value)}/></label><footer><button onClick={()=>setStaged([])}>ABBRECHEN</button><button className="primary" disabled={busy==='upload'} onClick={()=>void upload()}>{busy==='upload'?'WIRD HOCHGELADEN …':'JETZT HOCHLADEN'}</button></footer></section></div>}
  {deleteTarget&&<div className="media-upload-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setDeleteTarget(null)}><section className="media-delete-dialog" role="alertdialog" aria-modal="true" aria-labelledby="media-delete-title"><Icon name="delete_forever"/><h2 id="media-delete-title">MEDIUM LÖSCHEN?</h2><p><b>{deleteTarget.name}</b> wird dauerhaft aus der Team-Medienbibliothek entfernt. Cloud-Dateien, die noch in einer Präsentation verwendet werden, bleiben geschützt.</p><footer><button onClick={()=>setDeleteTarget(null)}>ABBRECHEN</button><button className="danger" disabled={busy===deleteTarget.id} onClick={()=>void remove()}>{busy===deleteTarget.id?'WIRD GELÖSCHT …':'DAUERHAFT LÖSCHEN'}</button></footer></section></div>}
  {generatorOpen&&<div className="media-upload-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setGeneratorOpen(false)}><section className="media-upload-dialog" role="dialog" aria-modal="true"><header><div><h2>KI-MOTIV ERSTELLEN</h2><p>Erzeugt lokal einen individuellen 16:9-Hintergrund. Es wird kein API-Schlüssel benötigt und kein Prompt an einen externen Dienst gesendet.</p></div><button onClick={()=>setGeneratorOpen(false)}><Icon name="close"/></button></header><label>Motivbeschreibung<textarea rows={4} maxLength={300} value={generatorPrompt} onChange={event=>setGeneratorPrompt(event.target.value)} placeholder="z. B. ruhiger blauer Hintergrund mit warmem Licht"/></label><label>Stil<select value={generatorStyle} onChange={event=>setGeneratorStyle(event.target.value)}><option value="soft">Ruhig und weich</option><option value="bold">Kräftig und kontrastreich</option><option value="dark">Dunkel für helle Schrift</option></select></label><footer><button onClick={()=>setGeneratorOpen(false)}>ABBRECHEN</button><button className="primary" disabled={!generatorPrompt.trim()} onClick={generateLocal}>MOTIV ERSTELLEN</button></footer></section></div>}
 </main>
}
