import {useEffect,useMemo,useState} from 'react';

const Icon=({name}:{name:string})=><span className="material-symbols-outlined" aria-hidden="true">{name}</span>;
type Context='manage'|'select';type Purpose='item'|'background';type Tab='own'|'community'|'unsplash';
const bytes=(value:number)=>value<1024*1024?`${Math.max(1,Math.round(value/1024))} KB`:`${(value/1024/1024).toLocaleString('de-DE',{maximumFractionDigits:1})} MB`;
const typeName=(kind:CloudMediaAsset['kind'])=>({image:'Bild',video:'Video',audio:'Audio',pdf:'PDF'})[kind];

export function MediaBrowser(){
  const initial=useMemo(()=>{const query=new URLSearchParams(location.hash.split('?')[1]??'');return{context:(query.get('context')==='select'?'select':'manage') as Context,purpose:(query.get('purpose')==='background'?'background':'item') as Purpose}},[]);
  const [context,setContext]=useState<Context>(initial.context),[purpose,setPurpose]=useState<Purpose>(initial.purpose),[tab,setTab]=useState<Tab>('own'),[items,setItems]=useState<CloudMediaAsset[]>([]),[legacy,setLegacy]=useState<MediaAsset[]>([]),[selected,setSelected]=useState<CloudMediaAsset|null>(null),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[sort,setSort]=useState('newest'),[loading,setLoading]=useState(true),[offline,setOffline]=useState(false),[busy,setBusy]=useState(''),[staged,setStaged]=useState<MediaAsset[]>([]),[uploadName,setUploadName]=useState(''),[uploadTags,setUploadTags]=useState('');
  const api=(window.desktop as any)?.media,mediaWindow=(window.desktop as any)?.mediaWindow;
  async function refresh(){setLoading(true);try{const [cloud,pending]=await Promise.all([api?.cloudList()??[],api?.legacyList()??[]]);setItems(cloud);setLegacy(pending);setOffline(false);setSelected(current=>current?cloud.find((entry:CloudMediaAsset)=>entry.id===current.id)??null:null)}catch{setOffline(true);setItems([])}finally{setLoading(false)}}
  useEffect(()=>{void refresh();const dispose=mediaWindow?.onContext((next:{context:Context;purpose:Purpose})=>{setContext(next.context);setPurpose(next.purpose)});return()=>dispose?.()},[]);
  const shown=useMemo(()=>items.filter(item=>(kind==='all'||item.kind===kind)&&(purpose!=='background'||item.kind==='image')&&`${item.name} ${(item.tags??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='size'?(b.size-a.size):String(b.updatedAt??'').localeCompare(String(a.updatedAt??''))),[items,kind,purpose,query,sort]);
  async function beginUpload(){const picked:MediaAsset[]=await api?.import()??[];if(!picked.length)return;setStaged(picked);setUploadName(picked[0].name);setUploadTags('')}
  async function upload(){setBusy('upload');try{for(const [index,asset] of staged.entries()){const name=index===0?uploadName.trim()||asset.name:asset.name;await api.update(asset.id,{name,tags:uploadTags.split(',').map((tag:string)=>tag.trim()).filter(Boolean)});await api.sync(asset.id)}setStaged([]);await refresh()}catch(error){const message=String(error);alert(message.includes('TOO_LARGE')?'Diese Datei ist für den kostenlosen Cloudspeicher zu groß. Es wurde kein Bibliothekseintrag angelegt.':'Der Upload konnte nicht abgeschlossen werden. Prüfe deine Internetverbindung und die Upload-Berechtigung.')}finally{setBusy('')}}
  async function migrateAll(){setBusy('migration');try{for(const asset of legacy)await api.sync(asset.id);await refresh()}catch{alert('Die Migration wurde unterbrochen. Bereits hochgeladene Medien bleiben sicher gespeichert; die übrigen können später erneut übertragen werden.')}finally{setBusy('')}}
  async function remove(){if(!selected||!confirm(`„${selected.name}“ aus der Medienbibliothek entfernen?`))return;setBusy(selected.id);try{await api.cloudRemove(selected.id);setSelected(null);await refresh()}catch(error){const value=String(error);alert(value.includes('MEDIA_IN_LIVE_USE')?'Dieses Medium wird gerade in einer laufenden Ausgabe verwendet und kann nicht gelöscht werden.':value.includes('MEDIA_IN_PRESENTATIONS')?`Dieses Medium wird noch in Präsentationen verwendet und kann deshalb nicht gelöscht werden.\n\n${value.split(':').slice(1).join(':').replaceAll('|','\n')}`:'Das Medium konnte nicht gelöscht werden.')}finally{setBusy('')}}
  function choose(item:CloudMediaAsset){setSelected(item);if(context==='select'&&purpose==='background'&&item.kind!=='image')return}
  return <main className="cloud-media-browser">
    <header className="media-window-header"><div><h1>Medienbibliothek</h1><p>Medien zentral suchen, verwalten und für Präsentationen verwenden.</p></div><button title="Schließen" onClick={()=>void mediaWindow?.close()}><Icon name="close"/></button></header>
    <nav className="media-tabs" aria-label="Medienbereiche"><button className={tab==='own'?'active':''} onClick={()=>setTab('own')}>EIGENE MEDIEN</button><button className={tab==='community'?'active':''} onClick={()=>setTab('community')}>COMMUNITY</button><button className={tab==='unsplash'?'active':''} onClick={()=>setTab('unsplash')}>UNSPLASH</button></nav>
    <div className="media-commandbar"><label className="media-search"><Icon name="search"/><input placeholder="Medien durchsuchen" value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Medientyp" value={kind} onChange={event=>setKind(event.target.value)}><option value="all">Alle Medien</option><option value="image">Bilder</option><option value="video">Videos</option><option value="audio">Audio</option><option value="pdf">PDF</option></select><select aria-label="Sortierung" value={sort} onChange={event=>setSort(event.target.value)}><option value="newest">Neueste zuerst</option><option value="name">Name</option><option value="size">Dateigröße</option></select>{tab==='own'&&<button className="primary" onClick={()=>void beginUpload()}><Icon name="cloud_upload"/> MEDIEN HOCHLADEN</button>}</div>
    {legacy.length>0&&tab==='own'&&<aside className="migration-banner"><Icon name="cloud_sync"/><div><b>{legacy.length===1?'Ein vorhandenes Medium muss in die Cloud übertragen werden.':`${legacy.length} vorhandene Medien müssen in die Cloud übertragen werden.`}</b><span>Die Quelldateien bleiben während der sicheren Übertragung erhalten.</span></div><button disabled={busy==='migration'} onClick={()=>void migrateAll()}>{busy==='migration'?'WIRD ÜBERTRAGEN …':'JETZT MIGRIEREN'}</button></aside>}
    <div className="media-browser-body"><aside className="media-navigation"><b>BIBLIOTHEK</b><button className="active"><Icon name="perm_media"/> Alle Medien</button><button><Icon name="schedule"/> Zuletzt verwendet</button><button><Icon name="star"/> Favoriten</button><b>MEDIENTYPEN</b><button onClick={()=>setKind('image')}><Icon name="image"/> Bilder</button><button onClick={()=>setKind('video')}><Icon name="movie"/> Videos</button><button onClick={()=>setKind('audio')}><Icon name="audio_file"/> Audio</button><button onClick={()=>setKind('pdf')}><Icon name="picture_as_pdf"/> Dokumente</button></aside>
      <section className="media-content">{tab!=='own'?<div className="media-state"><Icon name={tab==='community'?'groups':'photo_library'}/><h2>{tab==='community'?'Community-Medien':'Unsplash'}</h2><p>{tab==='community'?'Für dieses Team ist noch keine veröffentlichte Community-Bibliothek eingerichtet.':'Unsplash ist nicht konfiguriert. Es werden keine Ersatzbilder oder simulierten Suchergebnisse angezeigt.'}</p></div>:loading?<div className="media-state"><span className="media-loading"/><h2>Medien werden geladen …</h2></div>:offline?<div className="media-state"><Icon name="cloud_off"/><h2>Cloud nicht erreichbar</h2><p>Prüfe die Internetverbindung und versuche es erneut.</p><button onClick={()=>void refresh()}>ERNEUT VERSUCHEN</button></div>:shown.length?<div className="cloud-media-grid">{shown.map(item=><button key={item.id} className={selected?.id===item.id?'selected':''} onClick={()=>choose(item)} onDoubleClick={()=>context==='select'&&void mediaWindow?.select(item,purpose)}>{item.kind==='image'?<img loading="lazy" src={item.downloadUrl} alt=""/>:<span className="media-kind"><Icon name={item.kind==='video'?'movie':item.kind==='audio'?'audio_file':'picture_as_pdf'}/></span>}<strong>{item.name}</strong><small>{typeName(item.kind)} · {bytes(item.size)}</small>{item.favorite&&<Icon name="star"/>}</button>)}</div>:<div className="media-state"><Icon name="cloud_upload"/><h2>Noch keine Medien</h2><p>Lade Bilder, Videos, Audio oder PDF-Dateien hoch. Erst nach erfolgreichem Upload erscheinen sie hier.</p><button className="primary" onClick={()=>void beginUpload()}>MEDIEN HOCHLADEN</button></div>}</section>
      <aside className="media-details">{selected?<><div className="detail-preview">{selected.kind==='image'?<img src={selected.downloadUrl} alt=""/>:<Icon name={selected.kind==='video'?'movie':selected.kind==='audio'?'audio_file':'picture_as_pdf'}/>}</div><h2>{selected.name}</h2><dl><dt>Typ</dt><dd>{typeName(selected.kind)}</dd><dt>Dateigröße</dt><dd>{bytes(selected.size)}</dd><dt>Format</dt><dd>{selected.extension||selected.path.split('.').at(-1)?.toUpperCase()}</dd><dt>Sichtbarkeit</dt><dd>Team</dd>{selected.updatedAt&&<><dt>Geändert</dt><dd>{new Date(selected.updatedAt).toLocaleString('de-DE')}</dd></>}</dl>{selected.tags?.length?<div className="detail-tags">{selected.tags.map(tag=><span key={tag}>{tag}</span>)}</div>:null}<div className="detail-actions">{context==='select'&&<button className="primary" disabled={purpose==='background'&&selected.kind!=='image'} onClick={()=>void mediaWindow?.select(selected,purpose)}>VERWENDEN</button>}<button><Icon name="star"/> FAVORIT</button><button className="danger" disabled={busy===selected.id} onClick={()=>void remove()}><Icon name="delete"/> LÖSCHEN</button></div></>:<div className="detail-empty"><Icon name="info"/><span>Wähle ein Medium aus, um Details und Aktionen anzuzeigen.</span></div>}</aside>
    </div>
    {staged.length>0&&<div className="media-upload-backdrop"><section className="media-upload-dialog"><header><div><h2>MEDIEN HOCHLADEN</h2><p>{staged.length===1?'Datei prüfen und anschließend in die Cloud hochladen.':`${staged.length} Dateien prüfen und anschließend in die Cloud hochladen.`}</p></div><button onClick={()=>setStaged([])}><Icon name="close"/></button></header><div className="upload-preview">{staged[0].kind==='image'?<img src={staged[0].url} alt="Vorschau"/>:<Icon name={staged[0].kind==='video'?'movie':staged[0].kind==='audio'?'audio_file':'picture_as_pdf'}/>}<span>{staged.map(item=>item.fileName).join(', ')}</span></div><label>Name<input value={uploadName} onChange={event=>setUploadName(event.target.value)}/></label><label>Schlagwörter<input placeholder="z. B. Gottesdienst, Hintergrund" value={uploadTags} onChange={event=>setUploadTags(event.target.value)}/></label><label>Sichtbarkeit<select><option>Nur Team</option></select></label><footer><button onClick={()=>setStaged([])}>ABBRECHEN</button><button className="primary" disabled={busy==='upload'} onClick={()=>void upload()}>{busy==='upload'?'WIRD HOCHGELADEN …':'JETZT HOCHLADEN'}</button></footer></section></div>}
  </main>
}
