import { useEffect, useRef, useState } from 'react';
import { readPersonalNote, sanitizeRichNote, writePersonalNote, type PersonalNoteKey } from './personalNotes';
type Props={noteKey:PersonalNoteKey;label:string;presentation?:boolean};
export function PersonalNotesPanel({noteKey,label,presentation=false}:Props){
  const identity=JSON.stringify(noteKey),editor=useRef<HTMLDivElement>(null),[value,setValue]=useState(()=>readPersonalNote(noteKey)),[status,setStatus]=useState<'idle'|'saving'|'saved'|'error'>('idle'),[open,setOpen]=useState(false),timer=useRef<number|undefined>(undefined);
  useEffect(()=>{const next=readPersonalNote(noteKey);setValue(next);setStatus('idle');if(editor.current)editor.current.innerHTML=next;return()=>{if(timer.current)clearTimeout(timer.current)}},[identity]);
  useEffect(()=>{if(open&&editor.current)editor.current.innerHTML=value},[open]);
  const change=(next:string)=>{const clean=sanitizeRichNote(next);setValue(clean);setStatus('saving');if(timer.current)clearTimeout(timer.current);const captured={...noteKey};timer.current=window.setTimeout(()=>{try{writePersonalNote(captured,clean);setStatus('saved')}catch{setStatus('error')}},500)};
  const command=(name:string)=>{editor.current?.focus();document.execCommand(name);change(editor.current?.innerHTML??'')};
  const editorView=<div className="personal-notes-editor"><div className="personal-notes-toolbar" role="toolbar" aria-label="Notiz formatieren"><button type="button" onClick={()=>command('bold')}><b>B</b></button><button type="button" onClick={()=>command('italic')}><i>I</i></button><button type="button" onClick={()=>command('underline')}><u>U</u></button><button type="button" onClick={()=>command('insertUnorderedList')}>• Liste</button><button type="button" onClick={()=>command('insertOrderedList')}>1. Liste</button><button type="button" onClick={()=>command('justifyLeft')}>↤</button><button type="button" onClick={()=>command('justifyCenter')}>↔</button><button type="button" onClick={()=>command('undo')}>↶</button><button type="button" onClick={()=>command('redo')}>↷</button></div><div ref={editor} className="personal-notes-richtext" contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" data-placeholder="Nur für mich auf diesem Gerät …" onInput={event=>change(event.currentTarget.innerHTML)} onPaste={event=>{event.preventDefault();document.execCommand('insertText',false,event.clipboardData.getData('text/plain'))}}/><small>{status==='saving'?'Speichert …':status==='saved'?'Gespeichert':status==='error'?'Lokales Speichern fehlgeschlagen':'Lokal gespeichert'}</small></div>;
  if(presentation)return <div className="presentation-notes-entry"><button type="button" className="presentation-notes-button" onClick={()=>setOpen(true)}>📝 {label}</button>{open&&<div className="personal-notes-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="personal-notes-dialog" role="dialog" aria-modal="true" aria-label={label}><header><b>{label}</b><button type="button" onClick={()=>setOpen(false)} aria-label="Schließen">×</button></header>{editorView}</section></div>}</div>;
  return <details className="personal-notes"><summary>{label}</summary>{editorView}</details>;
}
