import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { readPersonalNote, sanitizeRichNote, writePersonalNote, type PersonalNoteKey } from './personalNotes';
import {noteStatusMessage,PERSONAL_NOTE_SAVED_MS,type NoteStatus} from './noteStatus';
type Props={noteKey:PersonalNoteKey;label:string;presentation?:boolean};
export function PersonalNotesPanel({noteKey,label,presentation=false}:Props){
  const identity=JSON.stringify(noteKey),editor=useRef<HTMLDivElement>(null),[value,setValue]=useState(()=>readPersonalNote(noteKey)),[status,setStatus]=useState<NoteStatus>('idle'),[open,setOpen]=useState(false),timer=useRef<number|undefined>(undefined),statusTimer=useRef<number|undefined>(undefined);
  useEffect(()=>{const next=readPersonalNote(noteKey);setValue(next);setStatus('idle');if(editor.current)editor.current.innerHTML=next;return()=>{if(timer.current)clearTimeout(timer.current)}},[identity]);
  useEffect(()=>{if(open&&editor.current)editor.current.innerHTML=value},[open]);
  const change=(next:string)=>{const clean=sanitizeRichNote(next);setValue(clean);setStatus('saving');if(timer.current)clearTimeout(timer.current);if(statusTimer.current)clearTimeout(statusTimer.current);const captured={...noteKey};timer.current=window.setTimeout(()=>{try{writePersonalNote(captured,clean);setStatus('saved');statusTimer.current=window.setTimeout(()=>setStatus('idle'),PERSONAL_NOTE_SAVED_MS)}catch{setStatus('error')}},500)};
  const command=(name:string)=>{editor.current?.focus();document.execCommand(name);change(editor.current?.innerHTML??'')};
  const editorView=<div className="personal-notes-editor"><div className="personal-notes-toolbar" role="toolbar" aria-label="Notiz formatieren"><button type="button" onClick={()=>command('bold')}><b>B</b></button><button type="button" onClick={()=>command('italic')}><i>I</i></button><button type="button" onClick={()=>command('underline')}><u>U</u></button><button type="button" onClick={()=>command('insertUnorderedList')}>Liste</button><button type="button" onClick={()=>command('insertOrderedList')}>1. Liste</button><button type="button" onClick={()=>command('justifyLeft')}>Links</button><button type="button" onClick={()=>command('justifyCenter')}>Zentriert</button><button type="button" title="Rückgängig" aria-label="Rückgängig" onClick={()=>command('undo')}><span className="material-symbols-outlined" aria-hidden="true">undo</span></button><button type="button" title="Wiederholen" aria-label="Wiederholen" onClick={()=>command('redo')}><span className="material-symbols-outlined" aria-hidden="true">redo</span></button></div><div ref={editor} className="personal-notes-richtext" contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" data-placeholder="Nur für mich auf diesem Gerät …" onInput={event=>change(event.currentTarget.innerHTML)} onPaste={event=>{event.preventDefault();document.execCommand('insertText',false,event.clipboardData.getData('text/plain'))}}/><small><span className="material-symbols-outlined" aria-hidden="true">lock</span>{noteStatusMessage(status)}</small></div>;
  if(presentation)return <div className="presentation-notes-entry"><button type="button" className="presentation-notes-button" onClick={()=>setOpen(true)}><span className="material-symbols-outlined" aria-hidden="true">edit_note</span> {label}</button>{open&&createPortal(<div className="personal-notes-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="personal-notes-dialog" role="dialog" aria-modal="true" aria-label={label}><header><b>{label}</b><button type="button" onClick={()=>setOpen(false)} aria-label="Schließen">×</button></header>{editorView}</section></div>,document.body)}</div>;
  return <details className="personal-notes"><summary>{label}</summary>{editorView}</details>;
}
