import {useEffect,useRef,useState} from 'react';
import {searchRadioStations,type RadioStation} from './radioStations';
import type {BackgroundAudioTrack} from './store';
const PAGE_SIZE=10;
export function RadioStationBrowser({add}:{add:(track:BackgroundAudioTrack)=>void}){
 const[query,setQuery]=useState(''),[stations,setStations]=useState<RadioStation[]>([]),[visible,setVisible]=useState(PAGE_SIZE),[busy,setBusy]=useState(false),[error,setError]=useState(''),[active,setActive]=useState<RadioStation|null>(null),[status,setStatus]=useState<'idle'|'loading'|'playing'|'error'>('idle'),[liveTitle,setLiveTitle]=useState('');const audioRef=useRef<HTMLAudioElement|null>(null);
 const search=async()=>{setBusy(true);setError('');setVisible(PAGE_SIZE);try{const found=await searchRadioStations(query);setStations(found);if(!found.length)setError('Keine passenden, erreichbaren HTTPS-Radiosender gefunden.')}catch(reason){setError(`Radiosuche fehlgeschlagen: ${reason instanceof Error?reason.message:String(reason)}. Bitte erneut versuchen.`)}finally{setBusy(false)}};
 useEffect(()=>{if(!active)return;const timer=window.setInterval(()=>{const metadata=navigator.mediaSession?.metadata;setLiveTitle(metadata?.title&&metadata.title!==active.name?metadata.title:'')},1200);return()=>window.clearInterval(timer)},[active]);
 const play=(station:RadioStation)=>{audioRef.current?.pause();setActive(station);setLiveTitle('');setStatus('loading');window.setTimeout(()=>audioRef.current?.play().catch(()=>setStatus('error')),0)};
 return <section className="radio-station-browser"><header><h4>Radiosender</h4><p>Sender suchen, anhören und als Hintergrundaudio hinzufügen.</p></header><div className="radio-search"><span className="radio-query"><input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void search()}}} placeholder="Sender, Ort oder Musikrichtung"/>{query&&<button type="button" aria-label="Suchtext löschen" title="Suchtext löschen" onClick={()=>setQuery('')}><span className="material-symbols-outlined">close</span></button>}</span><button disabled={busy} onClick={()=>void search()}>{busy?'Suchen …':'Suchen'}</button></div>{error&&<p role="alert">{error}</p>}<div className="radio-results">{stations.slice(0,visible).map(station=><article key={station.id}><button className="radio-play" onClick={()=>play(station)} aria-label={`${station.name} abspielen`}><span className="material-symbols-outlined">{active?.id===station.id&&status==='playing'?'pause_circle':'play_circle'}</span></button><span><b>{station.name}</b><small>{[station.country,station.language,station.codec,station.bitrate?`${station.bitrate} kbit/s`:''].filter(Boolean).join(' · ')}</small></span><button onClick={()=>add({assetId:`radio:${station.id}`,name:station.name,url:station.streamUrl,artist:'Online-Radio',format:station.codec||'Stream',status:'ready'})}>Hinzufügen</button></article>)}</div>{stations.length>PAGE_SIZE&&<div className="radio-pagination">{visible<stations.length&&<button onClick={()=>setVisible(value=>Math.min(stations.length,value+PAGE_SIZE))}>Mehr laden</button>}{visible>PAGE_SIZE&&<button onClick={()=>setVisible(PAGE_SIZE)}>Weniger anzeigen</button>}</div>}<audio ref={audioRef} src={active?.streamUrl} preload="none" onLoadStart={()=>setStatus('loading')} onWaiting={()=>setStatus('loading')} onPlaying={()=>setStatus('playing')} onError={()=>setStatus('error')}/>{active&&<footer className={`radio-now-playing ${status}`} aria-live="polite">{active.artworkUrl?<img src={active.artworkUrl} alt=""/>:<span className="material-symbols-outlined">radio</span>}<div><small>{status==='loading'?<>Wird geladen<span className="loading-dots"/></>:status==='error'?'Wiedergabe nicht möglich':'Jetzt live'}</small><b>{liveTitle||active.name}</b>{liveTitle&&<span>{active.name}</span>}</div></footer>}</section>
}
