import {useEffect,useMemo,useState} from 'react';

export interface RewardSettings{enabled:boolean;showPoints:boolean;notifications:boolean;sound:boolean;showProgress:boolean}
export interface RewardEvent{id:string;userId:string;type:string;presentationId:string;serviceItemId?:string;points:number;title:string;description:string;createdAt:string;uniqueKey:string}
const settingsKey='gottesdienstregie.rewards.settings',eventsKey='gottesdienstregie.rewards.events';
export const defaultRewardSettings:RewardSettings={enabled:true,showPoints:true,notifications:true,sound:false,showProgress:true};
export const levelThresholds=[0,50,125,225,350,500,700,950,1250,1600];
export const badges=[
  ['presentationCreated','ERSTE SCHRITTE','Erste Präsentation erstellt.'],['preflightReady','BEREIT','Ersten erfolgreichen Preflight abgeschlossen.'],['firstOnAir','ON AIR','Erste Präsentation live verwendet.'],['eventLinked','VERKNÜPFT','Präsentation mit einer Veranstaltung verknüpft.'],['audioSetup','AUDIO EINGERICHTET','Getrennte Audioausgänge eingerichtet.'],['stageSetup','BÜHNENBLICK','STAGE-Ausgabe eingerichtet.'],['streamSetup','STREAM READY','LIVESTREAM-Ausgabe eingerichtet.'],['templateCreated','ORGANISIERT','Eigene Präsentationsvorlage erstellt.'],['loopReady','LOOP READY','Pre-/Post-Loop vorbereitet.'],['preflightPro','PRE-FLIGHT-PROFI','Zehn Präsentationen einsatzbereit geprüft.']
] as const;
export function getRewardSettings():RewardSettings{try{return{...defaultRewardSettings,...JSON.parse(localStorage.getItem(settingsKey)||'{}')}}catch{return defaultRewardSettings}}
export function setRewardSettings(value:RewardSettings){localStorage.setItem(settingsKey,JSON.stringify(value));dispatchEvent(new CustomEvent('rewards-changed'))}
export function rewardEvents(userId?:string):RewardEvent[]{try{const all=JSON.parse(localStorage.getItem(eventsKey)||'[]') as RewardEvent[];return userId?all.filter(item=>item.userId===userId):all}catch{return[]}}
export function awardReward(input:Omit<RewardEvent,'id'|'createdAt'|'uniqueKey'> & {scope?:string}){const settings=getRewardSettings();if(!settings.enabled)return null;const all=rewardEvents(),uniqueKey=`${input.userId}:${input.type}:${input.scope??input.presentationId}`,existing=all.find(item=>item.uniqueKey===uniqueKey);if(existing)return null;const event:RewardEvent={...input,id:crypto.randomUUID(),createdAt:new Date().toISOString(),uniqueKey};const next=[...all,event].slice(-1000);localStorage.setItem(eventsKey,JSON.stringify(next));dispatchEvent(new CustomEvent('reward-earned',{detail:event}));dispatchEvent(new CustomEvent('rewards-changed'));if(input.type==='preflightReady'&&new Set(next.filter(item=>item.userId===input.userId&&item.type==='preflightReady').map(item=>item.presentationId)).size>=10)awardReward({userId:input.userId,type:'preflightPro',presentationId:'account',scope:'account',points:25,title:'PRE-FLIGHT-PROFI',description:'Zehn unterschiedliche Präsentationen erfolgreich geprüft.'});return event}
export function rewardLevel(points:number){let level=1;for(let index=0;index<levelThresholds.length;index++)if(points>=levelThresholds[index])level=index+1;if(level===levelThresholds.length&&points>=levelThresholds.at(-1)!)level+=Math.floor((points-levelThresholds.at(-1)!)/450);const floor=level<=levelThresholds.length?levelThresholds[level-1]:levelThresholds.at(-1)!+(level-levelThresholds.length)*450,next=level<levelThresholds.length?levelThresholds[level]:floor+450;return{level,floor,next}}
export function RewardSettingsPanel(){const [settings,setSettings]=useState(getRewardSettings);const update=(patch:Partial<RewardSettings>)=>{const next={...settings,...patch};setSettings(next);setRewardSettings(next)};const reset=()=>{if(!confirm('Belohnungsfortschritt wirklich zurücksetzen? Diese Aktion kann nicht rückgängig gemacht werden.'))return;localStorage.removeItem(eventsKey);dispatchEvent(new CustomEvent('rewards-changed'))};return <section className="reward-settings"><h3>Belohnungen</h3><p>Das optionale Belohnungssystem macht Fortschritt sichtbar. Es schaltet keine Funktionen frei und verändert keine Rollen oder Berechtigungen.</p><div className="settings-group">{([['enabled','Belohnungssystem aktivieren'],['showPoints','XP im Profil anzeigen'],['notifications','Erfolgsbenachrichtigungen anzeigen'],['sound','Erfolgsbenachrichtigungen mit Ton'],['showProgress','Fortschritt anzeigen']] as const).map(([key,label])=><label className="setting-check" key={key}><input type="checkbox" checked={settings[key]} onChange={event=>update({[key]:event.target.checked})}/><span><b>{label}</b></span></label>)}<button className="danger-button" onClick={reset}>BELOHNUNGSFORTSCHRITT ZURÜCKSETZEN</button></div></section>}
export function RewardProfile({userId,displayName,close}:{userId:string;displayName:string;close:()=>void}){const [tick,setTick]=useState(0);useEffect(()=>{const change=()=>setTick(value=>value+1);addEventListener('rewards-changed',change);return()=>removeEventListener('rewards-changed',change)},[]);const events=useMemo(()=>rewardEvents(userId),[userId,tick]),xp=events.reduce((sum,item)=>sum+item.points,0),level=rewardLevel(xp),earned=new Set(events.map(item=>item.type));return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&close()}><div className="reward-profile" role="dialog" aria-modal="true"><header><div><small>PROFIL &amp; FORTSCHRITT</small><h2>{displayName.toUpperCase()}</h2></div><button onClick={close} aria-label="Schließen">×</button></header><section className="reward-level"><strong>LEVEL {level.level}</strong><b>{xp} XP</b><div><i style={{width:`${Math.min(100,(xp-level.floor)/(level.next-level.floor)*100)}%`}}/></div><small>{level.next-xp} XP bis zum nächsten Level</small></section><h3>ABZEICHEN</h3><div className="reward-badges">{badges.map(([type,title,description])=><article className={earned.has(type)?'earned':''} key={type}><span>★</span><div><b>{title}</b><small>{description}</small></div></article>)}</div><h3>AKTUELLE ERFOLGE</h3><ol className="reward-events">{events.slice().reverse().slice(0,20).map(item=><li key={item.id}><b>+{item.points} XP · {item.title}</b><small>{new Date(item.createdAt).toLocaleString('de-DE')}</small></li>)}{!events.length&&<li>Noch keine Erfolge. Sie entstehen automatisch bei sinnvoll abgeschlossener Arbeit.</li>}</ol></div></div>}
export function RewardToastHost({onAir}:{onAir:boolean}){const [queue,setQueue]=useState<RewardEvent[]>([]),[current,setCurrent]=useState<RewardEvent|null>(null),[held,setHeld]=useState(0);useEffect(()=>{const earned=(event:Event)=>{const reward=(event as CustomEvent<RewardEvent>).detail;if(onAir)setHeld(value=>value+1);else setQueue(value=>[...value,reward])};addEventListener('reward-earned',earned);return()=>removeEventListener('reward-earned',earned)},[onAir]);useEffect(()=>{if(onAir||current||!queue.length)return;setCurrent(queue[0]);setQueue(value=>value.slice(1))},[onAir,current,queue]);useEffect(()=>{if(!current)return;const timer=setTimeout(()=>setCurrent(null),5200);return()=>clearTimeout(timer)},[current]);useEffect(()=>{if(onAir||!held)return;setQueue(value=>[...value,{id:crypto.randomUUID(),userId:'',type:'summary',presentationId:'',points:0,title:`${held} neue Erfolge`,description:'Während des Gottesdienstes gesammelt',createdAt:new Date().toISOString(),uniqueKey:''}]);setHeld(0)},[onAir,held]);return current&&getRewardSettings().notifications?<aside className="reward-toast"><span>✓</span><div><small>ERFOLG FREIGESCHALTET</small><b>{current.title}</b><p>{current.description}</p>{current.points>0&&<strong>+{current.points} XP</strong>}</div></aside>:null}
