import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { usePreferences } from './preferences';

export type ItemType='content'|'image'|'video'|'videoInput'|'audio'|'song'|'bible'|'web'|'pdf'|'timer'|'countdown'|'announcement'|'slideshow'|'stageMessage'|'quickScreen'|'liveQuiz';
export type ElementType='text'|'image'|'shape'|'line'|'video'|'audio'|'videoInput'|'web'|'qr';
export type SaveState='clean'|'dirty'|'saving'|'saved'|'error';
export type DisplayRole='unused'|'operator'|'main'|'stage'|'notes'|'livestream'|'lobby';
export type TimingMode='manual'|'slide-duration'|'media-duration'|'scheduled';
export type TransitionType='cut'|'fade'|'crossfade'|'dissolve'|'slide'|'wipe'|'zoom'|'blur'|'circle'|'flip'|'push'|'iris'|'curtain'|'cube'|'swing'|'flash'|'scale';
export type TransitionDirection='left'|'right'|'up'|'down';
export type TransitionEasing='standard'|'linear'|'ease-in'|'ease-out'|'ease-in-out';
export interface SlideTransition{type:TransitionType;durationMs:number;direction:TransitionDirection;easing:TransitionEasing;reverseOnPrevious:boolean}
export interface ItemTiming{mode:TimingMode;slideDurationSeconds:number;autoAdvance:boolean;repeat:boolean;shuffle:boolean;mediaDurationSeconds:number;totalDurationSeconds:number}
export interface SlideTiming{durationSeconds?:number}
export interface SlideElement{id:string;type:ElementType;name:string;x:number;y:number;width:number;height:number;rotation:number;opacity:number;locked:boolean;visible:boolean;zIndex:number;properties:Record<string,string|number|boolean>}
export interface Slide{id:string;itemId:string;order:number;enabled:boolean;title:string;body:string;background:string;backgroundImage?:string;backgroundFit?:'cover'|'contain'|'auto'|'100% auto'|'auto 100%';backgroundPositionX?:'left'|'center'|'right';backgroundPositionY?:'top'|'center'|'bottom';backgroundBlur?:number;backgroundRotation?:number;elements:SlideElement[];transition:string;transitionDuration:number;transitionOverride?:SlideTransition|null;notes:string;timing?:SlideTiming}
export interface BackgroundAudioTrack{assetId:string;name:string;url:string;artist?:string;album?:string;durationSeconds?:number;format?:string;size?:number;status?:'ready'|'preparing'|'missing'}
export type AudioContinueUntil='itemEnd'|'sectionEnd'|'playlistEnd'|'stopCue'|'offAir'|'nextSection';
export interface BackgroundAudioConfig{tracks:BackgroundAudioTrack[];autoPlay:boolean;shuffle:boolean;repeat:boolean;continueUntil:AudioContinueUntil;volume:number;fadeInSeconds:number;fadeOutSeconds:number;crossfadeSeconds:number;muted:boolean;startItemId?:string;resumeSectionAfterItem?:boolean;ducking:{enabled:boolean;level:number;attackMs:number;releaseMs:number};restartMode?:'start'|'shuffle'|'resume'}
export interface ServiceItem{id:string;type:ItemType;title:string;section:string;sectionId:string;order:number;enabled:boolean;plannedDuration:number;metadata:Record<string,string|number|boolean>;slides:Slide[];autoAdvance:boolean;repeat:boolean;timing:ItemTiming;transitionDefault?:SlideTransition|null;notes:string;stageDirection:string;createdAt:string;updatedAt:string;groupId?:string;linkedContentId?:string;disabled?:boolean;backgroundAudio?:BackgroundAudioConfig;audioStopCue?:{fadeOutSeconds:number}}
export interface ServiceSection{id:string;title:string;order:number;backgroundAudio?:BackgroundAudioConfig}
export type ChangeCategory='PRÄSENTATION'|'SERVICEITEMS'|'FOLIEN'|'MEDIEN'|'SONGS'|'AUDIO'|'ÜBERGÄNGE'|'VIRTUAL SCREENS'|'SERVICEZEIT'|'VERANSTALTUNG'|'QUICK SCREENS'|'LIVEQUIZ'|'EINSTELLUNGEN';
export type ChangeAction='ERSTELLT'|'BEARBEITET'|'VERSCHOBEN'|'DUPLIZIERT'|'GELÖSCHT'|'WIEDERHERGESTELLT'|'VERKNÜPFT'|'VERKNÜPFUNG GELÖST'|'AUSGEBLENDET'|'EINGEBLENDET'|'IMPORTIERT';
export type HistorySyncStatus='LOCAL'|'PENDING'|'SYNCED'|'ERROR';
export interface EditHistoryEntry{id:string;presentationId:string;revisionId:string;timestamp:string;actor:string;userId:string;userDisplayName:string;deviceId?:string;deviceNameSnapshot?:string;action:string;actionType:ChangeAction;category:ChangeCategory;entityType:string;entityId:string;entityTitle:string;before?:unknown;after?:unknown;source:'desktop'|'ai'|'import'|'remote'|'automation'|'system';transactionId:string;syncStatus:HistorySyncStatus}
export interface RestorePoint{id:string;name:string;createdAt:string;createdBy:string;snapshot:Snapshot}
export interface EventLink{eventKey:string;titleSnapshot?:string;linkedAt?:string}
export interface Snapshot{items:ServiceItem[];sections:ServiceSection[];selectedItemId:string;selectedSlideId:string;title:string;date:string;eventId:string;eventLink?:EventLink;serviceTime:string}
export interface PresentationDocument{presentationId:string;title:string;date:string;createdAt:string;updatedAt:string;archived?:boolean;trashed?:boolean;eventId?:string;eventLink?:EventLink;templateId?:string;serviceTime?:string;serviceTimes?:string[];createdBy?:string;editHistory?:EditHistoryEntry[];restorePoints?:RestorePoint[];transitionDefault?:SlideTransition;sections:ServiceSection[];items:ServiceItem[];selectedItemId?:string;selectedSlideId?:string;previewItemId?:string;previewSlideId?:string}
interface State{
  presentationId:string;title:string;date:string;createdAt:string;updatedAt:string;archived:boolean;trashed:boolean;eventId:string;eventLink?:EventLink;templateId:string;serviceTime:string;createdBy:string;historyUserId:string;historyDisplayName:string;historyDeviceId:string;historyDeviceName:string;editHistory:EditHistoryEntry[];restorePoints:RestorePoint[];transitionDefault:SlideTransition;sections:ServiceSection[];items:ServiceItem[];
  selectedItemId:string;selectedServiceItemIds:string[];selectedSlideId:string;previewItemId:string;previewSlideId:string;liveItemId:string;liveSlideId:string;
  mode:'edit'|'preview';previewLayout:'single'|'grid';activeVirtualScreen:'main'|'livestream'|'stage'|'notes'|'signals';gridSize:number;smartGuides:boolean;marginGuides:boolean;ruleOfThirds:boolean;onAir:boolean;liveTimerPausedSlideId?:string;mainDisplayId?:number;displayRoles:Record<string,DisplayRole>;saveState:SaveState;history:Snapshot[];future:Snapshot[];clipboard?:Slide;selectedElementIds:string[];
  loadDocument:(document:unknown)=>void;newDocument:(title:string,date?:string)=>PresentationDocument;updatePresentation:(patch:Partial<Pick<State,'title'|'date'|'eventId'|'eventLink'|'templateId'|'serviceTime'|'createdBy'|'transitionDefault'>>)=>void;setHistoryActor:(userId:string,displayName:string,deviceId?:string,deviceName?:string)=>void;restoreHistoryEntry:(id:string)=>boolean;createRestorePoint:(name:string)=>void;restoreFromPoint:(id:string)=>boolean;
  select:(itemId:string,slideId?:string)=>void;selectServiceItems:(ids:string[],primary?:string)=>void;selectPreview:(itemId:string,slideId:string)=>void;setMode:(mode:'edit'|'preview')=>void;setPreviewLayout:(layout:'single'|'grid')=>void;setActiveVirtualScreen:(screen:'main'|'livestream'|'stage'|'notes'|'signals')=>void;setGridSize:(n:number)=>void;setGuide:(guide:'smartGuides'|'marginGuides'|'ruleOfThirds',value:boolean)=>void;
  addItem:(type:ItemType,copy?:{title:string;section:string;sectionId?:string;body:string;metadata?:Record<string,string|number|boolean>})=>void;removeItem:(id:string)=>void;removeItems:(ids:string[])=>void;duplicateItem:(id:string)=>void;duplicateItems:(ids:string[])=>void;insertServiceItems:(items:ServiceItem[],afterId:string)=>void;updateItem:(id:string,patch:Partial<ServiceItem>)=>void;setItemsEnabled:(ids:string[],enabled:boolean)=>void;groupItems:(ids:string[])=>void;ungroupItems:(ids:string[])=>void;createLinkedItem:(id:string,sectionId?:string)=>void;moveItemToSection:(id:string,sectionId:string)=>void;reorder:(active:string,over:string)=>void;
  updateSectionAudio:(id:string,config?:BackgroundAudioConfig)=>void;updateItemAudio:(id:string,config?:BackgroundAudioConfig)=>void;toggleAudioStopCue:(id:string)=>void;
  addSlide:()=>void;duplicateSlide:()=>void;copySlide:()=>void;pasteSlide:()=>void;removeSlide:()=>void;toggleSlide:()=>void;moveSlide:(direction:-1|1)=>void;reorderSlides:(active:string,over:string)=>void;
  updateSlide:(patch:Partial<Slide>)=>void;selectElements:(ids:string[])=>void;addElement:(type:ElementType)=>void;addShape:(kind:string,name:string)=>void;updateElement:(id:string,patch:Partial<SlideElement>)=>void;removeElement:(id:string)=>void;removeElements:()=>void;duplicateElements:(ids:string[])=>void;pasteElements:(elements:SlideElement[])=>void;showElementOnAllSlides:(id:string)=>void;toggleElementVisible:(id:string)=>void;toggleElementLocked:(id:string)=>void;moveElementLayer:(id:string,direction:-1|1)=>void;moveElementToFront:(id:string)=>void;moveElementToBack:(id:string)=>void;setMainDisplay:(id?:number)=>void;setDisplayRole:(id:number,role:DisplayRole)=>void;setOnAir:(value:boolean)=>void;goLive:(itemId:string,slideId:string)=>void;nextLive:()=>void;previousLive:()=>void;setLiveTimerPaused:(slideId?:string)=>void;
  undo:()=>void;redo:()=>void;markSaving:()=>void;markSaved:()=>void;markSaveError:()=>void;
}

const uuid=()=>crypto.randomUUID(),iso=()=>new Date().toISOString();
const cloneItem=(source:ServiceItem,title=source.title):ServiceItem=>{const item=structuredClone(source),itemId=uuid(),stamp=iso();return{...item,id:itemId,title,groupId:undefined,linkedContentId:undefined,createdAt:stamp,updatedAt:stamp,slides:item.slides.map(slide=>({...slide,id:uuid(),itemId,elements:slide.elements.map(element=>({...element,id:uuid()}))}))}};
const textDefaults=()=>{const preferences=usePreferences.getState();return{fontFamily:preferences.defaultFont||'Cera Pro',fontSize:preferences.defaultFontSize||72,fontWeight:preferences.defaultFontWeight||600,fontStyle:preferences.defaultFontStyle||'normal'}};
const textElement=(text:string):SlideElement=>({id:uuid(),type:'text',name:'Text',x:210,y:320,width:1500,height:280,rotation:0,opacity:1,locked:false,visible:true,zIndex:1,properties:{text,...textDefaults(),color:'#ffffff',align:'center',verticalAlign:'center',lineHeight:1.15,letterSpacing:0,padding:24}});
export const defaultTransition:SlideTransition={type:'fade',durationMs:500,direction:'left',easing:'standard',reverseOnPrevious:true};
const makeSlide=(itemId:string,title='Neue Folie',body='',background='#3b4652'):Slide=>({id:uuid(),itemId,order:0,enabled:true,title,body,background,elements:[textElement(body)],transition:'fade',transitionDuration:500,transitionOverride:null,notes:'',timing:{}});
const sectionName=(id:string)=>({pre:'VORPROGRAMM',warmup:'WARM-UP',arrival:'WARM-UP',service:'GOTTESDIENST',post:'NACHPROGRAMM'}[id]??'GOTTESDIENST');
const defaultTiming=():ItemTiming=>({mode:'manual',slideDurationSeconds:7,autoAdvance:false,repeat:false,shuffle:false,mediaDurationSeconds:0,totalDurationSeconds:0});
export const createServiceItem=(type:ItemType,options:Partial<ServiceItem>&{title?:string;sectionId?:string;body?:string}={}):ServiceItem=>{const id=options.id??uuid(),stamp=iso(),sectionId=options.sectionId==='arrival'?'warmup':options.sectionId??'service',timing={...defaultTiming(),...options.timing};return{id,type,title:options.title??'Neuer Inhalt',section:sectionName(sectionId),sectionId,order:options.order??0,enabled:options.enabled??true,plannedDuration:options.plannedDuration??0,metadata:options.metadata??{},slides:options.slides??[makeSlide(id,options.title,options.body??'')],autoAdvance:options.autoAdvance??timing.autoAdvance,repeat:options.repeat??timing.repeat,timing,notes:options.notes??'',stageDirection:options.stageDirection??'',createdAt:options.createdAt??stamp,updatedAt:options.updatedAt??stamp,groupId:options.groupId,disabled:options.disabled}};
const makeItem=(type:ItemType,title:string,sectionId='service',body='')=>createServiceItem(type,{title,sectionId,body});
const sections:ServiceSection[]=[{id:'pre',title:'VORPROGRAMM',order:0},{id:'warmup',title:'WARM-UP',order:1},{id:'service',title:'GOTTESDIENST',order:2},{id:'post',title:'NACHPROGRAMM',order:3}];
const welcome=makeItem('content','Willkommen','warmup','Schön, dass du da bist.');welcome.id='welcome';welcome.slides[0]={...welcome.slides[0],id:'welcome-1',itemId:'welcome'};
const song=makeItem('song','Großer Gott, wir loben dich','service','Großer Gott, wir loben dich\nHerr, wir preisen deine Stärke');song.id='song-1';song.slides=[{...song.slides[0],id:'song-1a',itemId:'song-1',title:'Vers 1'},makeSlide('song-1','Vers 2','Alles, was dich preisen kann\nKerubim und Serafinen','#394755')];song.slides[1].id='song-1b';
const sermon=makeItem('content','Predigt','service','Hoffnung, die trägt');sermon.id='sermon';sermon.slides[0]={...sermon.slides[0],id:'sermon-1',itemId:'sermon'};
const initial=[welcome,song,sermon].map((item,order)=>({...item,order,slides:item.slides.map((slide,index)=>({...slide,order:index}))}));
const snap=(state:State):Snapshot=>({items:structuredClone(state.items),sections:structuredClone(state.sections),selectedItemId:state.selectedItemId,selectedSlideId:state.selectedSlideId,title:state.title,date:state.date,eventId:state.eventId,eventLink:state.eventLink?{...state.eventLink}:undefined,serviceTime:state.serviceTime});
const redact=(value:unknown):unknown=>{if(!value||typeof value!=='object')return value;if(Array.isArray(value))return value.map(redact);return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([key,item])=>[/password/i,/token/i,/secret/i,/authorization/i,/api.?key/i].some(pattern=>pattern.test(key))?[key,'••••••••']:[key,redact(item)]))};
const legacyHistory=(entry:any,presentationId:string,index:number):EditHistoryEntry=>({id:String(entry?.id??`legacy-${index}-${entry?.timestamp??iso()}`),presentationId:String(entry?.presentationId??presentationId),revisionId:String(entry?.revisionId??`rev-${index+1}`),timestamp:String(entry?.timestamp??iso()),actor:String(entry?.actor??entry?.userDisplayName??'Unbekannt'),userId:String(entry?.userId??'legacy'),userDisplayName:String(entry?.userDisplayName??entry?.actor??'Unbekannt'),deviceId:entry?.deviceId?String(entry.deviceId):undefined,deviceNameSnapshot:entry?.deviceNameSnapshot?String(entry.deviceNameSnapshot):undefined,action:String(entry?.action??'Präsentation bearbeitet'),actionType:(entry?.actionType??'BEARBEITET') as ChangeAction,category:(entry?.category??'PRÄSENTATION') as ChangeCategory,entityType:String(entry?.entityType??'presentation'),entityId:String(entry?.entityId??presentationId),entityTitle:String(entry?.entityTitle??''),before:redact(entry?.before),after:redact(entry?.after),source:(entry?.source??'desktop') as EditHistoryEntry['source'],transactionId:String(entry?.transactionId??entry?.id??`legacy-${index}`),syncStatus:(entry?.syncStatus??'SYNCED') as HistorySyncStatus});
interface ChangeMeta{action:string;actionType:ChangeAction;category:ChangeCategory;entityType:string;entityId:string;entityTitle:string;before?:unknown;after?:unknown;coalesce?:boolean}
const describeChange=(state:State,patch:Partial<State>):ChangeMeta=>{
  if(typeof patch.title==='string'&&patch.title!==state.title)return{action:'Präsentationstitel geändert',actionType:'BEARBEITET',category:'PRÄSENTATION',entityType:'presentation',entityId:state.presentationId,entityTitle:patch.title,before:state.title,after:patch.title};
  if(patch.eventLink?.eventKey!==state.eventLink?.eventKey)return{action:patch.eventLink?.eventKey?'Veranstaltung verknüpft':'Veranstaltungsverknüpfung gelöst',actionType:patch.eventLink?.eventKey?'VERKNÜPFT':'VERKNÜPFUNG GELÖST',category:'VERANSTALTUNG',entityType:'eventLink',entityId:patch.eventLink?.eventKey??state.eventLink?.eventKey??'',entityTitle:patch.eventLink?.titleSnapshot??state.eventLink?.titleSnapshot??'Veranstaltung',before:state.eventLink,after:patch.eventLink};
  if(typeof patch.serviceTime==='string'&&patch.serviceTime!==state.serviceTime)return{action:'Servicezeit geändert',actionType:'BEARBEITET',category:'SERVICEZEIT',entityType:'serviceTime',entityId:state.presentationId,entityTitle:'Servicezeit',before:state.serviceTime,after:patch.serviceTime};
  if(patch.sections)return{action:'Ablaufabschnitt geändert',actionType:'BEARBEITET',category:'PRÄSENTATION',entityType:'section',entityId:'sections',entityTitle:'Ablauf',before:state.sections,after:patch.sections};
  if(patch.items){const oldIds=new Set(state.items.map(item=>item.id)),newIds=new Set(patch.items.map(item=>item.id)),added=patch.items.filter(item=>!oldIds.has(item.id)),removed=state.items.filter(item=>!newIds.has(item.id));if(added.length)return{action:added.length===1?`Element „${added[0].title}“ hinzugefügt`:`${added.length} Elemente hinzugefügt`,actionType:'ERSTELLT',category:'SERVICEITEMS',entityType:'serviceItem',entityId:added[0].id,entityTitle:added[0].title,after:added};if(removed.length)return{action:removed.length===1?`Element „${removed[0].title}“ gelöscht`:`${removed.length} Elemente gelöscht`,actionType:'GELÖSCHT',category:'SERVICEITEMS',entityType:'serviceItem',entityId:removed[0].id,entityTitle:removed[0].title,before:removed};const renamed=patch.items.find(item=>state.items.some(previous=>previous.id===item.id&&previous.title!==item.title));if(renamed){const previous=state.items.find(item=>item.id===renamed.id)!;return{action:`Element „${renamed.title}“ umbenannt`,actionType:'BEARBEITET',category:'SERVICEITEMS',entityType:'serviceItem',entityId:renamed.id,entityTitle:renamed.title,before:previous.title,after:renamed.title}}const beforeSlides=state.items.reduce((sum,item)=>sum+item.slides.length,0),afterSlides=patch.items.reduce((sum,item)=>sum+item.slides.length,0);if(afterSlides!==beforeSlides)return{action:afterSlides>beforeSlides?'Folie hinzugefügt':'Folie gelöscht',actionType:afterSlides>beforeSlides?'ERSTELLT':'GELÖSCHT',category:'FOLIEN',entityType:'slide',entityId:state.selectedSlideId,entityTitle:'Folie',before:beforeSlides,after:afterSlides};return{action:'Folieninhalt oder Gestaltung geändert',actionType:'BEARBEITET',category:'FOLIEN',entityType:'slide',entityId:state.selectedSlideId,entityTitle:state.items.flatMap(item=>item.slides).find(slide=>slide.id===state.selectedSlideId)?.title??'Folie',before:state.items,after:patch.items,coalesce:true}}
  return{action:'Präsentationseinstellungen geändert',actionType:'BEARBEITET',category:'EINSTELLUNGEN',entityType:'presentation',entityId:state.presentationId,entityTitle:state.title,before:undefined,after:patch};
};
const changed=(state:State,patch:Partial<State>,override?:Partial<ChangeMeta>)=>{const timestamp=iso(),meta={...describeChange(state,patch),...override} as ChangeMeta,previous=state.editHistory.at(-1),same=meta.coalesce&&previous?.entityId===meta.entityId&&previous.actionType===meta.actionType&&Date.parse(timestamp)-Date.parse(previous.timestamp)<1500,revision=Number(String(previous?.revisionId??'rev-0').replace(/\D/g,''))||0,entry:EditHistoryEntry={id:uuid(),presentationId:state.presentationId,revisionId:`rev-${same?revision:revision+1}`,timestamp,actor:state.historyDisplayName||state.createdBy||'Unbekannt',userId:state.historyUserId||'local',userDisplayName:state.historyDisplayName||state.createdBy||'Unbekannt',deviceId:state.historyDeviceId||undefined,deviceNameSnapshot:state.historyDeviceName||undefined,action:meta.action,actionType:meta.actionType,category:meta.category,entityType:meta.entityType,entityId:meta.entityId,entityTitle:meta.entityTitle,before:redact(same?previous?.before:meta.before),after:redact(meta.after),source:'desktop',transactionId:same?previous!.transactionId:uuid(),syncStatus:'PENDING'},editHistory=same?[...state.editHistory.slice(0,-1),entry]:[...state.editHistory,entry].slice(-1000);return{...patch,history:[...state.history.slice(-49),snap(state)],future:[],editHistory,saveState:'dirty' as SaveState,updatedAt:timestamp}};
const activeSlides=(state:State)=>state.items.filter(item=>item.enabled&&!item.disabled).flatMap(item=>item.slides.filter(slide=>slide.enabled).map(slide=>({itemId:item.id,slideId:slide.id})));
export const itemDurationSeconds=(item:ServiceItem)=>{const active=item.slides.filter(slide=>slide.enabled),slideTotal=active.reduce((sum,slide)=>sum+(slide.timing?.durationSeconds??item.timing?.slideDurationSeconds??item.plannedDuration??0),0);return Math.max(0,Math.round(item.timing?.mediaDurationSeconds||item.timing?.totalDurationSeconds||slideTotal||item.plannedDuration||0))};
export const formatDuration=(seconds:number)=>{const value=Math.max(0,Math.round(seconds));if(value>0&&value<60)return `${value}s`;const minutes=Math.floor(value/60),rest=value%60;return `${minutes}:${String(rest).padStart(2,'0')}`};
export const parseDuration=(value:string)=>{const normalized=value.trim().toLowerCase(),secondsOnly=normalized.match(/^(\d+)\s*s$/);if(secondsOnly){const seconds=Number(secondsOnly[1]);return seconds>=1?Math.round(seconds):null}const parts=normalized.split(':').map(Number);if(parts.some(Number.isNaN))return null;const seconds=parts.length===1?parts[0]:parts.length===2?parts[0]*60+parts[1]:parts[0]*3600+parts[1]*60+parts[2];return seconds>=1?Math.round(seconds):null};
const normalizeTransition=(value:any,legacyType?:string,legacyDuration?:number):SlideTransition|null=>{if(value===null)return null;const type=['cut','fade','crossfade','dissolve','slide','wipe','zoom','blur','circle','flip','push','iris','curtain','cube','swing','flash','scale'].includes(value?.type)?value.type:(legacyType==='none'?'cut':legacyType==='fade'?'fade':undefined);if(!type)return null;return{type,durationMs:Math.max(100,Math.min(5000,Number(value?.durationMs??legacyDuration??500))),direction:['left','right','up','down'].includes(value?.direction)?value.direction:'left',easing:['standard','linear','ease-in','ease-out','ease-in-out'].includes(value?.easing)?value.easing:'standard',reverseOnPrevious:value?.reverseOnPrevious!==false}};
const normalizeItem=(raw:any,index:number):ServiceItem=>{const type:ItemType=raw?.type==='media'?'image':raw?.type??'content',legacySection=raw?.sectionId??(raw?.section==='ANKOMMEN'?'warmup':raw?.section==='VORPROGRAMM'?'pre':raw?.section==='NACHPROGRAMM'?'post':'service'),sectionId=legacySection==='arrival'?'warmup':legacySection,base=makeItem(type,raw?.title??'Neuer Inhalt',sectionId),timing={...base.timing,...raw?.timing,autoAdvance:raw?.timing?.autoAdvance??raw?.autoAdvance??false,repeat:raw?.timing?.repeat??raw?.repeat??false};return{...base,...raw,type,sectionId,section:sectionName(sectionId),timing,transitionDefault:normalizeTransition(raw?.transitionDefault),autoAdvance:timing.autoAdvance,repeat:timing.repeat,createdAt:raw?.createdAt??base.createdAt,updatedAt:raw?.updatedAt??base.updatedAt,order:raw?.order??index,enabled:raw?.enabled??!raw?.disabled,slides:(raw?.slides?.length?raw.slides:base.slides).map((slide:any,slideIndex:number)=>({...makeSlide(raw?.id??base.id,slide?.title,slide?.body,slide?.background),...slide,transitionOverride:slide?.transitionOverride===null?null:normalizeTransition(slide?.transitionOverride,slide?.transition,slide?.transitionDuration),timing:slide?.timing??{},itemId:raw?.id??base.id,order:slide?.order??slideIndex,enabled:slide?.enabled??true}))}};

export function blankPresentationDocument(title='Neue Präsentation',date=new Date().toISOString().slice(0,10)):PresentationDocument{const stamp=iso();return{presentationId:uuid(),title:title.slice(0,500),date,createdAt:stamp,updatedAt:stamp,archived:false,trashed:false,eventId:'',eventLink:undefined,templateId:'',serviceTime:'10:30',createdBy:'',editHistory:[],restorePoints:[],transitionDefault:{...defaultTransition},sections:structuredClone(sections),items:[]}}

export const usePresentation=create<State>()(persist((set,get)=>({
  presentationId:'',title:'',date:new Date().toISOString().slice(0,10),createdAt:iso(),updatedAt:iso(),archived:false,trashed:false,eventId:'',eventLink:undefined,templateId:'',serviceTime:'',createdBy:'',historyUserId:'',historyDisplayName:'',historyDeviceId:'',historyDeviceName:'',editHistory:[],restorePoints:[],transitionDefault:{...defaultTransition},sections,items:[],
  selectedItemId:'',selectedServiceItemIds:[],selectedSlideId:'',previewItemId:'',previewSlideId:'',liveItemId:'',liveSlideId:'',mode:'edit',previewLayout:'single',activeVirtualScreen:'main',gridSize:200,smartGuides:true,marginGuides:false,ruleOfThirds:false,onAir:false,liveTimerPausedSlideId:undefined,displayRoles:{},saveState:'saved',history:[],future:[],selectedElementIds:[],
  loadDocument:raw=>{const document=raw as any,items=(document?.items??[]).map(normalizeItem),first=items[0],firstSlide=first?.slides[0],legacyTime=Array.isArray(document?.serviceTimes)?document.serviceTimes[0]:'',legacyEvent=String(document?.eventId??''),presentationId=String(document?.presentationId??uuid()),selectedItemId=document?.selectedItemId&&items.some((item:ServiceItem)=>item.id===document.selectedItemId)?document.selectedItemId:first?.id??'';set({presentationId,title:String(document?.title??'Unbenannte Präsentation').slice(0,500),date:String(document?.date??new Date().toISOString().slice(0,10)),createdAt:String(document?.createdAt??iso()),updatedAt:String(document?.updatedAt??iso()),archived:document?.archived===true,trashed:document?.trashed===true,eventId:legacyEvent,eventLink:document?.eventLink?.eventKey?document.eventLink:(legacyEvent?{eventKey:legacyEvent}:undefined),templateId:String(document?.templateId??''),serviceTime:String(document?.serviceTime??legacyTime??''),createdBy:String(document?.createdBy??''),editHistory:Array.isArray(document?.editHistory)?document.editHistory.map((entry:any,index:number)=>legacyHistory(entry,presentationId,index)).slice(-1000):[],restorePoints:Array.isArray(document?.restorePoints)?document.restorePoints.slice(-50):[],transitionDefault:normalizeTransition(document?.transitionDefault)??{...defaultTransition},sections:Array.isArray(document?.sections)&&document.sections.length?document.sections:sections,items,selectedItemId,selectedServiceItemIds:selectedItemId?[selectedItemId]:[],selectedSlideId:document?.selectedSlideId&&items.some((item:ServiceItem)=>item.slides.some(slide=>slide.id===document.selectedSlideId))?document.selectedSlideId:firstSlide?.id??'',previewItemId:document?.previewItemId??first?.id??'',previewSlideId:document?.previewSlideId??firstSlide?.id??'',liveItemId:'',liveSlideId:'',onAir:false,saveState:'saved',history:[],future:[],selectedElementIds:[]})},
  newDocument:(title,date)=>{const document=blankPresentationDocument(title,date);get().loadDocument(document);return document},
  updatePresentation:patch=>set(state=>changed(state,{...patch,...(typeof patch.title==='string'?{title:patch.title.slice(0,500)}:{})})),
  setHistoryActor:(historyUserId,historyDisplayName,historyDeviceId='',historyDeviceName='')=>set({historyUserId,historyDisplayName,historyDeviceId,historyDeviceName}),
  restoreHistoryEntry:id=>{let restored=false;set(state=>{const entry=state.editHistory.find(item=>item.id===id);if(!entry)return state;let patch:Partial<State>|null=null;if(entry.category==='SERVICEZEIT'&&typeof entry.before==='string')patch={serviceTime:entry.before};else if(entry.entityType==='presentation'&&typeof entry.before==='string')patch={title:entry.before};else if(entry.entityType==='serviceItem'){const before=Array.isArray(entry.before)?entry.before[0] as ServiceItem:undefined,after=Array.isArray(entry.after)?entry.after[0] as ServiceItem:undefined;if(entry.actionType==='GELÖSCHT'&&before)patch={items:[...state.items,before].map((item,order)=>({...item,order}))};else if(entry.actionType==='ERSTELLT'&&after)patch={items:state.items.filter(item=>item.id!==after.id).map((item,order)=>({...item,order}))}}if(!patch)return state;restored=true;return changed(state,patch,{action:`Stand von ${new Date(entry.timestamp).toLocaleString('de-DE')} wiederhergestellt`,actionType:'WIEDERHERGESTELLT',category:entry.category,entityType:entry.entityType,entityId:entry.entityId,entityTitle:entry.entityTitle,before:entry.after,after:entry.before})});return restored},
  createRestorePoint:name=>set(state=>{const point:RestorePoint={id:uuid(),name:name.trim().slice(0,80)||'Wiederherstellungspunkt',createdAt:iso(),createdBy:state.historyDisplayName||state.createdBy||'Unbekannt',snapshot:snap(state)};return{restorePoints:[...state.restorePoints,point].slice(-50),saveState:'dirty'}}),
  restoreFromPoint:id=>{let restored=false;set(state=>{const point=state.restorePoints.find(item=>item.id===id);if(!point)return state;restored=true;return changed(state,structuredClone(point.snapshot),{action:`Wiederherstellungspunkt „${point.name}“ wiederhergestellt`,actionType:'WIEDERHERGESTELLT',category:'PRÄSENTATION',entityType:'presentation',entityId:state.presentationId,entityTitle:state.title,before:snap(state),after:point.snapshot})});return restored},
  select:(selectedItemId,slideId)=>{const state=get(),item=state.items.find(entry=>entry.id===selectedItemId),selectedSlideId=slideId??item?.slides[0]?.id??'';set(state.mode==='preview'?{selectedItemId,selectedServiceItemIds:[selectedItemId],selectedSlideId,previewItemId:selectedItemId,previewSlideId:selectedSlideId}:{selectedItemId,selectedServiceItemIds:[selectedItemId],selectedSlideId})},
  selectServiceItems:(ids,primary)=>set(state=>{const selectedServiceItemIds=[...new Set(ids)].filter(id=>state.items.some(item=>item.id===id)),selectedItemId=primary&&selectedServiceItemIds.includes(primary)?primary:selectedServiceItemIds.at(-1)??'',item=state.items.find(entry=>entry.id===selectedItemId);return{selectedServiceItemIds,selectedItemId,selectedSlideId:item?.slides[0]?.id??''}}),selectPreview:(previewItemId,previewSlideId)=>set({previewItemId,previewSlideId,selectedItemId:previewItemId,selectedServiceItemIds:[previewItemId],selectedSlideId:previewSlideId}),
  setMode:mode=>set(state=>mode==='preview'?{mode,previewItemId:state.selectedItemId||state.previewItemId,previewSlideId:state.selectedSlideId||state.previewSlideId}:{mode,selectedItemId:state.previewItemId||state.selectedItemId,selectedSlideId:state.previewSlideId||state.selectedSlideId}),setPreviewLayout:previewLayout=>set({previewLayout}),setActiveVirtualScreen:activeVirtualScreen=>set({activeVirtualScreen}),setGridSize:gridSize=>set({gridSize:Math.max(160,Math.min(440,Math.round((gridSize-160)/40)*40+160))}),setGuide:(guide,value)=>set({[guide]:value}),
  addItem:(type,copy)=>set(state=>{const names:Record<ItemType,string>={content:'Neuer Inhalt',image:'Neues Bild',video:'Neues Video',videoInput:'Neuer Videoeingang',audio:'Neues Audio',song:'Neuer Song',bible:'Bibelstelle',web:'Neue Webseite',pdf:'Neues PDF',timer:'Neuer Timer',countdown:'Neuer Countdown',announcement:'Neue Ankündigung',slideshow:'Neue Slideshow',stageMessage:'Neue Stage-Nachricht',quickScreen:'Neue Schnellanzeige',liveQuiz:'Neues LiveQuiz'},rawSection=copy?.sectionId??(copy?.section==='ANKOMMEN'?'warmup':copy?.section==='VORPROGRAMM'?'pre':copy?.section==='NACHPROGRAMM'?'post':'service'),sectionId=rawSection==='arrival'?'warmup':rawSection,item=createServiceItem(type,{title:copy?.title??names[type],sectionId,body:copy?.body??'',metadata:copy?.metadata??{},order:state.items.length});return changed(state,{items:[...state.items,item],selectedItemId:item.id,selectedSlideId:item.slides[0].id,selectedElementIds:[]})}),
  removeItem:id=>get().removeItems([id]),
  removeItems:ids=>set(state=>{const remove=new Set(ids),items=state.items.filter(item=>!remove.has(item.id)),first=items[0];return items.length===state.items.length?state:changed(state,{items,selectedItemId:first?.id??'',selectedServiceItemIds:first?[first.id]:[],selectedSlideId:first?.slides[0]?.id??''})}),
  duplicateItem:id=>get().duplicateItems([id]),
  duplicateItems:ids=>set(state=>{const chosen=new Set(ids),items:ServiceItem[]=[];const clones:ServiceItem[]=[];for(const source of state.items){items.push(source);if(chosen.has(source.id)){const clone=cloneItem(source,`${source.title} – Kopie`);clones.push(clone);items.push(clone)}}if(!clones.length)return state;const last=clones.at(-1)!;return changed(state,{items:items.map((entry,order)=>({...entry,order})),selectedItemId:last.id,selectedServiceItemIds:clones.map(item=>item.id),selectedSlideId:last.slides[0]?.id??''})}),
  insertServiceItems:(sources,afterId)=>set(state=>{if(!sources.length)return state;const clones=sources.map(source=>cloneItem(source)),items=[...state.items],index=Math.max(-1,items.findIndex(item=>item.id===afterId));items.splice(index+1,0,...clones);const last=clones.at(-1)!;return changed(state,{items:items.map((entry,order)=>({...entry,order})),selectedItemId:last.id,selectedServiceItemIds:clones.map(item=>item.id),selectedSlideId:last.slides[0]?.id??''})}),
  updateItem:(id,patch)=>set(state=>{const source=state.items.find(item=>item.id===id),linkedContentId=source?.linkedContentId;return changed(state,{items:state.items.map(item=>item.id===id||linkedContentId&&item.linkedContentId===linkedContentId?{...item,...patch,id:item.id,sectionId:item.sectionId,section:item.section,order:item.order,groupId:item.groupId,linkedContentId,updatedAt:iso()}:item)})}),
  setItemsEnabled:(ids,enabled)=>set(state=>{const selected=new Set(ids);return changed(state,{items:state.items.map(item=>selected.has(item.id)?{...item,enabled,disabled:!enabled,updatedAt:iso()}:item)})}),
  groupItems:ids=>set(state=>{const selected=new Set(ids),chosen=state.items.filter(item=>selected.has(item.id));if(chosen.length<2||new Set(chosen.map(item=>item.sectionId)).size!==1)return state;const groupId=uuid();return changed(state,{items:state.items.map(item=>selected.has(item.id)?{...item,groupId,metadata:{...item.metadata,groupTitle:'GRUPPE'},updatedAt:iso()}:item)})}),
  ungroupItems:ids=>set(state=>{const groups=new Set(state.items.filter(item=>ids.includes(item.id)).map(item=>item.groupId).filter(Boolean));if(!groups.size)return state;return changed(state,{items:state.items.map(item=>item.groupId&&groups.has(item.groupId)?{...item,groupId:undefined,updatedAt:iso()}:item)})}),
  createLinkedItem:(id,targetSectionId)=>set(state=>{const source=state.items.find(item=>item.id===id);if(!source)return state;const linkedContentId=source.linkedContentId??uuid(),clone={...cloneItem(source),linkedContentId,sectionId:targetSectionId??source.sectionId,section:sectionName(targetSectionId??source.sectionId)},items=state.items.map(item=>item.id===source.id?{...item,linkedContentId}:item);const sourceIndex=items.findIndex(item=>item.id===source.id),insertAt=targetSectionId?items.reduce((last,item,index)=>item.sectionId===targetSectionId?index:last,-1):sourceIndex;items.splice(insertAt+1,0,clone);return changed(state,{items:items.map((item,order)=>({...item,order})),selectedItemId:clone.id,selectedServiceItemIds:[clone.id],selectedSlideId:clone.slides[0]?.id??''})}),
  updateSectionAudio:(id,backgroundAudio)=>set(state=>changed(state,{sections:state.sections.map(section=>section.id===id?{...section,backgroundAudio}:section)})),
  updateItemAudio:(id,backgroundAudio)=>set(state=>changed(state,{items:state.items.map(item=>item.id===id?{...item,backgroundAudio,updatedAt:iso()}:item)})),
  toggleAudioStopCue:id=>set(state=>changed(state,{items:state.items.map(item=>item.id===id?{...item,audioStopCue:item.audioStopCue?undefined:{fadeOutSeconds:2.5},updatedAt:iso()}:item)})),
  moveItemToSection:(id,sectionId)=>set(state=>changed(state,{items:state.items.map(item=>item.id===id?{...item,sectionId,section:sectionName(sectionId),updatedAt:iso()}:item)})),
  reorder:(active,over)=>set(state=>{const source=state.items.find(item=>item.id===active),to=state.items.findIndex(item=>item.id===over);if(!source||to<0)return state;const moving=source.groupId?state.items.filter(item=>item.groupId===source.groupId):[source],ids=new Set(moving.map(item=>item.id)),items=state.items.filter(item=>!ids.has(item.id)),target=Math.min(items.length,Math.max(0,items.findIndex(item=>item.id===over)+(to>state.items.findIndex(item=>item.id===active)?1:0)));items.splice(target,0,...moving);return changed(state,{items:items.map((item,order)=>({...item,order}))})}),
  addSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId),slide=makeSlide(items[itemIndex].id);slides.splice(index<0?slides.length:index+1,0,slide);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:slide.id})}),
  duplicateSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId);if(index<0)return state;const clone={...structuredClone(slides[index]),id:uuid(),elements:slides[index].elements.map(element=>({...structuredClone(element),id:uuid()}))};slides.splice(index+1,0,clone);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:clone.id})}),
  copySlide:()=>{const state=get(),slide=state.items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(slide)set({clipboard:structuredClone(slide)})},
  pasteSlide:()=>set(state=>{if(!state.clipboard)return state;const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),clone={...structuredClone(state.clipboard),id:uuid(),itemId:items[itemIndex].id,elements:state.clipboard.elements.map(element=>({...structuredClone(element),id:uuid()}))};items[itemIndex].slides.push(clone);items[itemIndex].slides=items[itemIndex].slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:clone.id})}),
  removeSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId);if(index<0||slides.length<=1)return state;slides.splice(index,1);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:slides[Math.min(index,slides.length-1)].id})}),
  toggleSlide:()=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,enabled:!slide.enabled}:slide)}))})),
  moveSlide:direction=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId),index=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===state.selectedSlideId)??-1,target=index+direction;if(itemIndex<0||index<0||target<0||target>=state.items[itemIndex].slides.length)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides;[slides[index],slides[target]]=[slides[target],slides[index]];items[itemIndex].slides=slides.map((slide,order)=>({...slide,order}));return changed(state,{items})}),
  reorderSlides:(active,over)=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId),from=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===active)??-1,to=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===over)??-1;if(itemIndex<0||from<0||to<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,[moved]=slides.splice(from,1);slides.splice(to,0,moved);items[itemIndex].slides=slides.map((slide,order)=>({...slide,order}));return changed(state,{items})}),
  updateSlide:patch=>set(state=>{const sourceItem=state.items.find(item=>item.slides.some(slide=>slide.id===state.selectedSlideId)),sourceSlide=sourceItem?.slides.find(slide=>slide.id===state.selectedSlideId),linked=sourceItem?.linkedContentId;return changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>{const target=slide.id===state.selectedSlideId||Boolean(linked&&item.linkedContentId===linked&&slide.order===sourceSlide?.order);if(!target)return slide;return{...slide,...patch,id:slide.id,itemId:item.id,elements:patch.body!==undefined?slide.elements.map((element,index)=>index===0&&element.type==='text'?{...element,properties:{...element.properties,text:patch.body!}}:element):patch.elements??slide.elements}})}))})}),
  selectElements:selectedElementIds=>set({selectedElementIds}),
  addElement:type=>set(state=>{const element:SlideElement={id:uuid(),type,name:type==='text'?'Text':type==='shape'?'Rechteck':type==='image'?'Bild':type==='video'?'Video':type==='audio'?'Audio':type==='web'?'Webseite':type==='qr'?'QR-Code':'Linie',x:520,y:300,width:type==='line'?800:640,height:type==='line'?8:260,rotation:0,opacity:1,locked:false,visible:true,zIndex:99,properties:type==='text'?{text:'Neuer Text',...textDefaults(),color:'#ffffff',align:'center',verticalAlign:'center',lineHeight:1.15,padding:16}:type==='shape'?{shapeKind:'rectangle',fill:'#68aab5',stroke:'#ffffff',strokeWidth:0,radius:0}:type==='line'?{fill:'#ffffff'}:{src:'',fit:'cover'}};const items=state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:[...slide.elements,element].map((entry,index)=>({...entry,zIndex:index+1}))}:slide)}));return changed(state,{items,selectedElementIds:[element.id]})}),
  addShape:(kind,name)=>set(state=>{const slideExists=state.items.some(item=>item.slides.some(slide=>slide.id===state.selectedSlideId));if(!slideExists)return state;const element:SlideElement={id:uuid(),type:'shape',name,x:600,y:300,width:620,height:360,rotation:0,opacity:1,locked:false,visible:true,zIndex:99,properties:{shapeKind:kind,fill:'#68aab5',stroke:'#ffffff',strokeWidth:0,radius:42}};const items=state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:[...slide.elements,element].map((entry,index)=>({...entry,zIndex:index+1}))}:slide)}));return changed(state,{items,selectedElementIds:[element.id]},{action:`2D-Objekt „${name}“ hinzugefügt`,actionType:'ERSTELLT',category:'FOLIEN',entityType:'slideElement',entityId:element.id,entityTitle:name,after:element})}),
  updateElement:(id,patch)=>set(state=>{const sourceItem=state.items.find(item=>item.slides.some(slide=>slide.id===state.selectedSlideId)),sourceSlide=sourceItem?.slides.find(slide=>slide.id===state.selectedSlideId),sourceElement=sourceSlide?.elements.find(element=>element.id===id),elementIndex=sourceSlide?.elements.findIndex(element=>element.id===id)??-1,linked=sourceItem?.linkedContentId;return changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>{const targetSlide=slide.id===state.selectedSlideId||Boolean(linked&&item.linkedContentId===linked&&slide.order===sourceSlide?.order);if(!targetSlide)return slide;return{...slide,elements:slide.elements.map((element,index)=>element.id===id||linked&&index===elementIndex&&element.type===sourceElement?.type?{...element,...patch,id:element.id}:element)}})}))})}),
  duplicateElements:ids=>set(state=>{const selected=new Set(ids),items=structuredClone(state.items),slide=items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(!slide)return state;const source=slide.elements.filter(element=>selected.has(element.id));if(!source.length)return state;const clones=source.map(element=>({...structuredClone(element),id:uuid(),x:Math.min(1920-element.width,element.x+32),y:Math.min(1080-element.height,element.y+32),zIndex:slide.elements.length+1}));slide.elements=[...slide.elements,...clones].map((element,index)=>({...element,zIndex:index+1}));return changed(state,{items,selectedElementIds:clones.map(element=>element.id)},{action:clones.length===1?`Element „${clones[0].name}“ dupliziert`:`${clones.length} Elemente dupliziert`,actionType:'DUPLIZIERT',category:'FOLIEN',entityType:'slideElement',entityId:clones[0].id,entityTitle:clones[0].name,after:clones})}),
  pasteElements:elements=>set(state=>{const items=structuredClone(state.items),slide=items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(!slide||!elements.length)return state;const clones=elements.map(element=>({...structuredClone(element),id:uuid(),x:Math.min(1920-element.width,element.x+48),y:Math.min(1080-element.height,element.y+48),zIndex:slide.elements.length+1}));slide.elements=[...slide.elements,...clones].map((element,index)=>({...element,zIndex:index+1}));return changed(state,{items,selectedElementIds:clones.map(element=>element.id)},{action:clones.length===1?`Element „${clones[0].name}“ eingefügt`:`${clones.length} Elemente eingefügt`,actionType:'ERSTELLT',category:'FOLIEN',entityType:'slideElement',entityId:clones[0].id,entityTitle:clones[0].name,after:clones})}),
  showElementOnAllSlides:id=>set(state=>{const sourceItem=state.items.find(item=>item.slides.some(slide=>slide.id===state.selectedSlideId)),sourceSlide=sourceItem?.slides.find(slide=>slide.id===state.selectedSlideId),source=sourceSlide?.elements.find(element=>element.id===id);if(!source||!sourceItem)return state;const items=structuredClone(state.items),created:SlideElement[]=[];const targetItem=items.find(item=>item.id===sourceItem.id);for(const slide of targetItem?.slides??[]){if(slide.id===sourceSlide?.id||slide.elements.some(element=>element.properties.sourceElementId===id))continue;const clone={...structuredClone(source),id:uuid(),properties:{...source.properties,sourceElementId:id}};slide.elements=[...slide.elements,clone].map((element,index)=>({...element,zIndex:index+1}));created.push(clone)}return created.length?changed(state,{items,selectedElementIds:[id]},{action:`Element „${source.name}“ auf ${created.length+1} Folien angezeigt`,actionType:'ERSTELLT',category:'FOLIEN',entityType:'slideElement',entityId:id,entityTitle:source.name,after:created}):state}),
  removeElement:id=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.filter(element=>element.id!==id)}:slide)})),selectedElementIds:state.selectedElementIds.filter(elementId=>elementId!==id)})),
  removeElements:()=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.filter(element=>!state.selectedElementIds.includes(element.id))}:slide)})),selectedElementIds:[]})),
  toggleElementVisible:id=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.map(element=>element.id===id?{...element,visible:!element.visible}:element)}:slide)}))})),
  toggleElementLocked:id=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.map(element=>element.id===id?{...element,locked:!element.locked}:element)}:slide)}))})),
  moveElementLayer:(id,direction)=>set(state=>{const items=structuredClone(state.items),slide=items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(!slide)return state;const ordered=[...slide.elements].sort((a,b)=>a.zIndex-b.zIndex),index=ordered.findIndex(element=>element.id===id),target=index+direction;if(index<0||target<0||target>=ordered.length)return state;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];slide.elements=ordered.map((element,zIndex)=>({...element,zIndex:zIndex+1}));return changed(state,{items})}),
  moveElementToFront:id=>set(state=>{const items=structuredClone(state.items),slide=items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(!slide)return state;const element=slide.elements.find(entry=>entry.id===id);if(!element)return state;slide.elements=[...slide.elements.filter(entry=>entry.id!==id),element].map((entry,index)=>({...entry,zIndex:index+1}));return changed(state,{items})}),
  moveElementToBack:id=>set(state=>{const items=structuredClone(state.items),slide=items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(!slide)return state;const element=slide.elements.find(entry=>entry.id===id);if(!element)return state;slide.elements=[element,...slide.elements.filter(entry=>entry.id!==id)].map((entry,index)=>({...entry,zIndex:index+1}));return changed(state,{items})}),
  setMainDisplay:mainDisplayId=>set(state=>{const displayRoles={...state.displayRoles};for(const key of Object.keys(displayRoles))if(displayRoles[key]==='main')delete displayRoles[key];if(mainDisplayId!==undefined)displayRoles[String(mainDisplayId)]='main';return{mainDisplayId,displayRoles}}),
  setDisplayRole:(id,role)=>set(state=>{const displayRoles={...state.displayRoles};if(role!=='unused')for(const key of Object.keys(displayRoles))if(displayRoles[key]===role)delete displayRoles[key];if(role==='unused')delete displayRoles[String(id)];else displayRoles[String(id)]=role;const mainEntry=Object.entries(displayRoles).find(([,value])=>value==='main');return{displayRoles,mainDisplayId:mainEntry?Number(mainEntry[0]):undefined}}),
  setOnAir:onAir=>set({onAir,...(!onAir?{liveItemId:'',liveSlideId:'',liveTimerPausedSlideId:undefined}:{})}),goLive:(liveItemId,liveSlideId)=>set({liveItemId,liveSlideId,liveTimerPausedSlideId:undefined}),setLiveTimerPaused:liveTimerPausedSlideId=>set({liveTimerPausedSlideId}),
  nextLive:()=>{const state=get(),all=activeSlides(state),index=all.findIndex(entry=>entry.slideId===state.liveSlideId),currentItem=state.items.find(item=>item.id===state.liveItemId);let next=all[index<0?0:index+1];if(currentItem&&(currentItem.sectionId==='pre'||currentItem.sectionId==='post')){const sectionSlides=state.items.filter(item=>item.sectionId===currentItem.sectionId&&item.enabled&&!item.disabled).flatMap(item=>item.slides.filter(slide=>slide.enabled).map(slide=>({itemId:item.id,slideId:slide.id}))),sectionIndex=sectionSlides.findIndex(entry=>entry.slideId===state.liveSlideId);if(sectionSlides.length&&sectionIndex===sectionSlides.length-1&&state.items.some(item=>item.sectionId===currentItem.sectionId&&(item.repeat||item.timing.repeat)))next=sectionSlides[0]}if(next)state.goLive(next.itemId,next.slideId)},previousLive:()=>{const state=get(),all=activeSlides(state),index=all.findIndex(entry=>entry.slideId===state.liveSlideId),previous=all[Math.max(0,index<0?0:index-1)];if(previous)state.goLive(previous.itemId,previous.slideId)},
  undo:()=>set(state=>{const previous=state.history.at(-1);return previous?{...previous,history:state.history.slice(0,-1),future:[snap(state),...state.future].slice(0,50),saveState:'dirty',updatedAt:iso()}:state}),redo:()=>set(state=>{const next=state.future[0];return next?{...next,history:[...state.history,snap(state)].slice(-50),future:state.future.slice(1),saveState:'dirty',updatedAt:iso()}:state}),
  markSaving:()=>set(state=>({saveState:'saving',editHistory:state.editHistory.map(entry=>entry.syncStatus==='LOCAL'?{...entry,syncStatus:'PENDING' as const}:entry)})),markSaved:()=>set(state=>({saveState:'saved',editHistory:state.editHistory.map(entry=>entry.syncStatus==='PENDING'||entry.syncStatus==='LOCAL'?{...entry,syncStatus:'SYNCED' as const}:entry)})),markSaveError:()=>set(state=>({saveState:'error',editHistory:state.editHistory.map(entry=>entry.syncStatus==='PENDING'?{...entry,syncStatus:'ERROR' as const}:entry)}))
}),{name:'gottesdienstregie2.presentation',version:13,partialize:state=>({...state,onAir:false,liveItemId:'',liveSlideId:'',liveTimerPausedSlideId:undefined,saveState:'saved',history:[],future:[]}),migrate:(persisted:any)=>{const presentationId=String(persisted?.presentationId??'');return{...persisted,activeVirtualScreen:'main',transitionDefault:normalizeTransition(persisted?.transitionDefault)??{...defaultTransition},sections:Array.isArray(persisted?.sections)&&persisted.sections.length?persisted.sections:sections,items:(persisted?.items??initial).map(normalizeItem),archived:persisted?.archived===true,trashed:persisted?.trashed===true,eventId:persisted?.eventId??'',eventLink:persisted?.eventLink??(persisted?.eventId?{eventKey:persisted.eventId}:undefined),templateId:persisted?.templateId??'',serviceTime:persisted?.serviceTime??persisted?.serviceTimes?.[0]??'',createdBy:persisted?.createdBy??'',historyUserId:persisted?.historyUserId??'',historyDisplayName:persisted?.historyDisplayName??'',editHistory:Array.isArray(persisted?.editHistory)?persisted.editHistory.map((entry:any,index:number)=>legacyHistory(entry,presentationId,index)).slice(-1000):[],restorePoints:Array.isArray(persisted?.restorePoints)?persisted.restorePoints.slice(-50):[],selectedElementIds:[],previewItemId:persisted?.previewItemId??persisted?.selectedItemId,previewSlideId:persisted?.previewSlideId??persisted?.selectedSlideId,displayRoles:persisted?.displayRoles??(persisted?.mainDisplayId?{[String(persisted.mainDisplayId)]:'main'}:{}),liveItemId:'',liveSlideId:'',liveTimerPausedSlideId:undefined,onAir:false,history:[],future:[],saveState:'saved'}}}));

export function presentationDocument(state:State):PresentationDocument{return{presentationId:state.presentationId,title:state.title,date:state.date,createdAt:state.createdAt,updatedAt:state.updatedAt,archived:state.archived,trashed:state.trashed,eventId:state.eventLink?.eventKey??state.eventId,eventLink:state.eventLink,templateId:state.templateId,serviceTime:state.serviceTime,createdBy:state.createdBy,editHistory:state.editHistory,restorePoints:state.restorePoints,transitionDefault:state.transitionDefault,sections:state.sections,items:state.items,selectedItemId:state.selectedItemId,selectedSlideId:state.selectedSlideId,previewItemId:state.previewItemId,previewSlideId:state.previewSlideId}}
