import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type ItemType='content'|'image'|'video'|'audio'|'song'|'bible'|'web'|'pdf'|'timer'|'countdown';
export type ElementType='text'|'image'|'shape'|'line'|'video'|'qr';
export type SaveState='clean'|'dirty'|'saving'|'saved'|'error';
export type DisplayRole='unused'|'operator'|'main'|'stage'|'notes'|'livestream'|'lobby';
export interface SlideElement{id:string;type:ElementType;name:string;x:number;y:number;width:number;height:number;rotation:number;opacity:number;locked:boolean;visible:boolean;zIndex:number;properties:Record<string,string|number|boolean>}
export interface Slide{id:string;itemId:string;order:number;enabled:boolean;title:string;body:string;background:string;elements:SlideElement[];transition:string;transitionDuration:number;notes:string}
export interface ServiceItem{id:string;type:ItemType;title:string;section:string;sectionId:string;order:number;enabled:boolean;plannedDuration:number;metadata:Record<string,string|number|boolean>;slides:Slide[];autoAdvance:boolean;repeat:boolean;notes:string;stageDirection:string;disabled?:boolean}
export interface ServiceSection{id:string;title:string;order:number}
interface Snapshot{items:ServiceItem[];selectedItemId:string;selectedSlideId:string}
interface State{
  presentationId:string;title:string;date:string;createdAt:string;updatedAt:string;sections:ServiceSection[];items:ServiceItem[];
  selectedItemId:string;selectedSlideId:string;previewItemId:string;previewSlideId:string;liveItemId:string;liveSlideId:string;
  mode:'edit'|'preview';previewLayout:'single'|'grid';gridSize:number;onAir:boolean;mainDisplayId?:number;displayRoles:Record<string,DisplayRole>;saveState:SaveState;history:Snapshot[];future:Snapshot[];clipboard?:Slide;
  select:(itemId:string,slideId?:string)=>void;selectPreview:(itemId:string,slideId:string)=>void;setMode:(mode:'edit'|'preview')=>void;setPreviewLayout:(layout:'single'|'grid')=>void;setGridSize:(n:number)=>void;
  addItem:(type:ItemType,copy?:{title:string;section:string;body:string})=>void;removeItem:(id:string)=>void;reorder:(active:string,over:string)=>void;
  addSlide:()=>void;duplicateSlide:()=>void;copySlide:()=>void;pasteSlide:()=>void;removeSlide:()=>void;toggleSlide:()=>void;moveSlide:(direction:-1|1)=>void;reorderSlides:(active:string,over:string)=>void;
  updateSlide:(patch:Partial<Slide>)=>void;setMainDisplay:(id?:number)=>void;setDisplayRole:(id:number,role:DisplayRole)=>void;setOnAir:(value:boolean)=>void;goLive:(itemId:string,slideId:string)=>void;nextLive:()=>void;previousLive:()=>void;
  undo:()=>void;redo:()=>void;markSaving:()=>void;markSaved:()=>void;markSaveError:()=>void;
}

const uuid=()=>crypto.randomUUID(),iso=()=>new Date().toISOString();
const textElement=(text:string):SlideElement=>({id:uuid(),type:'text',name:'Text',x:210,y:320,width:1500,height:280,rotation:0,opacity:1,locked:false,visible:true,zIndex:1,properties:{text,fontFamily:'Inter',fontSize:72,fontWeight:600,color:'#ffffff',align:'center',verticalAlign:'center',lineHeight:1.15,letterSpacing:0,padding:24}});
const makeSlide=(itemId:string,title='Neue Folie',body='',background='#3b4652'):Slide=>({id:uuid(),itemId,order:0,enabled:true,title,body,background,elements:[textElement(body)],transition:'fade',transitionDuration:350,notes:''});
const sectionName=(id:string)=>({pre:'VORPROGRAMM',arrival:'ANKOMMEN',service:'GOTTESDIENST',post:'NACHPROGRAMM'}[id]??'GOTTESDIENST');
const makeItem=(type:ItemType,title:string,sectionId='service',body=''):ServiceItem=>{const id=uuid();return{id,type,title,section:sectionName(sectionId),sectionId,order:0,enabled:true,plannedDuration:0,metadata:{},slides:[makeSlide(id,title,body)],autoAdvance:false,repeat:false,notes:'',stageDirection:''}};
const sections:ServiceSection[]=[{id:'pre',title:'VORPROGRAMM',order:0},{id:'arrival',title:'ANKOMMEN',order:1},{id:'service',title:'GOTTESDIENST',order:2},{id:'post',title:'NACHPROGRAMM',order:3}];
const welcome=makeItem('content','Willkommen','arrival','Schön, dass du da bist.');welcome.id='welcome';welcome.slides[0]={...welcome.slides[0],id:'welcome-1',itemId:'welcome'};
const song=makeItem('song','Großer Gott, wir loben dich','service','Großer Gott, wir loben dich\nHerr, wir preisen deine Stärke');song.id='song-1';song.slides=[{...song.slides[0],id:'song-1a',itemId:'song-1',title:'Vers 1'},makeSlide('song-1','Vers 2','Alles, was dich preisen kann\nKerubim und Serafinen','#394755')];song.slides[1].id='song-1b';
const sermon=makeItem('content','Predigt','service','Hoffnung, die trägt');sermon.id='sermon';sermon.slides[0]={...sermon.slides[0],id:'sermon-1',itemId:'sermon'};
const initial=[welcome,song,sermon].map((item,order)=>({...item,order,slides:item.slides.map((slide,index)=>({...slide,order:index}))}));
const snap=(state:State):Snapshot=>({items:structuredClone(state.items),selectedItemId:state.selectedItemId,selectedSlideId:state.selectedSlideId});
const changed=(state:State,patch:Partial<State>)=>({...patch,history:[...state.history.slice(-49),snap(state)],future:[],saveState:'dirty' as SaveState,updatedAt:iso()});
const activeSlides=(state:State)=>state.items.filter(item=>item.enabled&&!item.disabled).flatMap(item=>item.slides.filter(slide=>slide.enabled).map(slide=>({itemId:item.id,slideId:slide.id})));
const normalizeItem=(raw:any,index:number):ServiceItem=>{const type:ItemType=raw?.type==='media'?'image':raw?.type??'content',sectionId=raw?.sectionId??(raw?.section==='ANKOMMEN'?'arrival':raw?.section==='VORPROGRAMM'?'pre':raw?.section==='NACHPROGRAMM'?'post':'service'),base=makeItem(type,raw?.title??'Neuer Inhalt',sectionId);return{...base,...raw,type,sectionId,section:sectionName(sectionId),order:raw?.order??index,enabled:raw?.enabled??!raw?.disabled,slides:(raw?.slides?.length?raw.slides:base.slides).map((slide:any,slideIndex:number)=>({...makeSlide(raw?.id??base.id,slide?.title,slide?.body,slide?.background),...slide,itemId:raw?.id??base.id,order:slide?.order??slideIndex,enabled:slide?.enabled??true}))}};

export const usePresentation=create<State>()(persist((set,get)=>({
  presentationId:'default-presentation',title:'Sonntagsgottesdienst',date:new Date().toISOString().slice(0,10),createdAt:iso(),updatedAt:iso(),sections,items:initial,
  selectedItemId:'welcome',selectedSlideId:'welcome-1',previewItemId:'welcome',previewSlideId:'welcome-1',liveItemId:'',liveSlideId:'',mode:'edit',previewLayout:'single',gridSize:180,onAir:false,displayRoles:{},saveState:'saved',history:[],future:[],
  select:(selectedItemId,slideId)=>{const item=get().items.find(entry=>entry.id===selectedItemId);set({selectedItemId,selectedSlideId:slideId??item?.slides[0]?.id??''})},selectPreview:(previewItemId,previewSlideId)=>set({previewItemId,previewSlideId}),
  setMode:mode=>set({mode}),setPreviewLayout:previewLayout=>set({previewLayout}),setGridSize:gridSize=>set({gridSize}),
  addItem:(type,copy)=>set(state=>{const names:Record<ItemType,string>={content:'Neuer Inhalt',image:'Neues Bild',video:'Neues Video',audio:'Neues Audio',song:'Neuer Song',bible:'Bibelstelle',web:'Neue Webseite',pdf:'Neues PDF',timer:'Neuer Timer',countdown:'Neuer Countdown'},sectionId=copy?.section==='ANKOMMEN'?'arrival':'service',item=makeItem(type,copy?.title??names[type],sectionId,copy?.body??'');item.order=state.items.length;return changed(state,{items:[...state.items,item],selectedItemId:item.id,selectedSlideId:item.slides[0].id})}),
  removeItem:id=>set(state=>{const items=state.items.filter(item=>item.id!==id),first=items[0];return items.length===state.items.length?state:changed(state,{items,selectedItemId:first?.id??'',selectedSlideId:first?.slides[0]?.id??''})}),
  reorder:(active,over)=>set(state=>{const from=state.items.findIndex(item=>item.id===active),to=state.items.findIndex(item=>item.id===over);if(from<0||to<0)return state;const items=[...state.items],[moved]=items.splice(from,1);items.splice(to,0,moved);return changed(state,{items:items.map((item,order)=>({...item,order}))})}),
  addSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId),slide=makeSlide(items[itemIndex].id);slides.splice(index<0?slides.length:index+1,0,slide);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:slide.id})}),
  duplicateSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId);if(index<0)return state;const clone={...structuredClone(slides[index]),id:uuid(),elements:slides[index].elements.map(element=>({...structuredClone(element),id:uuid()}))};slides.splice(index+1,0,clone);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:clone.id})}),
  copySlide:()=>{const state=get(),slide=state.items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(slide)set({clipboard:structuredClone(slide)})},
  pasteSlide:()=>set(state=>{if(!state.clipboard)return state;const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),clone={...structuredClone(state.clipboard),id:uuid(),itemId:items[itemIndex].id,elements:state.clipboard.elements.map(element=>({...structuredClone(element),id:uuid()}))};items[itemIndex].slides.push(clone);items[itemIndex].slides=items[itemIndex].slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:clone.id})}),
  removeSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId);if(index<0||slides.length<=1)return state;slides.splice(index,1);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:slides[Math.min(index,slides.length-1)].id})}),
  toggleSlide:()=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,enabled:!slide.enabled}:slide)}))})),
  moveSlide:direction=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId),index=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===state.selectedSlideId)??-1,target=index+direction;if(itemIndex<0||index<0||target<0||target>=state.items[itemIndex].slides.length)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides;[slides[index],slides[target]]=[slides[target],slides[index]];items[itemIndex].slides=slides.map((slide,order)=>({...slide,order}));return changed(state,{items})}),
  reorderSlides:(active,over)=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId),from=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===active)??-1,to=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===over)??-1;if(itemIndex<0||from<0||to<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,[moved]=slides.splice(from,1);slides.splice(to,0,moved);items[itemIndex].slides=slides.map((slide,order)=>({...slide,order}));return changed(state,{items})}),
  updateSlide:patch=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,...patch,elements:patch.body!==undefined?slide.elements.map((element,index)=>index===0&&element.type==='text'?{...element,properties:{...element.properties,text:patch.body!}}:element):patch.elements??slide.elements}:slide)}))})),
  setMainDisplay:mainDisplayId=>set(state=>{const displayRoles={...state.displayRoles};for(const key of Object.keys(displayRoles))if(displayRoles[key]==='main')delete displayRoles[key];if(mainDisplayId!==undefined)displayRoles[String(mainDisplayId)]='main';return{mainDisplayId,displayRoles}}),
  setDisplayRole:(id,role)=>set(state=>{const displayRoles={...state.displayRoles};if(role!=='unused')for(const key of Object.keys(displayRoles))if(displayRoles[key]===role)delete displayRoles[key];if(role==='unused')delete displayRoles[String(id)];else displayRoles[String(id)]=role;const mainEntry=Object.entries(displayRoles).find(([,value])=>value==='main');return{displayRoles,mainDisplayId:mainEntry?Number(mainEntry[0]):undefined}}),
  setOnAir:onAir=>set({onAir,...(!onAir?{liveItemId:'',liveSlideId:''}:{})}),goLive:(liveItemId,liveSlideId)=>set({liveItemId,liveSlideId}),
  nextLive:()=>{const state=get(),all=activeSlides(state),index=all.findIndex(entry=>entry.slideId===state.liveSlideId),next=all[Math.min(all.length-1,index<0?0:index+1)];if(next)state.goLive(next.itemId,next.slideId)},previousLive:()=>{const state=get(),all=activeSlides(state),index=all.findIndex(entry=>entry.slideId===state.liveSlideId),previous=all[Math.max(0,index<0?0:index-1)];if(previous)state.goLive(previous.itemId,previous.slideId)},
  undo:()=>set(state=>{const previous=state.history.at(-1);return previous?{...previous,history:state.history.slice(0,-1),future:[snap(state),...state.future].slice(0,50),saveState:'dirty',updatedAt:iso()}:state}),redo:()=>set(state=>{const next=state.future[0];return next?{...next,history:[...state.history,snap(state)].slice(-50),future:state.future.slice(1),saveState:'dirty',updatedAt:iso()}:state}),
  markSaving:()=>set({saveState:'saving'}),markSaved:()=>set({saveState:'saved'}),markSaveError:()=>set({saveState:'error'})
}),{name:'gottesdienstregie2.presentation',version:3,partialize:state=>({...state,onAir:false,liveItemId:'',liveSlideId:'',saveState:'saved',history:[],future:[]}),migrate:(persisted:any)=>({...persisted,sections:persisted?.sections??sections,items:(persisted?.items??initial).map(normalizeItem),previewItemId:persisted?.previewItemId??persisted?.selectedItemId,previewSlideId:persisted?.previewSlideId??persisted?.selectedSlideId,displayRoles:persisted?.displayRoles??(persisted?.mainDisplayId?{[String(persisted.mainDisplayId)]:'main'}:{}),liveItemId:'',liveSlideId:'',onAir:false,history:[],future:[],saveState:'saved'})}));

export function presentationDocument(state:State){return{presentationId:state.presentationId,title:state.title,date:state.date,createdAt:state.createdAt,updatedAt:state.updatedAt,sections:state.sections,items:state.items,selectedItemId:state.selectedItemId,selectedSlideId:state.selectedSlideId,previewItemId:state.previewItemId,previewSlideId:state.previewSlideId}}
