import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export type ItemType='content'|'image'|'video'|'videoInput'|'audio'|'song'|'bible'|'web'|'pdf'|'timer'|'countdown'|'announcement'|'slideshow'|'stageMessage'|'quickScreen';
export type ElementType='text'|'image'|'shape'|'line'|'video'|'audio'|'videoInput'|'web'|'qr';
export type SaveState='clean'|'dirty'|'saving'|'saved'|'error';
export type DisplayRole='unused'|'operator'|'main'|'stage'|'notes'|'livestream'|'lobby';
export type TimingMode='manual'|'slide-duration'|'media-duration'|'scheduled';
export interface ItemTiming{mode:TimingMode;slideDurationSeconds:number;autoAdvance:boolean;repeat:boolean;shuffle:boolean;mediaDurationSeconds:number;totalDurationSeconds:number}
export interface SlideTiming{durationSeconds?:number}
export interface SlideElement{id:string;type:ElementType;name:string;x:number;y:number;width:number;height:number;rotation:number;opacity:number;locked:boolean;visible:boolean;zIndex:number;properties:Record<string,string|number|boolean>}
export interface Slide{id:string;itemId:string;order:number;enabled:boolean;title:string;body:string;background:string;elements:SlideElement[];transition:string;transitionDuration:number;notes:string;timing?:SlideTiming}
export interface ServiceItem{id:string;type:ItemType;title:string;section:string;sectionId:string;order:number;enabled:boolean;plannedDuration:number;metadata:Record<string,string|number|boolean>;slides:Slide[];autoAdvance:boolean;repeat:boolean;timing:ItemTiming;notes:string;stageDirection:string;createdAt:string;updatedAt:string;groupId?:string;disabled?:boolean}
export interface ServiceSection{id:string;title:string;order:number}
interface Snapshot{items:ServiceItem[];selectedItemId:string;selectedSlideId:string}
export interface PresentationDocument{presentationId:string;title:string;date:string;createdAt:string;updatedAt:string;archived?:boolean;trashed?:boolean;eventId?:string;templateId?:string;serviceTime?:string;serviceTimes?:string[];createdBy?:string;sections:ServiceSection[];items:ServiceItem[];selectedItemId?:string;selectedSlideId?:string;previewItemId?:string;previewSlideId?:string}
interface State{
  presentationId:string;title:string;date:string;createdAt:string;updatedAt:string;archived:boolean;trashed:boolean;eventId:string;templateId:string;serviceTime:string;createdBy:string;sections:ServiceSection[];items:ServiceItem[];
  selectedItemId:string;selectedSlideId:string;previewItemId:string;previewSlideId:string;liveItemId:string;liveSlideId:string;
  mode:'edit'|'preview';previewLayout:'single'|'grid';gridSize:number;onAir:boolean;mainDisplayId?:number;displayRoles:Record<string,DisplayRole>;saveState:SaveState;history:Snapshot[];future:Snapshot[];clipboard?:Slide;selectedElementIds:string[];
  loadDocument:(document:unknown)=>void;newDocument:(title:string,date?:string)=>PresentationDocument;updatePresentation:(patch:Partial<Pick<State,'title'|'date'|'eventId'|'templateId'|'serviceTime'>>)=>void;
  select:(itemId:string,slideId?:string)=>void;selectPreview:(itemId:string,slideId:string)=>void;setMode:(mode:'edit'|'preview')=>void;setPreviewLayout:(layout:'single'|'grid')=>void;setGridSize:(n:number)=>void;
  addItem:(type:ItemType,copy?:{title:string;section:string;sectionId?:string;body:string;metadata?:Record<string,string|number|boolean>})=>void;removeItem:(id:string)=>void;duplicateItem:(id:string)=>void;updateItem:(id:string,patch:Partial<ServiceItem>)=>void;moveItemToSection:(id:string,sectionId:string)=>void;reorder:(active:string,over:string)=>void;
  addSlide:()=>void;duplicateSlide:()=>void;copySlide:()=>void;pasteSlide:()=>void;removeSlide:()=>void;toggleSlide:()=>void;moveSlide:(direction:-1|1)=>void;reorderSlides:(active:string,over:string)=>void;
  updateSlide:(patch:Partial<Slide>)=>void;selectElements:(ids:string[])=>void;addElement:(type:ElementType)=>void;updateElement:(id:string,patch:Partial<SlideElement>)=>void;removeElements:()=>void;toggleElementVisible:(id:string)=>void;toggleElementLocked:(id:string)=>void;moveElementLayer:(id:string,direction:-1|1)=>void;setMainDisplay:(id?:number)=>void;setDisplayRole:(id:number,role:DisplayRole)=>void;setOnAir:(value:boolean)=>void;goLive:(itemId:string,slideId:string)=>void;nextLive:()=>void;previousLive:()=>void;
  undo:()=>void;redo:()=>void;markSaving:()=>void;markSaved:()=>void;markSaveError:()=>void;
}

const uuid=()=>crypto.randomUUID(),iso=()=>new Date().toISOString();
const textElement=(text:string):SlideElement=>({id:uuid(),type:'text',name:'Text',x:210,y:320,width:1500,height:280,rotation:0,opacity:1,locked:false,visible:true,zIndex:1,properties:{text,fontFamily:'Inter',fontSize:72,fontWeight:600,color:'#ffffff',align:'center',verticalAlign:'center',lineHeight:1.15,letterSpacing:0,padding:24}});
const makeSlide=(itemId:string,title='Neue Folie',body='',background='#3b4652'):Slide=>({id:uuid(),itemId,order:0,enabled:true,title,body,background,elements:[textElement(body)],transition:'fade',transitionDuration:350,notes:'',timing:{}});
const sectionName=(id:string)=>({pre:'VORPROGRAMM',warmup:'WARM-UP',arrival:'WARM-UP',service:'GOTTESDIENST',post:'NACHPROGRAMM'}[id]??'GOTTESDIENST');
const defaultTiming=():ItemTiming=>({mode:'manual',slideDurationSeconds:7,autoAdvance:false,repeat:false,shuffle:false,mediaDurationSeconds:0,totalDurationSeconds:0});
export const createServiceItem=(type:ItemType,options:Partial<ServiceItem>&{title?:string;sectionId?:string;body?:string}={}):ServiceItem=>{const id=options.id??uuid(),stamp=iso(),sectionId=options.sectionId==='arrival'?'warmup':options.sectionId??'service',timing={...defaultTiming(),...options.timing};return{id,type,title:options.title??'Neuer Inhalt',section:sectionName(sectionId),sectionId,order:options.order??0,enabled:options.enabled??true,plannedDuration:options.plannedDuration??0,metadata:options.metadata??{},slides:options.slides??[makeSlide(id,options.title,options.body??'')],autoAdvance:options.autoAdvance??timing.autoAdvance,repeat:options.repeat??timing.repeat,timing,notes:options.notes??'',stageDirection:options.stageDirection??'',createdAt:options.createdAt??stamp,updatedAt:options.updatedAt??stamp,groupId:options.groupId,disabled:options.disabled}};
const makeItem=(type:ItemType,title:string,sectionId='service',body='')=>createServiceItem(type,{title,sectionId,body});
const sections:ServiceSection[]=[{id:'pre',title:'VORPROGRAMM',order:0},{id:'warmup',title:'WARM-UP',order:1},{id:'service',title:'GOTTESDIENST',order:2},{id:'post',title:'NACHPROGRAMM',order:3}];
const welcome=makeItem('content','Willkommen','warmup','Schön, dass du da bist.');welcome.id='welcome';welcome.slides[0]={...welcome.slides[0],id:'welcome-1',itemId:'welcome'};
const song=makeItem('song','Großer Gott, wir loben dich','service','Großer Gott, wir loben dich\nHerr, wir preisen deine Stärke');song.id='song-1';song.slides=[{...song.slides[0],id:'song-1a',itemId:'song-1',title:'Vers 1'},makeSlide('song-1','Vers 2','Alles, was dich preisen kann\nKerubim und Serafinen','#394755')];song.slides[1].id='song-1b';
const sermon=makeItem('content','Predigt','service','Hoffnung, die trägt');sermon.id='sermon';sermon.slides[0]={...sermon.slides[0],id:'sermon-1',itemId:'sermon'};
const initial=[welcome,song,sermon].map((item,order)=>({...item,order,slides:item.slides.map((slide,index)=>({...slide,order:index}))}));
const snap=(state:State):Snapshot=>({items:structuredClone(state.items),selectedItemId:state.selectedItemId,selectedSlideId:state.selectedSlideId});
const changed=(state:State,patch:Partial<State>)=>({...patch,history:[...state.history.slice(-49),snap(state)],future:[],saveState:'dirty' as SaveState,updatedAt:iso()});
const activeSlides=(state:State)=>state.items.filter(item=>item.enabled&&!item.disabled).flatMap(item=>item.slides.filter(slide=>slide.enabled).map(slide=>({itemId:item.id,slideId:slide.id})));
export const itemDurationSeconds=(item:ServiceItem)=>{const active=item.slides.filter(slide=>slide.enabled),slideTotal=active.reduce((sum,slide)=>sum+(slide.timing?.durationSeconds??item.timing?.slideDurationSeconds??item.plannedDuration??0),0);return Math.max(0,Math.round(item.timing?.mediaDurationSeconds||item.timing?.totalDurationSeconds||slideTotal||item.plannedDuration||0))};
export const formatDuration=(seconds:number)=>{const value=Math.max(0,Math.round(seconds));if(value>0&&value<60)return `${value}s`;const minutes=Math.floor(value/60),rest=value%60;return `${minutes}:${String(rest).padStart(2,'0')}`};
export const parseDuration=(value:string)=>{const normalized=value.trim().toLowerCase(),secondsOnly=normalized.match(/^(\d+)\s*s$/);if(secondsOnly){const seconds=Number(secondsOnly[1]);return seconds>=1?Math.round(seconds):null}const parts=normalized.split(':').map(Number);if(parts.some(Number.isNaN))return null;const seconds=parts.length===1?parts[0]:parts.length===2?parts[0]*60+parts[1]:parts[0]*3600+parts[1]*60+parts[2];return seconds>=1?Math.round(seconds):null};
const normalizeItem=(raw:any,index:number):ServiceItem=>{const type:ItemType=raw?.type==='media'?'image':raw?.type??'content',legacySection=raw?.sectionId??(raw?.section==='ANKOMMEN'?'warmup':raw?.section==='VORPROGRAMM'?'pre':raw?.section==='NACHPROGRAMM'?'post':'service'),sectionId=legacySection==='arrival'?'warmup':legacySection,base=makeItem(type,raw?.title??'Neuer Inhalt',sectionId),timing={...base.timing,...raw?.timing,autoAdvance:raw?.timing?.autoAdvance??raw?.autoAdvance??false,repeat:raw?.timing?.repeat??raw?.repeat??false};return{...base,...raw,type,sectionId,section:sectionName(sectionId),timing,autoAdvance:timing.autoAdvance,repeat:timing.repeat,createdAt:raw?.createdAt??base.createdAt,updatedAt:raw?.updatedAt??base.updatedAt,order:raw?.order??index,enabled:raw?.enabled??!raw?.disabled,slides:(raw?.slides?.length?raw.slides:base.slides).map((slide:any,slideIndex:number)=>({...makeSlide(raw?.id??base.id,slide?.title,slide?.body,slide?.background),...slide,timing:slide?.timing??{},itemId:raw?.id??base.id,order:slide?.order??slideIndex,enabled:slide?.enabled??true}))}};

export function blankPresentationDocument(title='Neue Präsentation',date=new Date().toISOString().slice(0,10)):PresentationDocument{const stamp=iso();return{presentationId:uuid(),title,date,createdAt:stamp,updatedAt:stamp,archived:false,trashed:false,eventId:'',templateId:'',serviceTime:'',createdBy:'',sections,items:[]}}

export const usePresentation=create<State>()(persist((set,get)=>({
  presentationId:'',title:'',date:new Date().toISOString().slice(0,10),createdAt:iso(),updatedAt:iso(),archived:false,trashed:false,eventId:'',templateId:'',serviceTime:'',createdBy:'',sections,items:[],
  selectedItemId:'',selectedSlideId:'',previewItemId:'',previewSlideId:'',liveItemId:'',liveSlideId:'',mode:'edit',previewLayout:'single',gridSize:180,onAir:false,displayRoles:{},saveState:'saved',history:[],future:[],selectedElementIds:[],
  loadDocument:raw=>{const document=raw as any,items=(document?.items??[]).map(normalizeItem),first=items[0],firstSlide=first?.slides[0],legacyTime=Array.isArray(document?.serviceTimes)?document.serviceTimes[0]:'';set({presentationId:String(document?.presentationId??uuid()),title:String(document?.title??'Unbenannte Präsentation'),date:String(document?.date??new Date().toISOString().slice(0,10)),createdAt:String(document?.createdAt??iso()),updatedAt:String(document?.updatedAt??iso()),archived:document?.archived===true,trashed:document?.trashed===true,eventId:String(document?.eventId??''),templateId:String(document?.templateId??''),serviceTime:String(document?.serviceTime??legacyTime??''),createdBy:String(document?.createdBy??''),sections:Array.isArray(document?.sections)&&document.sections.length?document.sections:sections,items,selectedItemId:document?.selectedItemId&&items.some((item:ServiceItem)=>item.id===document.selectedItemId)?document.selectedItemId:first?.id??'',selectedSlideId:document?.selectedSlideId&&items.some((item:ServiceItem)=>item.slides.some(slide=>slide.id===document.selectedSlideId))?document.selectedSlideId:firstSlide?.id??'',previewItemId:document?.previewItemId??first?.id??'',previewSlideId:document?.previewSlideId??firstSlide?.id??'',liveItemId:'',liveSlideId:'',onAir:false,saveState:'saved',history:[],future:[],selectedElementIds:[]})},
  newDocument:(title,date)=>{const document=blankPresentationDocument(title,date);get().loadDocument(document);return document},
  updatePresentation:patch=>set(state=>changed(state,patch)),
  select:(selectedItemId,slideId)=>{const item=get().items.find(entry=>entry.id===selectedItemId);set({selectedItemId,selectedSlideId:slideId??item?.slides[0]?.id??''})},selectPreview:(previewItemId,previewSlideId)=>set({previewItemId,previewSlideId}),
  setMode:mode=>set({mode}),setPreviewLayout:previewLayout=>set({previewLayout}),setGridSize:gridSize=>set({gridSize}),
  addItem:(type,copy)=>set(state=>{const names:Record<ItemType,string>={content:'Neuer Inhalt',image:'Neues Bild',video:'Neues Video',videoInput:'Neuer Videoeingang',audio:'Neues Audio',song:'Neuer Song',bible:'Bibelstelle',web:'Neue Webseite',pdf:'Neues PDF',timer:'Neuer Timer',countdown:'Neuer Countdown',announcement:'Neue Ankündigung',slideshow:'Neue Slideshow',stageMessage:'Neue Stage-Nachricht',quickScreen:'Neue Schnellanzeige'},rawSection=copy?.sectionId??(copy?.section==='ANKOMMEN'?'warmup':copy?.section==='VORPROGRAMM'?'pre':copy?.section==='NACHPROGRAMM'?'post':'service'),sectionId=rawSection==='arrival'?'warmup':rawSection,item=createServiceItem(type,{title:copy?.title??names[type],sectionId,body:copy?.body??'',metadata:copy?.metadata??{},order:state.items.length});return changed(state,{items:[...state.items,item],selectedItemId:item.id,selectedSlideId:item.slides[0].id,selectedElementIds:[]})}),
  removeItem:id=>set(state=>{const items=state.items.filter(item=>item.id!==id),first=items[0];return items.length===state.items.length?state:changed(state,{items,selectedItemId:first?.id??'',selectedSlideId:first?.slides[0]?.id??''})}),
  duplicateItem:id=>set(state=>{const source=state.items.find(item=>item.id===id);if(!source)return state;const item=structuredClone(source),itemId=uuid();item.id=itemId;item.title=`${item.title} – Kopie`;item.createdAt=iso();item.updatedAt=iso();item.slides=item.slides.map(slide=>({...slide,id:uuid(),itemId,elements:slide.elements.map(element=>({...element,id:uuid()}))}));item.order=source.order+1;const items=[...state.items],index=items.findIndex(entry=>entry.id===id);items.splice(index+1,0,item);return changed(state,{items:items.map((entry,order)=>({...entry,order})),selectedItemId:item.id,selectedSlideId:item.slides[0]?.id??''})}),
  updateItem:(id,patch)=>set(state=>changed(state,{items:state.items.map(item=>item.id===id?{...item,...patch,updatedAt:iso()}:item)})),
  moveItemToSection:(id,sectionId)=>set(state=>changed(state,{items:state.items.map(item=>item.id===id?{...item,sectionId,section:sectionName(sectionId),updatedAt:iso()}:item)})),
  reorder:(active,over)=>set(state=>{const from=state.items.findIndex(item=>item.id===active),to=state.items.findIndex(item=>item.id===over);if(from<0||to<0)return state;const items=[...state.items],[moved]=items.splice(from,1);items.splice(to,0,moved);return changed(state,{items:items.map((item,order)=>({...item,order}))})}),
  addSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId),slide=makeSlide(items[itemIndex].id);slides.splice(index<0?slides.length:index+1,0,slide);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:slide.id})}),
  duplicateSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId);if(index<0)return state;const clone={...structuredClone(slides[index]),id:uuid(),elements:slides[index].elements.map(element=>({...structuredClone(element),id:uuid()}))};slides.splice(index+1,0,clone);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:clone.id})}),
  copySlide:()=>{const state=get(),slide=state.items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(slide)set({clipboard:structuredClone(slide)})},
  pasteSlide:()=>set(state=>{if(!state.clipboard)return state;const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),clone={...structuredClone(state.clipboard),id:uuid(),itemId:items[itemIndex].id,elements:state.clipboard.elements.map(element=>({...structuredClone(element),id:uuid()}))};items[itemIndex].slides.push(clone);items[itemIndex].slides=items[itemIndex].slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:clone.id})}),
  removeSlide:()=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId);if(itemIndex<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,index=slides.findIndex(slide=>slide.id===state.selectedSlideId);if(index<0||slides.length<=1)return state;slides.splice(index,1);items[itemIndex].slides=slides.map((entry,order)=>({...entry,order}));return changed(state,{items,selectedSlideId:slides[Math.min(index,slides.length-1)].id})}),
  toggleSlide:()=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,enabled:!slide.enabled}:slide)}))})),
  moveSlide:direction=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId),index=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===state.selectedSlideId)??-1,target=index+direction;if(itemIndex<0||index<0||target<0||target>=state.items[itemIndex].slides.length)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides;[slides[index],slides[target]]=[slides[target],slides[index]];items[itemIndex].slides=slides.map((slide,order)=>({...slide,order}));return changed(state,{items})}),
  reorderSlides:(active,over)=>set(state=>{const itemIndex=state.items.findIndex(item=>item.id===state.selectedItemId),from=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===active)??-1,to=state.items[itemIndex]?.slides.findIndex(slide=>slide.id===over)??-1;if(itemIndex<0||from<0||to<0)return state;const items=structuredClone(state.items),slides=items[itemIndex].slides,[moved]=slides.splice(from,1);slides.splice(to,0,moved);items[itemIndex].slides=slides.map((slide,order)=>({...slide,order}));return changed(state,{items})}),
  updateSlide:patch=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,...patch,elements:patch.body!==undefined?slide.elements.map((element,index)=>index===0&&element.type==='text'?{...element,properties:{...element.properties,text:patch.body!}}:element):patch.elements??slide.elements}:slide)}))})),
  selectElements:selectedElementIds=>set({selectedElementIds}),
  addElement:type=>set(state=>{const element:SlideElement={id:uuid(),type,name:type==='text'?'Text':type==='shape'?'Form':type==='image'?'Bild':type==='video'?'Video':type==='audio'?'Audio':type==='web'?'Webseite':type==='qr'?'QR-Code':'Linie',x:520,y:300,width:type==='line'?800:640,height:type==='line'?8:260,rotation:0,opacity:1,locked:false,visible:true,zIndex:99,properties:type==='text'?{text:'Neuer Text',fontFamily:'Inter',fontSize:64,fontWeight:600,color:'#ffffff',align:'center',verticalAlign:'center',lineHeight:1.15,padding:16}:type==='shape'?{fill:'#68aab5',stroke:'#ffffff',strokeWidth:0}:type==='line'?{fill:'#ffffff'}:{src:'',fit:'cover'}};const items=state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:[...slide.elements,element].map((entry,index)=>({...entry,zIndex:index+1}))}:slide)}));return changed(state,{items,selectedElementIds:[element.id]})}),
  updateElement:(id,patch)=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.map(element=>element.id===id?{...element,...patch}:element)}:slide)}))})),
  removeElements:()=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.filter(element=>!state.selectedElementIds.includes(element.id))}:slide)})),selectedElementIds:[]})),
  toggleElementVisible:id=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.map(element=>element.id===id?{...element,visible:!element.visible}:element)}:slide)}))})),
  toggleElementLocked:id=>set(state=>changed(state,{items:state.items.map(item=>({...item,slides:item.slides.map(slide=>slide.id===state.selectedSlideId?{...slide,elements:slide.elements.map(element=>element.id===id?{...element,locked:!element.locked}:element)}:slide)}))})),
  moveElementLayer:(id,direction)=>set(state=>{const items=structuredClone(state.items),slide=items.flatMap(item=>item.slides).find(entry=>entry.id===state.selectedSlideId);if(!slide)return state;const ordered=[...slide.elements].sort((a,b)=>a.zIndex-b.zIndex),index=ordered.findIndex(element=>element.id===id),target=index+direction;if(index<0||target<0||target>=ordered.length)return state;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];slide.elements=ordered.map((element,zIndex)=>({...element,zIndex:zIndex+1}));return changed(state,{items})}),
  setMainDisplay:mainDisplayId=>set(state=>{const displayRoles={...state.displayRoles};for(const key of Object.keys(displayRoles))if(displayRoles[key]==='main')delete displayRoles[key];if(mainDisplayId!==undefined)displayRoles[String(mainDisplayId)]='main';return{mainDisplayId,displayRoles}}),
  setDisplayRole:(id,role)=>set(state=>{const displayRoles={...state.displayRoles};if(role!=='unused')for(const key of Object.keys(displayRoles))if(displayRoles[key]===role)delete displayRoles[key];if(role==='unused')delete displayRoles[String(id)];else displayRoles[String(id)]=role;const mainEntry=Object.entries(displayRoles).find(([,value])=>value==='main');return{displayRoles,mainDisplayId:mainEntry?Number(mainEntry[0]):undefined}}),
  setOnAir:onAir=>set({onAir,...(!onAir?{liveItemId:'',liveSlideId:''}:{})}),goLive:(liveItemId,liveSlideId)=>set({liveItemId,liveSlideId}),
  nextLive:()=>{const state=get(),all=activeSlides(state),index=all.findIndex(entry=>entry.slideId===state.liveSlideId),currentItem=state.items.find(item=>item.id===state.liveItemId);let next=all[index<0?0:index+1];if(currentItem&&(currentItem.sectionId==='pre'||currentItem.sectionId==='post')){const sectionSlides=state.items.filter(item=>item.sectionId===currentItem.sectionId&&item.enabled&&!item.disabled).flatMap(item=>item.slides.filter(slide=>slide.enabled).map(slide=>({itemId:item.id,slideId:slide.id}))),sectionIndex=sectionSlides.findIndex(entry=>entry.slideId===state.liveSlideId);if(sectionSlides.length&&sectionIndex===sectionSlides.length-1&&state.items.some(item=>item.sectionId===currentItem.sectionId&&(item.repeat||item.timing.repeat)))next=sectionSlides[0]}if(next)state.goLive(next.itemId,next.slideId)},previousLive:()=>{const state=get(),all=activeSlides(state),index=all.findIndex(entry=>entry.slideId===state.liveSlideId),previous=all[Math.max(0,index<0?0:index-1)];if(previous)state.goLive(previous.itemId,previous.slideId)},
  undo:()=>set(state=>{const previous=state.history.at(-1);return previous?{...previous,history:state.history.slice(0,-1),future:[snap(state),...state.future].slice(0,50),saveState:'dirty',updatedAt:iso()}:state}),redo:()=>set(state=>{const next=state.future[0];return next?{...next,history:[...state.history,snap(state)].slice(-50),future:state.future.slice(1),saveState:'dirty',updatedAt:iso()}:state}),
  markSaving:()=>set({saveState:'saving'}),markSaved:()=>set({saveState:'saved'}),markSaveError:()=>set({saveState:'error'})
}),{name:'gottesdienstregie2.presentation',version:6,partialize:state=>({...state,onAir:false,liveItemId:'',liveSlideId:'',saveState:'saved',history:[],future:[]}),migrate:(persisted:any)=>({...persisted,sections,items:(persisted?.items??initial).map(normalizeItem),archived:persisted?.archived===true,trashed:persisted?.trashed===true,eventId:persisted?.eventId??'',templateId:persisted?.templateId??'',serviceTime:persisted?.serviceTime??persisted?.serviceTimes?.[0]??'',createdBy:persisted?.createdBy??'',selectedElementIds:[],previewItemId:persisted?.previewItemId??persisted?.selectedItemId,previewSlideId:persisted?.previewSlideId??persisted?.selectedSlideId,displayRoles:persisted?.displayRoles??(persisted?.mainDisplayId?{[String(persisted.mainDisplayId)]:'main'}:{}),liveItemId:'',liveSlideId:'',onAir:false,history:[],future:[],saveState:'saved'})}));

export function presentationDocument(state:State):PresentationDocument{return{presentationId:state.presentationId,title:state.title,date:state.date,createdAt:state.createdAt,updatedAt:state.updatedAt,archived:state.archived,trashed:state.trashed,eventId:state.eventId,templateId:state.templateId,serviceTime:state.serviceTime,createdBy:state.createdBy,sections:state.sections,items:state.items,selectedItemId:state.selectedItemId,selectedSlideId:state.selectedSlideId,previewItemId:state.previewItemId,previewSlideId:state.previewSlideId}}
