import {useCallback,useEffect,useMemo,useState} from 'react';
import {formatStorageBytes,storageCategoryLabels,type StorageCategory,type StorageSnapshot} from './storageMaintenance';

const empty:StorageSnapshot={totalBytes:0,categories:[]};
export function StorageSettings(){
  const api=(window.desktop as any)?.storage as undefined|{snapshot:()=>Promise<StorageSnapshot>;clear:(categories:StorageCategory[])=>Promise<StorageSnapshot>};
  const [snapshot,setSnapshot]=useState(empty),[selected,setSelected]=useState<StorageCategory[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('');
  const refresh=useCallback(async()=>{if(!api)return;setLoading(true);setError('');try{const value=await api.snapshot();setSnapshot(value);setSelected(current=>current.length?current:value.categories.filter(item=>item.bytes>0&&!item.error).map(item=>item.category));}catch(reason){setError(reason instanceof Error?reason.message:String(reason));}finally{setLoading(false)}},[api]);
  useEffect(()=>{void refresh()},[refresh]);
  const selectedBytes=useMemo(()=>snapshot.categories.filter(item=>selected.includes(item.category)).reduce((sum,item)=>sum+item.bytes,0),[selected,snapshot]);
  const clear=async()=>{if(!api||!selected.length)return;const names=selected.map(category=>storageCategoryLabels[category]).join(', ');if(!confirm(`Folgende Zwischenspeicher werden unwiderruflich geleert:\n\n${names}\n\nFreizugebender Speicher: ${formatStorageBytes(selectedBytes)}\n\nPräsentationen, Einstellungen und Originalmedien bleiben erhalten.`))return;setLoading(true);setError('');try{setSnapshot(await api.clear(selected));setSelected([]);}catch(reason){const message=reason instanceof Error?reason.message:String(reason);setError(message.includes('ON_AIR')?'Während ON AIR kann der Speicher nicht geleert werden.':message.includes('DOWNLOAD_ACTIVE')?'Bitte warte, bis alle Sprachdownloads beendet sind.':`Der Speicher konnte nicht vollständig geleert werden: ${message}`);}finally{setLoading(false)}};
  return <section className="settings-group storage-settings"><h4>SPEICHER &amp; ZWISCHENSPEICHER</h4><p>Aktuell belegen löschbare, von GottesdienstRegie erzeugte Zwischendaten <strong>{loading?'Wird berechnet …':formatStorageBytes(snapshot.totalBytes)}</strong>. Präsentationen, Konten, Einstellungen, Originalmedien und gespeicherte Liedübersetzungen werden nicht gelöscht.</p>{!api&&<p className="notice">Diese Funktion ist nur in der Desktop-App verfügbar.</p>}{snapshot.categories.map(item=><label className="storage-category" key={item.category}><input type="checkbox" disabled={loading||!!item.error||item.bytes===0} checked={selected.includes(item.category)} onChange={event=>setSelected(value=>event.target.checked?[...value,item.category]:value.filter(category=>category!==item.category))}/><span><b>{storageCategoryLabels[item.category]}</b><small>{item.error?`Nicht verfügbar: ${item.error}`:`${formatStorageBytes(item.bytes)} · ${item.files} Dateien`}</small></span></label>)}{error&&<p className="error">{error}</p>}<div className="storage-actions"><button type="button" disabled={loading} onClick={()=>void refresh()}>NEU BERECHNEN</button><button className="danger-button" type="button" disabled={loading||!selected.length} onClick={()=>void clear()}>AUSGEWÄHLTEN SPEICHER LEEREN · {formatStorageBytes(selectedBytes)}</button></div></section>;
}
