export const TERMS_VERSION='2.1';
export const TERMS_EFFECTIVE_DATE='26. September 2026';
export type TermsSection={title:string;paragraphs:string[]};
export const termsSections:TermsSection[]=[
{title:'1. Geltungsbereich',paragraphs:['Diese Nutzungsbedingungen gelten für die Installation, Einrichtung und Verwendung der Anwendung GottesdienstRegie einschließlich der Desktop- und Weboberfläche, Cloud- und Medienfunktionen, Übersetzungsdienste, Fernsteuerung, Ausgabefenster sowie bereitgestellter Updates. Sie erfassen sowohl die Vorbereitung einer Veranstaltung als auch Vorschau, Testbetrieb und öffentliche Liveausgabe. Mit der ausdrücklichen Zustimmung bei der Installation oder Aktualisierung wird die jeweils angezeigte Fassung akzeptiert; ergänzende Bedingungen eines eingesetzten Drittanbieters bleiben daneben anwendbar.']},
{title:'2. Anbieter und Kontakt',paragraphs:['GottesdienstRegie wird als nicht gewinnorientiertes Arbeitsmittel der Philippus Gemeinde Bielefeld e. V. bereitgestellt und dient vor allem der Planung und technischen Durchführung von Gottesdiensten und vergleichbaren Veranstaltungen. Aus der Bereitstellung entsteht kein Anspruch auf individuellen Support, bestimmte Reaktionszeiten oder eine dauerhafte Weiterentwicklung einzelner Funktionen. Fragen sowie nachvollziehbare Fehler-, Datenschutz- oder Sicherheitsmeldungen sollen mit Versionsnummer und einer möglichst genauen Beschreibung an die in der Anwendung genannte Kontaktstelle gerichtet werden.']},
{title:'3. Nutzungsvoraussetzungen',paragraphs:['Die Anwendung darf nur von Personen verwendet werden, die von der verantwortlichen Gemeinde oder Organisation hierzu berechtigt wurden und die Bedienung der eingesetzten Ausgabe-, Audio- und Netzwerktechnik ausreichend beherrschen. Vor einer Veranstaltung sind die lokale Funktionsfähigkeit, verfügbare Speicherkapazität, Netzwerkzugänge, verbundene Monitore und gegebenenfalls erforderliche Dienste zu prüfen. Minderjährige oder noch nicht eingewiesene Personen nutzen die Anwendung ausschließlich mit Zustimmung und unter angemessener Aufsicht einer verantwortlichen Person.']},
{title:'4. Konten und Zugangsdaten',paragraphs:['Persönliche Zugangsdaten, Zugriffstoken und sonstige Anmeldeinformationen dürfen nicht unkontrolliert weitergegeben, gemeinsam verwendet oder in frei zugänglichen Präsentationen und Notizen gespeichert werden. Nutzer haben angemessene Gerätesperren zu verwenden und Sitzungen auf gemeinsam genutzten Gemeindecomputern nach Abschluss der Arbeit vollständig zu beenden. Verlorene Geräte, verdächtige Anmeldungen oder ein möglicher Zugriff durch Unberechtigte sind unverzüglich zu melden, damit betroffene Zugänge geändert oder gesperrt werden können.']},
{title:'5. Verantwortung im Livebetrieb',paragraphs:['Die jeweils bedienende Person prüft vor ON AIR eigenverantwortlich die verknüpfte Veranstaltung, den vollständigen Ablauf, sichtbare Inhalte, Übergänge, Timer, Medien, Audioquellen sowie die Zuordnung von MAIN, STAGE, Livestream und Recording. Vorschau, Preflight und Testbetrieb sind technische Hilfen, können aber falsche Inhalte, fehlerhafte Rechtezuordnungen oder externe Störungen nicht vollständig erkennen und ersetzen keine menschliche Endkontrolle. Für kritische Veranstaltungen soll eine eingewiesene zweite Person erreichbar sein und ein praktikabler Ersatzablauf ohne Cloud- oder Netzverbindung vorbereitet werden.']},
{title:'6. Inhalte und Medienrechte',paragraphs:['Es dürfen ausschließlich Texte, Bilder, Videos, Musik, Schriften, Bibelübersetzungen und sonstige Medien eingestellt oder öffentlich wiedergegeben werden, für die alle im konkreten Nutzungsumfang erforderlichen Rechte, Lizenzen oder Einwilligungen bestehen. Dies umfasst insbesondere Urheber-, Persönlichkeits-, Marken-, Datenschutz-, Aufführungs-, Streaming- und Vervielfältigungsrechte; eine technische Importmöglichkeit ist keine Bestätigung der rechtlichen Zulässigkeit. Die verantwortliche Organisation dokumentiert erforderliche Nachweise und entfernt Inhalte unverzüglich, wenn Rechte fehlen, ablaufen oder von Berechtigten nachvollziehbar beanstandet werden.']},
{title:'7. Unzulässige Nutzung',paragraphs:['Untersagt ist jede Verwendung für rechtswidrige, diskriminierende, menschenverachtende, täuschende, schädigende oder sicherheitsgefährdende Inhalte sowie für Handlungen, die Rechte anderer Personen oder Organisationen verletzen. Ebenso unzulässig sind das Umgehen technischer Schutzmaßnahmen, automatisierte Überlastungsversuche, Manipulation fremder Veranstaltungen und der Versuch, nicht freigegebene Daten oder Systeme auszulesen. Erkennbare Fehlfunktionen dürfen nicht ausgenutzt werden; sie sind so zu melden, dass keine zusätzlichen Schäden oder unnötigen Veröffentlichungen entstehen.']},
{title:'8. Dienste Dritter',paragraphs:['Für angebundene Dienste wie Unsplash, GitHub, Firebase, Radio Browser, Bibeltextquellen, Übersetzungsmodelle oder eingebettete Webseiten gelten zusätzlich die Bedingungen, Datenschutzregeln und Lizenzvorgaben des jeweiligen Anbieters. GottesdienstRegie kontrolliert weder deren dauerhafte Verfügbarkeit noch die Richtigkeit, Sicherheit oder rechtliche Zulässigkeit fremder Inhalte und kann Schnittstellenänderungen oder Sperrungen nicht ausschließen. Vor einer öffentlichen Verwendung sind Quelle, Aktualität und Nutzungsrecht zu prüfen; erforderliche Konten oder Schlüssel werden eigenverantwortlich verwaltet.']},
{title:'9. Cloud und Synchronisierung',paragraphs:['Präsentationen, Metadaten, Änderungshistorien, Notizen und Medienreferenzen können abhängig von Konfiguration und Berechtigung lokal, in einer Team-Cloud oder auf mehreren Geräten gespeichert werden. Synchronisierung kann durch fehlendes Netzwerk, konkurrierende Bearbeitung, abgelaufene Zugänge oder technische Störungen verzögert beziehungsweise verhindert werden. Nutzer prüfen deshalb vor kritischen Veranstaltungen, ob der erwartete Stand einschließlich benötigter Medien auf dem tatsächlich eingesetzten Gerät verfügbar ist, und bewahren bei wichtigen Projekten zusätzlich eine aktuelle Sicherung auf.']},
{title:'10. Lokale Speicherung und Cache',paragraphs:['Die Anwendung speichert unter anderem Einstellungen, Vorschaudaten, Übersetzungsmodelle, temporäre Dateien und technische Zwischenergebnisse lokal auf dem verwendeten Gerät. Andere Personen mit Zugriff auf dasselbe Betriebssystemkonto können je nach Gerätekonfiguration auf Teile dieser Daten zugreifen; vertrauliche Angaben sollen deshalb nur im dafür vorgesehenen Umfang gespeichert werden. Das bestätigte Leeren ausgewiesener Cachebereiche ist endgültig und kann einen erneuten Download erforderlich machen, soll jedoch gespeicherte Präsentationen, Originalmedien und persönliche Inhalte außerhalb des bezeichneten Cachebereichs nicht entfernen.']},
{title:'11. Übersetzung und Sprachmodelle',paragraphs:['Automatisch erzeugte Übersetzungen können sprachlich, sachlich, kulturell oder theologisch unzutreffend sein und dürfen nicht ohne inhaltliche Prüfung als verbindliche Übersetzung behandelt werden. Die verantwortliche Person kontrolliert insbesondere Eigennamen, Bibelstellen, Liedtexte, Fachbegriffe und Aussagen, deren falsche Wiedergabe Personen verletzen oder den Sinn wesentlich verändern könnte. Herunterladbare Sprachmodelle benötigen lokalen Speicherplatz und beim ersten Bezug eine Internetverbindung; bei der Weitergabe einer Präsentation muss das benötigte Modell gegebenenfalls auch auf dem Zielgerät installiert werden.']},
{title:'12. Updates und Änderungen',paragraphs:['Aktualisierungen können Funktionen ergänzen, verändern oder entfernen sowie Dateiformate, Systemvoraussetzungen, Sicherheitsmechanismen und diese Nutzungsbedingungen anpassen. Vor einem Update sind laufende Ausgaben zu beenden, wichtige Präsentationen zu sichern und ausreichend Zeit für Installation und anschließende Kontrolle einzuplanen; Updates sollen nicht unmittelbar vor einer Veranstaltung ungeprüft eingespielt werden. Wesentliche Änderungen werden mit Versionsnummer und Datum kenntlich gemacht, wobei ältere Versionen aus Sicherheits- oder Kompatibilitätsgründen nicht dauerhaft unterstützt werden müssen.']},
{title:'13. Verfügbarkeit und Datensicherung',paragraphs:['Eine ununterbrochene, fehlerfreie oder für jeden Einsatzzweck geeignete Verfügbarkeit der Anwendung und verbundener Dienste wird nicht zugesagt. Wartung, Updates, Netzwerkausfälle, Änderungen externer Schnittstellen oder Fehler an Computern und Ausgabegeräten können Funktionen zeitweise einschränken. Nutzer erstellen deshalb in angemessenen Abständen überprüfbare Sicherungskopien und halten für den Ausfall von Netzwerk, Cloud, Medienserver, Audio, Computer oder Ausgabegerät einen organisatorisch erprobten Ersatzplan bereit.']},
{title:'14. Gewährleistung',paragraphs:['Die Anwendung wird im Rahmen der gesetzlichen Vorgaben in dem jeweils verfügbaren Entwicklungsstand bereitgestellt. Funktionsbeschreibungen, Bildschirmdarstellungen, Roadmaps, Hilfetexte und Versionshinweise erläutern die beabsichtigte Nutzung, stellen jedoch ohne ausdrückliche Vereinbarung keine Garantie einer bestimmten Eigenschaft oder dauerhaften Verfügbarkeit dar. Gesetzlich zwingende Rechte, insbesondere bei vorsätzlich verschwiegenen Mängeln oder ausdrücklich übernommenen Garantien, bleiben durch diese Regelung unberührt.']},
{title:'15. Haftung',paragraphs:['Für Vorsatz und grobe Fahrlässigkeit sowie für Schäden aus der Verletzung von Leben, Körper oder Gesundheit gelten die gesetzlichen Haftungsregeln. Bei leicht fahrlässiger Verletzung wesentlicher Pflichten ist die Haftung, soweit gesetzlich zulässig, auf den bei Bereitstellung vorhersehbaren und typischen Schaden begrenzt; dies betrifft insbesondere nicht vermeidbare Folgeschäden aus fehlenden Sicherungen oder einem nicht vorbereiteten Ersatzablauf. Zwingende Haftungsvorschriften, Ansprüche nach dem Produkthaftungsrecht und eine ausdrücklich übernommene Garantie bleiben uneingeschränkt unberührt.']},
{title:'16. Verantwortung für Ansprüche Dritter',paragraphs:['Wer Inhalte ohne ausreichende Rechte, Einwilligungen oder Freigaben einstellt oder öffentlich verwendet, informiert die verantwortliche Organisation unverzüglich über daraus entstehende Beanstandungen oder Ansprüche. Die betreffende Person stellt vorhandene Herkunfts-, Lizenz- und Bearbeitungsinformationen vollständig bereit und unterstützt die sachgerechte Prüfung und Abwehr, soweit dies rechtlich zulässig und zumutbar ist. Eigene gesetzliche Verantwortlichkeiten werden durch die technische Bereitstellung der Anwendung oder eine Freigabe innerhalb eines Teams nicht auf den Anbieter übertragen.']},
{title:'17. Beendigung und Kündigung',paragraphs:['Die Nutzung kann jederzeit durch Abmeldung und Deinstallation beendet werden; zuvor sind benötigte Präsentationen und Medien in einem geeigneten, weiterhin zugänglichen Format zu sichern. Zugänge dürfen bei Sicherheitsrisiken, Rechtsverstößen, missbräuchlicher Nutzung oder Wegfall der organisatorischen Berechtigung vorübergehend eingeschränkt oder dauerhaft gesperrt werden. Lokale Daten werden durch eine Kontosperre nicht zwingend automatisch gelöscht, und gesetzliche oder organisatorische Aufbewahrungspflichten bleiben auch nach Ende der Nutzung bestehen.']},
{title:'18. Schlussbestimmungen',paragraphs:['Es gilt deutsches Recht, soweit zwingende verbraucherschützende oder andere gesetzliche Regelungen keine abweichende Rechtswahl verlangen. Sollte eine einzelne Bestimmung ganz oder teilweise unwirksam oder undurchführbar sein, bleiben die übrigen Bestimmungen wirksam; an die Stelle der betroffenen Regelung tritt die gesetzliche Regelung. Maßgeblich ist die bei der jeweiligen Zustimmung bereitgestellte und mit Versionsnummer gekennzeichnete Fassung; Übersetzungen oder Kurzfassungen dienen nur der besseren Verständlichkeit.']},
];
export function plainTerms(){return `GottesdienstRegie – Nutzungsbedingungen\nVersion ${TERMS_VERSION} · Gültig ab ${TERMS_EFFECTIVE_DATE}\n\n${termsSections.map(section=>`${section.title}\n${section.paragraphs.map(paragraph=>`- ${paragraph}`).join('\n')}`).join('\n\n')}`}
