export const TERMS_VERSION='2.0';
export const TERMS_EFFECTIVE_DATE='20. September 2026';
export type TermsSection={title:string;paragraphs:string[]};
export const termsSections:TermsSection[]=[
{title:'1. Geltungsbereich',paragraphs:['Diese Nutzungsbedingungen gelten für die Installation und Verwendung der Anwendung GottesdienstRegie einschließlich ihrer Desktop-, Cloud-, Medien-, Übersetzungs-, Fernsteuerungs- und Updatefunktionen. Mit Installation, Anmeldung oder Aktualisierung werden sie in ihrer jeweils angezeigten Fassung akzeptiert.']},
{title:'2. Anbieter und Kontakt',paragraphs:['GottesdienstRegie wird als Arbeitsmittel der Philippus Gemeinde Bielefeld e. V. bereitgestellt. Fragen, Fehler- oder Sicherheitsmeldungen sind an die in der Anwendung angegebene Kontaktadresse zu richten.']},
{title:'3. Nutzungsvoraussetzungen',paragraphs:['Die Anwendung darf nur von berechtigten Personen und im Rahmen der jeweiligen Gemeinde- oder Organisationsaufgabe genutzt werden. Minderjährige verwenden sie nur mit Zustimmung und Aufsicht einer verantwortlichen Person.']},
{title:'4. Konten und Zugangsdaten',paragraphs:['Zugangsdaten sind persönlich, geheim zu halten und vor Zugriff Dritter zu schützen. Auf gemeinsam genutzten Geräten ist die Sitzung nach Abschluss der Arbeit zu beenden. Verdächtige Zugriffe sind unverzüglich zu melden.']},
{title:'5. Verantwortung im Livebetrieb',paragraphs:['Nutzer prüfen Veranstaltung, Ablauf, Inhalte, Ausgabegeräte, Audio, MAIN, STAGE, Livestream und Recording vor ON AIR selbst. Vorschau, Preflight und Testbetrieb unterstützen diese Prüfung, ersetzen aber keine verantwortliche Kontrolle.']},
{title:'6. Inhalte und Medienrechte',paragraphs:['Es dürfen nur Texte, Bilder, Videos, Musik, Schriften, Bibeltexte und sonstige Medien verwendet werden, für die ausreichende Rechte oder Erlaubnisse bestehen. Die Verantwortung für Urheber-, Persönlichkeits-, Marken-, Lizenz- und Aufführungsrechte liegt bei der einstellenden Organisation.']},
{title:'7. Unzulässige Nutzung',paragraphs:['Unzulässig sind rechtswidrige, diskriminierende, schädigende oder sicherheitsgefährdende Inhalte, die Umgehung technischer Schutzmaßnahmen sowie die Nutzung zur Störung fremder Systeme oder Veranstaltungen.']},
{title:'8. Dienste Dritter',paragraphs:['Unsplash, GitHub, Firebase, Radio Browser, Übersetzungsmodelle und eingebettete Webinhalte unterliegen zusätzlich den Bedingungen ihrer jeweiligen Anbieter. Verfügbarkeit, Inhalte und Datenschutz dieser Dienste werden nicht von GottesdienstRegie kontrolliert.']},
{title:'9. Cloud und Synchronisierung',paragraphs:['Präsentationen, Metadaten, Änderungshistorien und Medienreferenzen können abhängig von der Konfiguration lokal oder synchronisiert gespeichert werden. Nutzer prüfen vor kritischen Veranstaltungen, ob der erwartete Stand vollständig verfügbar ist.']},
{title:'10. Lokale Speicherung und Cache',paragraphs:['Die Anwendung speichert Einstellungen, Modelle, Vorschaudaten und temporäre Dateien lokal. Das Leeren ausdrücklich ausgewiesener Cachebereiche ist endgültig; Präsentationen, gespeicherte Übersetzungen und Originalmedien dürfen davon nicht betroffen sein.']},
{title:'11. Übersetzung und Sprachmodelle',paragraphs:['Automatische Übersetzungen können sachlich, sprachlich oder theologisch fehlerhaft sein. Jede Übersetzung ist vor ihrer Anzeige zu prüfen. Sprachmodelle benötigen Speicherplatz und gegebenenfalls eine Internetverbindung; gespeicherte Texte bleiben unabhängig vom Modell erhalten.']},
{title:'12. Updates und Änderungen',paragraphs:['Updates dürfen Funktionen, Dateiformate, Sicherheitsanforderungen und diese Bedingungen ändern. Vor einer Aktualisierung sind laufende Ausgaben zu beenden und wichtige Präsentationen zu sichern. Wesentliche Änderungen werden mit Versionsdatum kenntlich gemacht.']},
{title:'13. Verfügbarkeit und Datensicherung',paragraphs:['Eine ununterbrochene oder fehlerfreie Verfügbarkeit wird nicht zugesagt. Nutzer halten geeignete Backups und einen betrieblichen Ersatzplan für Ausfälle von Netzwerk, Cloud, Medien, Computern oder Ausgabegeräten bereit.']},
{title:'14. Gewährleistung',paragraphs:['Die Anwendung wird im Rahmen der gesetzlichen Vorgaben bereitgestellt. Beschreibungen und Hilfetexte sind keine Garantie bestimmter Eigenschaften. Zwingende gesetzliche Rechte bleiben unberührt.']},
{title:'15. Haftung',paragraphs:['Für Vorsatz und grobe Fahrlässigkeit sowie für Schäden aus Verletzung von Leben, Körper oder Gesundheit gilt die gesetzliche Haftung. Bei leicht fahrlässiger Verletzung wesentlicher Vertragspflichten ist die Haftung im gesetzlich zulässigen Umfang auf den vorhersehbaren typischen Schaden begrenzt. Zwingende Haftungsvorschriften bleiben unberührt.']},
{title:'16. Verantwortung für Ansprüche Dritter',paragraphs:['Wer rechtswidrige oder nicht ausreichend lizenzierte Inhalte einsetzt, unterstützt die verantwortliche Organisation bei der Abwehr daraus entstehender Ansprüche und stellt die erforderlichen Informationen bereit, soweit dies gesetzlich zulässig ist.']},
{title:'17. Beendigung und Kündigung',paragraphs:['Die Nutzung kann jederzeit durch Deinstallation und Abmeldung beendet werden. Zugänge können bei Sicherheitsrisiken, Rechtsverstößen oder Wegfall der Berechtigung gesperrt werden. Gesetzliche Aufbewahrungspflichten bleiben bestehen.']},
{title:'18. Schlussbestimmungen',paragraphs:['Es gilt deutsches Recht, soweit zwingendes Recht nichts anderes bestimmt. Sollten einzelne Regelungen unwirksam sein, bleiben die übrigen Regelungen unberührt. Maßgeblich ist die bei Zustimmung bereitgestellte Fassung.']},
];
export function plainTerms(){return `GottesdienstRegie – Nutzungsbedingungen\nVersion ${TERMS_VERSION} · Gültig ab ${TERMS_EFFECTIVE_DATE}\n\n${termsSections.map(section=>`${section.title}\n${section.paragraphs.join('\n\n')}`).join('\n\n')}`}
