import{useEffect,useState}from'react';
import{cancelTranslationPack,refreshTranslationPacks,downloadTranslationPack}from'./translationPackManager';
import type{TranslationPackDescriptor,TranslationPackProgress}from'./translationPackTypes';
import{formatStorageBytes}from'./storageMaintenance';
import{FlagIcon}from'./flags/FlagIcon';

export function TranslationPackSettings(){
 const[items,setItems]=useState<TranslationPackDescriptor[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(''),[progress,setProgress]=useState<TranslationPackProgress|null>(null),[error,setError]=useState('');
 const load=()=>refreshTranslationPacks().then(setItems);useEffect(()=>{void load()},[]);
 const shown=items.filter(item=>`${item.source} ${item.target} ${item.model}`.toLowerCase().includes(query.toLowerCase()));
 const start=async(item:TranslationPackDescriptor)=>{setBusy(item.key);setError('');setProgress({key:item.key,status:'downloading',downloadedBytes:0,percent:0});try{await downloadTranslationPack(item.source,item.target,setProgress);await load()}catch(reason){if(!String(reason).includes('ABORT'))setError(`Das Sprachpaket konnte nicht geladen werden: ${String(reason)}`)}finally{setBusy('');setProgress(null)}};
 return <section className="settings-group translation-pack-settings"><h4>LOKALE SPRACHPAKETE</h4><p>Bereit bedeutet, dass alle Modelldateien vollständig geprüft wurden. Ein Download startet nur nach deinem Klick. Präsentationen speichern den übersetzten Text; für neue automatische Übersetzungen muss das passende Paket auf jedem verwendeten Computer vorhanden sein.</p><input type="search" placeholder="Sprachpakete suchen …" value={query} onChange={event=>setQuery(event.target.value)}/>{error&&<p className="error">{error}</p>}<div>{shown.map(item=>{const active=busy===item.key,value=active?progress:null;return <article key={item.key}><span className="pack-language-pair"><FlagIcon languageCode={item.source} decorative/><b>{item.source.toUpperCase()} → {item.target.toUpperCase()}</b><FlagIcon languageCode={item.target} decorative/><small>{item.model} · {item.revision}</small></span><span>{active?(value?.totalBytes?`${value.percent}% · ${formatStorageBytes(value.downloadedBytes)} / ${formatStorageBytes(value.totalBytes)}`:`Wird geladen · ${formatStorageBytes(value?.downloadedBytes??0)}`):item.status==='ready'?'Bereit':item.status==='error'?'Fehler':'Nicht heruntergeladen'}</span>{active?<button type="button" onClick={()=>void cancelTranslationPack(item.key)}><span className="material-symbols-outlined">cancel</span> Abbrechen</button>:item.status==='ready'?<button type="button" onClick={async()=>{await (window.desktop as any)?.translationPacks?.remove(item.key);await load()}}><span className="material-symbols-outlined">delete</span> Entfernen</button>:<button type="button" disabled={Boolean(busy)} onClick={()=>void start(item)}><span className="material-symbols-outlined">cloud_download</span> {item.status==='error'?'Erneut versuchen':'Herunterladen'}</button>}</article>})}</div></section>
}
