/// <reference types="vite/client" />
interface DesktopDisplay { id:number;label:string;primary:boolean;bounds:{x:number;y:number;width:number;height:number};workArea:{x:number;y:number;width:number;height:number};scaleFactor:number;rotation:number;touchSupport:string }
interface DesktopUpdateStatus { state:'idle'|'checking'|'available'|'not-available'|'downloading'|'downloaded'|'rollback-downloading'|'rollback-ready'|'error'|'development';version?:string;percent?:number;releaseNotes?:string;message?:string }
interface DesktopVersionMetadata{version:string;installedAt:string;modifiedAt:string;fileSize:number;executable:string}
interface DesktopPreviousVersion{version:string;publishedAt:string;size:number;url:string}
interface DesktopOutputStatus{role:string;state:'ready'|'missing'|'closed'}
interface DesktopPreflight{ok:boolean;errors:string[];warnings:string[];displays?:DesktopDisplay[]}
interface DesktopOperatorPreferences{windowStartMode:'fullscreen'|'maximized'|'window'|'restore';operatorDisplayTarget:'primary'|'last';automaticUpdates:boolean;autoDownloadUpdates:boolean}
interface PresentationSummary{id:string;title:string;date:string;createdAt:string;updatedAt:string;archived:boolean;trashed:boolean;itemCount:number;slideCount:number}
interface MediaAsset{id:string;name:string;fileName:string;url:string;kind:'image'|'video'|'audio'|'pdf';extension:string;size:number;checksum:string;createdAt:string;favorite:boolean;tags:string[]}
interface Window { desktop?: { displays:()=>Promise<DesktopDisplay[]>;onDisplaysChanged:(callback:(displays:DesktopDisplay[])=>void)=>()=>void;identifyDisplays:(assignments:Record<string,string>)=>Promise<boolean>;preflight:(assignments:Record<string,string>,presentation:{hasPresentation:boolean;activeSlideCount:number;media:string[]})=>Promise<DesktopPreflight>;goOnAir:(assignments:Record<string,string>,payload:unknown)=>Promise<boolean>;goOffAir:()=>Promise<boolean>;sendLiveSlide:(payload:unknown)=>Promise<boolean>;onLiveSlide:(callback:(payload:unknown)=>void)=>()=>void;onOutputStatus:(callback:(payload:DesktopOutputStatus)=>void)=>()=>void;openExternal:(url:string)=>Promise<boolean>;media:{list:()=>Promise<MediaAsset[]>;import:()=>Promise<MediaAsset[]>;update:(id:string,patch:Partial<MediaAsset>)=>Promise<MediaAsset>;remove:(id:string)=>Promise<boolean>};presentation:{list:(options?:{archived?:boolean;trashed?:boolean})=>Promise<PresentationSummary[]>;create:(input:{title?:string;date?:string;template?:unknown})=>Promise<unknown>;save:(document:unknown)=>Promise<PresentationSummary>;load:(id?:string)=>Promise<unknown|null>;duplicate:(id:string)=>Promise<unknown>;rename:(id:string,title:string)=>Promise<PresentationSummary>;archive:(id:string,value:boolean)=>Promise<PresentationSummary>;trash:(id:string,value:boolean)=>Promise<PresentationSummary>;import:()=>Promise<unknown|null>;export:(id:string)=>Promise<string|null>;backup:(id:string)=>Promise<string>;recovery:()=>Promise<{summary:PresentationSummary;document:unknown}|null>;markClean:()=>Promise<boolean>};session:{read:()=>Promise<string|null>;write:(token:string)=>Promise<boolean>;clear:()=>Promise<boolean>};auth:{login:(email:string,password:string,remember:boolean)=>Promise<import('./auth').LoginResult>;verifyTwoFactor:(challengeId:string,code:string,recovery:boolean)=>Promise<import('./auth').AuthSession>;cancelTwoFactor:(challengeId:string)=>Promise<boolean>;restore:()=>Promise<import('./auth').AuthSession|null>;logout:()=>Promise<boolean>;connection:()=>Promise<boolean>};updates:{currentVersion:()=>Promise<string>;metadata:()=>Promise<DesktopVersionMetadata>;check:()=>Promise<DesktopUpdateStatus>;download:()=>Promise<boolean>;install:()=>Promise<boolean>;previous:()=>Promise<DesktopPreviousVersion|null>;rollback:()=>Promise<boolean>;onStatus:(callback:(status:DesktopUpdateStatus)=>void)=>()=>void} } }
